/**
 * Catálogo Kanto completo (Fase 6.3-A — expansão para a estética própria).
 *
 * Este arquivo completa a Pokédex com TODAS as espécies de Kanto (ids 1–151)
 * que ainda não existiam, mais Steelix (208), que fecha a linha do Onix.
 * Motivação do mantenedor: o catálogo cheio é a base para criar a estética
 * própria do jogo no futuro — nada de fora agora significa não caçar conteúdo
 * depois.
 *
 * Fonte das sprites: mesma de todo o projeto — PokeAPI/sprites no CDN do
 * GitHub, padrão Gen V preto-e-branco animado (front/back/shiny). Cobertura
 * verificada por listagem da árvore Git do repositório em 2026-09-06: TODOS
 * os ids 1–151 e 208 têm as três variações animadas. (Animados existem só
 * até o id 649; quando passarmos de Gen 5, será preciso outra fonte.)
 *
 * Decisões de conteúdo:
 * - Tipagem e status-base CANÔNICOS modernos (Fairy conta desde já: Clefairy,
 *   Jigglypuff, Mr. Mime; Magnemite é Electric/Steel).
 * - Evoluções por PEDRA ou TROCA viram gatilho de nível PROVISÓRIO (mesma
 *   decisão já registrada para Staryu/Eevee na 6.3) — marcadas com `// pedra`
 *   e `// troca`. Quando os itens de evolução existirem, os gatilhos trocam.
 * - Vaporeon/Jolteon/Flareon existem como espécie, mas NÃO estão ligadas à
 *   Eevee: escolher entre três destinos exige mecânica de escolha/pedras,
 *   que ainda não existe. Eevee segue evoluindo para Umbreon (nível 30).
 * - Learnsets seguem a filosofia da 6.2-C: fraco (20–40) no nível 1,
 *   upgrade ~35 no 7, médio (50–65) no 12–20, forte (80+) do 28 em diante.
 *
 * Este módulo NÃO importa nada em runtime de `pokedex.ts` (só tipos, que
 * somem na compilação) para não criar ciclo de módulos: ele recebe
 * `ALL_MOVES` de quem o chama.
 */
import type { AllMoves, EvolvesTo, PokemonSpeciesData } from "./pokedex";

type MoveKey = keyof AllMoves;
type Bases = [number, number, number, number, number, number];

const SPRITE_BASE =
  "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated";

function spriteUrl(id: number, variant?: "back" | "shiny"): string {
  return variant
    ? `${SPRITE_BASE}/${variant}/${id}.gif`
    : `${SPRITE_BASE}/${id}.gif`;
}

/** Espécies novas, em ordem de id. Chamado por `pokedex.ts` com `ALL_MOVES`. */
export function gen1Rest(M: AllMoves): PokemonSpeciesData[] {
  const sp = (
    id: number,
    name: string,
    types: [string] | [string, string],
    bases: Bases,
    catchRate: number,
    moves: ReadonlyArray<readonly [number, MoveKey]>,
    evolve: ReadonlyArray<EvolvesTo> | undefined,
    description: string
  ): PokemonSpeciesData => ({
    id,
    name,
    types,
    baseHp: bases[0],
    baseAtk: bases[1],
    baseDef: bases[2],
    baseSpAtk: bases[3],
    baseSpDef: bases[4],
    baseSpd: bases[5],
    catchRate,
    learnset: moves.map(([level, key]) => ({ level, move: M[key] })),
    evolvesTo: evolve?.map((e) => ({ ...e })),
    frontSprite: spriteUrl(id),
    backSprite: spriteUrl(id, "back"),
    shinyFrontSprite: spriteUrl(id, "shiny"),
    description,
  });

  return [
    // ── Insetos iniciais ───────────────────────────────────────────────────
    sp(10, "Caterpie", ["Bug"], [45, 30, 35, 20, 20, 45], 255,
      [[1, "Tackle"], [9, "FuryCutter"]], [{ speciesId: 11, trigger: "level", level: 7 }],
      "Come folhas sem parar; o cheiro adocicado afasta predadores."),
    sp(11, "Metapod", ["Bug"], [50, 20, 55, 25, 25, 30], 120,
      [[1, "Tackle"], [9, "FuryCutter"]], [{ speciesId: 12, trigger: "level", level: 10 }],
      "Dentro do casco duro, o corpo se reorganiza para a metamorfose."),
    sp(12, "Butterfree", ["Bug", "Flying"], [60, 45, 50, 90, 80, 70], 45,
      [[1, "Gust"], [1, "Confusion"], [13, "BugBite"], [22, "Psybeam"], [32, "AirSlash"], [44, "Psychic"]], undefined,
      "Suas asas cobertas de escamas venenosas brilham sob o sol."),
    sp(13, "Weedle", ["Bug", "Poison"], [40, 35, 30, 20, 20, 50], 255,
      [[1, "PoisonSting"], [9, "FuryCutter"]], [{ speciesId: 14, trigger: "level", level: 7 }],
      "O ferrão na cabeça protege o corpo macio enquanto rói folhas."),
    sp(14, "Kakuna", ["Bug", "Poison"], [45, 25, 50, 25, 25, 35], 120,
      [[1, "PoisonSting"], [9, "FuryCutter"]], [{ speciesId: 15, trigger: "level", level: 10 }],
      "Quase imóvel no casco; o ferrão permanece afiado para defesa."),
    sp(15, "Beedrill", ["Bug", "Poison"], [65, 90, 40, 45, 80, 75], 45,
      [[1, "FuryCutter"], [1, "PoisonSting"], [13, "BugBite"], [20, "Sludge"], [30, "XScissor"], [42, "SludgeBomb"]], undefined,
      "Ataca em enxame; os três ferrões injetam veneno potente."),

    // ── Aves e roedores comuns ─────────────────────────────────────────────
    sp(16, "Pidgey", ["Normal", "Flying"], [40, 45, 40, 35, 35, 56], 255,
      [[1, "Tackle"], [1, "Gust"], [7, "QuickAttack"], [13, "WingAttack"]],
      [{ speciesId: 17, trigger: "level", level: 18 }],
      "Muito comum; agita areia com as asas para fugir de perigos."),
    sp(17, "Pidgeotto", ["Normal", "Flying"], [63, 60, 55, 50, 50, 71], 120,
      [[1, "Gust"], [1, "QuickAttack"], [13, "WingAttack"], [26, "AirSlash"], [40, "BodySlam"]],
      [{ speciesId: 18, trigger: "level", level: 36 }],
      "Defende um território vasto, patrulhando-o do alto todos os dias."),
    sp(18, "Pidgeot", ["Normal", "Flying"], [83, 80, 75, 70, 70, 101], 45,
      [[1, "Gust"], [1, "QuickAttack"], [13, "WingAttack"], [26, "AirSlash"], [46, "BodySlam"]], undefined,
      "Voa em velocidade de mach 2; o rastro dobra as copas das árvores."),
    sp(19, "Rattata", ["Normal"], [30, 56, 35, 25, 35, 72], 255,
      [[1, "Tackle"], [7, "QuickAttack"], [14, "Bite"], [23, "BodySlam"]],
      [{ speciesId: 20, trigger: "level", level: 20 }],
      "Rói qualquer coisa com os incisivos que crescem a vida toda."),
    sp(20, "Raticate", ["Normal"], [55, 81, 60, 50, 70, 97], 127,
      [[1, "QuickAttack"], [14, "Bite"], [24, "BodySlam"], [40, "DarkPulse"]], undefined,
      "Os bigodes dão equilíbrio; sem eles, fica mais lento e nervoso."),
    sp(21, "Spearow", ["Normal", "Flying"], [40, 60, 30, 31, 31, 70], 255,
      [[1, "Tackle"], [1, "Gust"], [7, "QuickAttack"], [13, "WingAttack"]],
      [{ speciesId: 22, trigger: "level", level: 20 }],
      "Valente e barulhento; bate as asas para espantar invasores."),
    sp(22, "Fearow", ["Normal", "Flying"], [65, 90, 65, 61, 61, 100], 90,
      [[1, "Gust"], [1, "QuickAttack"], [13, "WingAttack"], [26, "AirSlash"], [44, "DarkPulse"]], undefined,
      "Sobrevoa vastos territórios sem descanso usando o bico longo."),
    sp(23, "Ekans", ["Poison"], [35, 60, 44, 40, 54, 55], 255,
      [[1, "PoisonSting"], [13, "Bite"], [20, "Sludge"], [34, "SludgeBomb"]],
      [{ speciesId: 24, trigger: "level", level: 22 }],
      "Desfere mordidas venenosas e engole presas inteiras, devagar."),
    sp(24, "Arbok", ["Poison"], [60, 95, 69, 65, 79, 80], 90,
      [[1, "PoisonSting"], [13, "Bite"], [22, "Sludge"], [38, "SludgeBomb"]], undefined,
      "Os padrões da capa assustam presas antes da constrição final."),
    sp(26, "Raichu", ["Electric"], [60, 90, 55, 90, 80, 110], 75,
      [[1, "ThunderShock"], [1, "QuickAttack"], [12, "Spark"], [36, "Thunderbolt"], [48, "Thunder"]], undefined,
      "A cauda descarrega raios ao cravar no chão; chega a 100 mil volts."),

    // ── Desertos, cavernas e Nidoran ───────────────────────────────────────
    sp(27, "Sandshrew", ["Ground"], [50, 75, 85, 20, 30, 40], 255,
      [[1, "Scratch"], [1, "MudSlap"], [15, "Dig"], [32, "Earthquake"]],
      [{ speciesId: 28, trigger: "level", level: 22 }],
      "Enrola-se em bola e rola pelos desertos que chama de lar."),
    sp(28, "Sandslash", ["Ground"], [75, 100, 110, 45, 55, 65], 90,
      [[1, "MudSlap"], [15, "Dig"], [34, "Earthquake"], [42, "SludgeBomb"]], undefined,
      "As garras afiam em pedras duras; cavam ninhos fundos no solo."),
    sp(29, "Nidoran♀", ["Poison"], [55, 47, 52, 40, 40, 41], 235,
      [[1, "Scratch"], [1, "PoisonSting"], [14, "Sludge"]],
      [{ speciesId: 30, trigger: "level", level: 16 }],
      "As espinhas das costas crescem quando ameaçada; o veneno é fraco."),
    sp(30, "Nidorina", ["Poison"], [70, 62, 67, 55, 55, 56], 120,
      [[1, "Scratch"], [1, "PoisonSting"], [14, "Sludge"], [28, "SludgeBomb"]],
      [{ speciesId: 31, trigger: "level", level: 30 }], // pedra (Lua)
      "Fica de vigia pelos arredores; as presas secam veneno com facilidade."),
    sp(31, "Nidoqueen", ["Poison", "Ground"], [90, 92, 87, 75, 85, 76], 45,
      [[1, "PoisonSting"], [14, "Sludge"], [26, "Earthquake"], [38, "SludgeBomb"]], undefined,
      "Corpo coberto de escamas duras; a investida derruba árvores."),
    sp(32, "Nidoran♂", ["Poison"], [46, 57, 40, 40, 40, 50], 235,
      [[1, "Tackle"], [1, "PoisonSting"], [14, "Sludge"]],
      [{ speciesId: 33, trigger: "level", level: 16 }],
      "Move as orelhas grandes em qualquer direção para ouvir perigos."),
    sp(33, "Nidorino", ["Poison"], [61, 72, 57, 55, 55, 65], 120,
      [[1, "Tackle"], [1, "PoisonSting"], [14, "Sludge"], [28, "SludgeBomb"]],
      [{ speciesId: 34, trigger: "level", level: 30 }], // pedra (Lua)
      "Impulsivo: ataca primeiro e avalia o perigo depois, chifre à frente."),
    sp(34, "Nidoking", ["Poison", "Ground"], [81, 102, 77, 85, 75, 85], 45,
      [[1, "PoisonSting"], [14, "Sludge"], [26, "Earthquake"], [38, "SludgeBomb"]], undefined,
      "A cauda poderosa esmaga; o chifre libera veneno ao perfurar."),

    // ── Fadas e raposas ────────────────────────────────────────────────────
    sp(35, "Clefairy", ["Fairy"], [70, 45, 48, 60, 65, 35], 150,
      [[1, "Tackle"], [1, "FairyWind"], [28, "PlayRough"]],
      [{ speciesId: 36, trigger: "level", level: 30 }], // pedra (Lua)
      "Adorável e raro; dança sob a luz da lua cheia em montanhas distantes."),
    sp(36, "Clefable", ["Fairy"], [95, 70, 73, 95, 90, 60], 25,
      [[1, "Tackle"], [1, "FairyWind"], [28, "PlayRough"], [44, "Moonblast"]], undefined,
      "Ouvido a quilômetros: fuga silenciosa e ouvido afinadíssimo."),
    sp(37, "Vulpix", ["Fire"], [38, 41, 40, 50, 65, 65], 190,
      [[1, "Ember"], [14, "FireFang"], [34, "Flamethrower"]],
      [{ speciesId: 38, trigger: "level", level: 30 }], // pedra (Fogo)
      "As seis caudas crescem com a idade; expelam chamas quentes."),
    sp(38, "Ninetales", ["Fire"], [73, 76, 75, 81, 100, 100], 75,
      [[1, "Ember"], [14, "FireFang"], [36, "Flamethrower"]], undefined,
      "Nove caudas douradas; dizem que vive mil anos guardando rancor."),
    sp(39, "Jigglypuff", ["Normal", "Fairy"], [115, 45, 20, 45, 25, 20], 170,
      [[1, "Tackle"], [1, "FairyWind"], [20, "BodySlam"], [28, "PlayRough"]],
      [{ speciesId: 40, trigger: "level", level: 30 }], // pedra (Lua)
      "Canta uma canção que adormece; infla os olhos quando irritado."),
    sp(40, "Wigglytuff", ["Normal", "Fairy"], [140, 70, 45, 85, 50, 45], 50,
      [[1, "Tackle"], [1, "FairyWind"], [20, "BodySlam"], [30, "PlayRough"], [46, "Moonblast"]], undefined,
      "O corpo elástico infla sem limites; os olhos grandes encantam."),

    // ── Cavernas e florestas ───────────────────────────────────────────────
    sp(41, "Zubat", ["Poison", "Flying"], [40, 45, 35, 30, 40, 55], 255,
      [[1, "PoisonSting"], [1, "Gust"], [13, "Bite"], [20, "WingAttack"], [28, "Sludge"], [36, "SludgeBomb"]],
      [{ speciesId: 42, trigger: "level", level: 22 }],
      "Cego de nascença; navega por ecolocalização na escuridão."),
    sp(42, "Golbat", ["Poison", "Flying"], [75, 80, 70, 65, 75, 90], 90,
      [[1, "Gust"], [1, "PoisonSting"], [13, "Bite"], [22, "WingAttack"], [32, "AirSlash"], [40, "SludgeBomb"]], undefined,
      "Bebe mais de 300 ml de sangue por vez; voa silencioso à noite."),
    sp(43, "Oddish", ["Grass", "Poison"], [45, 50, 55, 75, 65, 30], 255,
      [[1, "VineWhip"], [1, "PoisonSting"], [12, "RazorLeaf"], [24, "Sludge"]],
      [{ speciesId: 44, trigger: "level", level: 21 }],
      "Enterra-se no solo durante o dia e caminha sob a lua."),
    sp(44, "Gloom", ["Grass", "Poison"], [60, 65, 70, 85, 75, 40], 120,
      [[1, "VineWhip"], [1, "PoisonSting"], [12, "RazorLeaf"], [24, "Sludge"], [36, "SludgeBomb"]],
      [{ speciesId: 45, trigger: "level", level: 30 }], // pedra (Folha)
      "O mel que escorre da boca tem um cheiro capaz de derrubar adultos."),
    sp(45, "Vileplume", ["Grass", "Poison"], [75, 80, 85, 110, 90, 50], 45,
      [[1, "VineWhip"], [12, "RazorLeaf"], [24, "Sludge"], [38, "SludgeBomb"], [46, "SolarBeam"]], undefined,
      "As pétalas gigantes espalham pólen alérgeno ao abrir."),
    sp(46, "Paras", ["Bug", "Grass"], [35, 70, 55, 45, 55, 25], 190,
      [[1, "Scratch"], [1, "FuryCutter"], [13, "BugBite"], [22, "RazorLeaf"]],
      [{ speciesId: 47, trigger: "level", level: 24 }],
      "Os cogumelos das costas sugam nutrientes e dão ordens ao inseto."),
    sp(47, "Parasect", ["Bug", "Grass"], [60, 95, 80, 60, 80, 30], 75,
      [[1, "FuryCutter"], [13, "BugBite"], [22, "RazorLeaf"], [36, "XScissor"], [44, "SolarBeam"]], undefined,
      "O cogumelo dominou o hospedeiro; esporos saem das guelras."),
    sp(48, "Venonat", ["Bug", "Poison"], [60, 55, 50, 40, 55, 45], 190,
      [[1, "PoisonSting"], [1, "FuryCutter"], [17, "BugBite"], [25, "Sludge"]],
      [{ speciesId: 49, trigger: "level", level: 31 }],
      "Os olhos compostos funcionam como radar e enxergam na escuridão."),
    sp(49, "Venomoth", ["Bug", "Poison"], [70, 65, 60, 90, 75, 90], 75,
      [[1, "FuryCutter"], [17, "BugBite"], [25, "Sludge"], [36, "SludgeBomb"], [44, "Psychic"]], undefined,
      "As escamas das asas poeiram veneno a cada batida."),

    // ── Campo aberto e montes ──────────────────────────────────────────────
    sp(50, "Diglett", ["Ground"], [10, 55, 25, 35, 45, 95], 255,
      [[1, "MudSlap"], [16, "Dig"]],
      [{ speciesId: 51, trigger: "level", level: 26 }],
      "Vive em túneis; o corpo sob o solo nunca foi visto por ninguém."),
    sp(51, "Dugtrio", ["Ground"], [35, 100, 50, 50, 70, 120], 50,
      [[1, "MudSlap"], [16, "Dig"], [36, "Earthquake"]], undefined,
      "Trigêmeos que cavam juntos; a rede de túneis desestabiliza o chão."),
    sp(52, "Meowth", ["Normal"], [40, 45, 35, 40, 40, 90], 255,
      [[1, "Scratch"], [7, "QuickAttack"], [16, "Bite"], [28, "BodySlam"]],
      [{ speciesId: 53, trigger: "level", level: 28 }],
      "A moeda na testa brilha; adora objetos redondos e brilhantes."),
    sp(53, "Persian", ["Normal"], [65, 70, 60, 65, 65, 115], 90,
      [[1, "Scratch"], [7, "QuickAttack"], [16, "Bite"], [30, "BodySlam"], [44, "DarkPulse"]], undefined,
      "Elegante e orgulhoso; a gema na testa cintila na escuridão."),
    sp(54, "Psyduck", ["Water"], [50, 52, 48, 65, 50, 55], 190,
      [[1, "Bubble"], [16, "WaterPulse"], [28, "Confusion"], [40, "Psychic"]],
      [{ speciesId: 55, trigger: "level", level: 33 }],
      "Sofre de dores de cabeça constantes; nelas, desata poderes psíquicos."),
    sp(55, "Golduck", ["Water"], [80, 82, 78, 95, 80, 85], 75,
      [[1, "Bubble"], [16, "WaterPulse"], [28, "Confusion"], [34, "Surf"], [44, "Psychic"]], undefined,
      "Nada gracioso em lagos calmos; as mãos viram remos eficientes."),
    sp(56, "Mankey", ["Fighting"], [40, 80, 35, 35, 45, 70], 190,
      [[1, "Scratch"], [1, "KarateChop"], [20, "BodySlam"], [34, "AuraSphere"]],
      [{ speciesId: 57, trigger: "level", level: 28 }],
      "Sobe em árvores para calmaria — e desce rage por qualquer coisa."),
    sp(57, "Primeape", ["Fighting"], [65, 105, 60, 60, 70, 95], 75,
      [[1, "KarateChop"], [20, "BodySlam"], [36, "AuraSphere"]], undefined,
      "Persegue quem o irrita até a exaustão — da vítima, não dele."),
    sp(58, "Growlithe", ["Fire"], [55, 70, 45, 70, 50, 60], 190,
      [[1, "Ember"], [1, "Bite"], [16, "FireFang"]],
      [{ speciesId: 59, trigger: "level", level: 30 }], // pedra (Fogo)
      "Cão de guarda leal; o latido assusta intrusos a quilômetros."),
    sp(59, "Arcanine", ["Fire"], [90, 110, 80, 100, 80, 95], 75,
      [[1, "Ember"], [1, "Bite"], [16, "FireFang"], [40, "Flamethrower"], [48, "BodySlam"]], undefined,
      "Corre 10 mil quilômetros por dia; a crina de fogo impressiona."),
    sp(60, "Poliwag", ["Water"], [40, 50, 40, 40, 40, 90], 255,
      [[1, "Bubble"], [14, "WaterPulse"]],
      [{ speciesId: 61, trigger: "level", level: 25 }],
      "A espiral na barriga indica o grau de hipnese que ela exerce."),
    sp(61, "Poliwhirl", ["Water"], [65, 65, 65, 50, 50, 90], 120,
      [[1, "Bubble"], [14, "WaterPulse"], [30, "Surf"]],
      [{ speciesId: 62, trigger: "level", level: 30 }], // pedra (Água)
      "As pernas se desenvolvem; em terra, prefere andar de quatro."),
    sp(62, "Poliwrath", ["Water", "Fighting"], [90, 95, 95, 70, 90, 70], 45,
      [[1, "Bubble"], [14, "WaterPulse"], [24, "KarateChop"], [32, "Surf"], [44, "AuraSphere"]], undefined,
      "Nadador olímpico; os braços desenvolvidos cortam água e adversários."),

    // ── Psíquicos e trocas clássicas ───────────────────────────────────────
    sp(63, "Abra", ["Psychic"], [25, 20, 15, 105, 55, 90], 200,
      [[1, "Confusion"], [20, "Psybeam"], [36, "Psychic"]],
      [{ speciesId: 64, trigger: "level", level: 16 }],
      "Dorme 18 horas por dia; teletransporta ao sentir perigo."),
    sp(64, "Kadabra", ["Psychic"], [40, 35, 30, 120, 70, 105], 100,
      [[1, "Confusion"], [20, "Psybeam"], [36, "Psychic"]],
      [{ speciesId: 65, trigger: "level", level: 36 }], // troca
      "A alfa de ondas cerebrais dormente dobra colheres sem tocar."),
    sp(65, "Alakazam", ["Psychic"], [55, 50, 45, 135, 95, 120], 50,
      [[1, "Confusion"], [20, "Psybeam"], [38, "Psychic"]], undefined,
      "QI de 5000; a memória perfeita lembra de tudo desde o nascimento."),
    sp(66, "Machop", ["Fighting"], [70, 80, 50, 35, 35, 35], 180,
      [[1, "KarateChop"], [1, "Tackle"], [24, "BodySlam"], [36, "AuraSphere"]],
      [{ speciesId: 67, trigger: "level", level: 28 }],
      "Treina com pedregulhos; os músculos nunca cansam."),
    sp(67, "Machoke", ["Fighting"], [80, 100, 70, 50, 60, 45], 90,
      [[1, "KarateChop"], [24, "BodySlam"], [36, "AuraSphere"]],
      [{ speciesId: 68, trigger: "level", level: 40 }], // troca
      "O cinto de força contém os músculos que crescem sem parar."),
    sp(68, "Machamp", ["Fighting"], [90, 130, 80, 65, 85, 55], 45,
      [[1, "KarateChop"], [24, "BodySlam"], [38, "AuraSphere"], [46, "Earthquake"]], undefined,
      "Quatro braços: mil golpes em dois segundos, diz a lenda."),
    sp(69, "Bellsprout", ["Grass", "Poison"], [50, 75, 35, 70, 30, 40], 255,
      [[1, "VineWhip"], [1, "PoisonSting"], [12, "RazorLeaf"], [24, "Sludge"]],
      [{ speciesId: 70, trigger: "level", level: 21 }],
      "Planta carnívora: digere insetos com ácido e usa raízes como pés."),
    sp(70, "Weepinbell", ["Grass", "Poison"], [65, 90, 50, 85, 45, 55], 120,
      [[1, "VineWhip"], [1, "PoisonSting"], [12, "RazorLeaf"], [24, "Sludge"], [36, "SludgeBomb"]],
      [{ speciesId: 71, trigger: "level", level: 30 }], // pedra (Folha)
      "Cospe pólen que paralisa; então engole a presa inteira."),
    sp(71, "Victreebel", ["Grass", "Poison"], [80, 105, 65, 100, 70, 70], 45,
      [[1, "VineWhip"], [12, "RazorLeaf"], [24, "Sludge"], [38, "SludgeBomb"], [46, "SolarBeam"]], undefined,
      "A jarra docemente perfumada atrai presas para o líquido digestivo."),
    sp(72, "Tentacool", ["Water", "Poison"], [40, 40, 35, 50, 100, 70], 190,
      [[1, "Bubble"], [1, "PoisonSting"], [18, "WaterPulse"], [30, "Sludge"], [40, "SludgeBomb"]],
      [{ speciesId: 73, trigger: "level", level: 30 }],
      "Flutua com as marés; as guelras deixam passar só o que é água."),
    sp(73, "Tentacruel", ["Water", "Poison"], [80, 70, 65, 80, 120, 100], 60,
      [[1, "Bubble"], [1, "PoisonSting"], [18, "WaterPulse"], [30, "Sludge"], [42, "Surf"], [48, "SludgeBomb"]], undefined,
      "Os oitenta tentáculos se estendem para enredar presas inteiras."),
    sp(75, "Graveler", ["Rock", "Ground"], [55, 95, 115, 45, 45, 35], 120,
      [[1, "Tackle"], [1, "RockThrow"], [20, "RockSlide"]],
      [{ speciesId: 76, trigger: "level", level: 40 }], // troca
      "Rola montanha abaixo; os atritos arredondam as pedras do corpo."),
    sp(76, "Golem", ["Rock", "Ground"], [80, 120, 130, 55, 65, 45], 45,
      [[1, "Tackle"], [1, "RockThrow"], [20, "RockSlide"], [44, "Earthquake"]], undefined,
      "A carapaça explosiva se renova a cada ano, mais dura que antes."),
    sp(77, "Ponyta", ["Fire"], [50, 85, 55, 65, 65, 90], 190,
      [[1, "Tackle"], [1, "Ember"], [18, "FireFang"]],
      [{ speciesId: 78, trigger: "level", level: 40 }],
      "A crina de fogo nasce fraca e cresce saltitante com o treino."),
    sp(78, "Rapidash", ["Fire"], [65, 100, 70, 80, 80, 105], 60,
      [[1, "Ember"], [18, "FireFang"], [42, "Flamethrower"], [50, "BodySlam"]], undefined,
      "Galopa a 240 km/h; a chama da crina riscando o vento assusta."),
    sp(79, "Slowpoke", ["Water", "Psychic"], [90, 65, 65, 40, 40, 15], 190,
      [[1, "Tackle"], [1, "Confusion"], [20, "WaterPulse"], [36, "Surf"]],
      [{ speciesId: 80, trigger: "level", level: 37 }],
      "Esquece o que ia fazer no meio do caminho até a beira do lago."),
    sp(80, "Slowbro", ["Water", "Psychic"], [95, 75, 110, 100, 80, 30], 75,
      [[1, "Tackle"], [1, "Confusion"], [20, "WaterPulse"], [34, "Surf"], [44, "Psychic"]], undefined,
      "O Shellder na cauda virou lanche e parasita ao mesmo tempo."),
    sp(81, "Magnemite", ["Electric", "Steel"], [25, 35, 70, 95, 55, 45], 190,
      [[1, "ThunderShock"], [1, "MetalClaw"], [20, "Spark"], [36, "Thunderbolt"]],
      [{ speciesId: 82, trigger: "level", level: 30 }],
      "Flutua usando ondas de rádio; solda-se a painéis de aço."),
    sp(82, "Magneton", ["Electric", "Steel"], [50, 60, 95, 120, 70, 70], 60,
      [[1, "ThunderShock"], [1, "MetalClaw"], [20, "Spark"], [38, "Thunderbolt"], [48, "Thunder"]], undefined,
      "Três Magnemite ligados; o campo magnético atrapalha bússolas."),
    sp(83, "Farfetch'd", ["Normal", "Flying"], [52, 90, 55, 58, 62, 60], 45,
      [[1, "Scratch"], [1, "Gust"], [15, "WingAttack"], [28, "AirSlash"]], undefined,
      "Defende o alho-porro como uma espada; sem ele, fica perdido."),
    sp(84, "Doduo", ["Normal", "Flying"], [35, 85, 45, 35, 35, 75], 190,
      [[1, "Scratch"], [1, "Gust"], [14, "QuickAttack"], [22, "WingAttack"]],
      [{ speciesId: 85, trigger: "level", level: 31 }],
      "Duas cabeças conversam o dia inteiro; voa mal, corre muito."),
    sp(85, "Dodrio", ["Normal", "Flying"], [60, 110, 70, 60, 60, 110], 45,
      [[1, "Scratch"], [1, "Gust"], [14, "QuickAttack"], [24, "WingAttack"], [36, "AirSlash"]], undefined,
      "Três cabeças: uma dorme, uma vigia e uma come, em turnos."),
    sp(86, "Seel", ["Water"], [65, 45, 55, 45, 70, 45], 190,
      [[1, "Bubble"], [1, "IcyWind"], [20, "WaterPulse"]],
      [{ speciesId: 87, trigger: "level", level: 34 }],
      "O chifre afiado quebra gelo; a língua congela o que toca."),
    sp(87, "Dewgong", ["Water", "Ice"], [90, 70, 80, 70, 95, 70], 75,
      [[1, "Bubble"], [1, "IcyWind"], [20, "WaterPulse"], [32, "Surf"], [42, "IceBeam"]], undefined,
      "Corpo térmico isolado; nada em águas a oito graus negativos."),
    sp(88, "Grimer", ["Poison"], [80, 80, 50, 40, 50, 25], 190,
      [[1, "PoisonSting"], [18, "Sludge"]],
      [{ speciesId: 89, trigger: "level", level: 38 }],
      "Nasceu de lodo exposto a raios X; segue o cheiro de esgoto."),
    sp(89, "Muk", ["Poison"], [105, 105, 75, 65, 100, 50], 75,
      [[1, "PoisonSting"], [18, "Sludge"], [40, "SludgeBomb"]], undefined,
      "Tão tóxico que as plantas morrem no caminho por onde passa."),
    sp(90, "Shellder", ["Water"], [30, 65, 100, 45, 25, 40], 190,
      [[1, "Bubble"], [1, "IceShard"], [20, "WaterPulse"]],
      [{ speciesId: 91, trigger: "level", level: 30 }], // pedra (Água)
      "A concha é mais dura que diamante; só abre para atacar."),
    sp(91, "Cloyster", ["Water", "Ice"], [50, 95, 180, 85, 45, 70], 60,
      [[1, "IceShard"], [1, "IcyWind"], [20, "WaterPulse"], [36, "Surf"], [44, "IceBeam"]], undefined,
      "A casca triplo-reforçada dispara espinhos quando ameaçada."),
    sp(92, "Gastly", ["Ghost", "Poison"], [30, 35, 30, 100, 35, 80], 190,
      [[1, "Lick"], [1, "PoisonSting"], [24, "SludgeBomb"]],
      [{ speciesId: 93, trigger: "level", level: 25 }],
      "Bola de gás que atravessa paredes; envolve adversários em veneno."),
    sp(93, "Haunter", ["Ghost", "Poison"], [45, 50, 45, 115, 55, 95], 90,
      [[1, "Lick"], [1, "PoisonSting"], [24, "SludgeBomb"], [38, "ShadowBall"]],
      [{ speciesId: 94, trigger: "level", level: 40 }], // troca
      "Na escuridão total, a língua lambe o medo de quem passa."),
    sp(96, "Drowzee", ["Psychic"], [60, 48, 45, 43, 90, 42], 190,
      [[1, "Confusion"], [17, "Psybeam"], [31, "Psychic"]],
      [{ speciesId: 97, trigger: "level", level: 26 }],
      "Come sonhos; os pesados têm gosto melhor, diz a espécie."),
    sp(97, "Hypno", ["Psychic"], [85, 73, 70, 73, 115, 67], 75,
      [[1, "Confusion"], [17, "Psybeam"], [33, "Psychic"]], undefined,
      "O pêndulo balança; três segundos e o alvo já está dormindo."),
    sp(98, "Krabby", ["Water"], [30, 105, 90, 25, 25, 50], 225,
      [[1, "Bubble"], [1, "MudSlap"], [20, "BodySlam"]],
      [{ speciesId: 99, trigger: "level", level: 28 }],
      "As pinças medem dez centímetros e esmagam com força desproporcional."),
    sp(99, "Kingler", ["Water"], [55, 130, 115, 50, 50, 75], 60,
      [[1, "Bubble"], [1, "MudSlap"], [20, "BodySlam"], [40, "Surf"]], undefined,
      "A pinça gigante de dez mil cavalos-de-força abre até rochas."),
    sp(100, "Voltorb", ["Electric"], [40, 30, 50, 55, 55, 100], 190,
      [[1, "ThunderShock"], [14, "Spark"]],
      [{ speciesId: 101, trigger: "level", level: 30 }],
      "Parece uma Pokébola; quando confundido com uma, explode de raiva."),
    sp(101, "Electrode", ["Electric"], [60, 50, 70, 80, 80, 150], 60,
      [[1, "ThunderShock"], [14, "Spark"], [38, "Thunderbolt"], [50, "Thunder"]], undefined,
      "O Pokémon mais rápido do rolamento comum; explode por pouco."),
    sp(102, "Exeggcute", ["Grass", "Psychic"], [60, 40, 80, 60, 45, 40], 90,
      [[1, "Confusion"], [1, "VineWhip"], [24, "Psybeam"]],
      [{ speciesId: 103, trigger: "level", level: 30 }], // pedra (Folha)
      "Seis ovos que se agregam por telepatia; um dorme, outro pensa."),
    sp(103, "Exeggutor", ["Grass", "Psychic"], [95, 95, 85, 125, 75, 55], 45,
      [[1, "Confusion"], [1, "VineWhip"], [24, "Psybeam"], [40, "Psychic"], [46, "SolarBeam"]], undefined,
      "Cada cabeça pensa por conta própria; quando caem, viram Exeggcute."),
    sp(104, "Cubone", ["Ground"], [50, 50, 95, 40, 50, 35], 190,
      [[1, "Scratch"], [1, "MudSlap"], [18, "Dig"]],
      [{ speciesId: 105, trigger: "level", level: 28 }],
      "Usa o crânio da mãe como capacete; chora baixinho à noite."),
    sp(105, "Marowak", ["Ground"], [60, 80, 110, 50, 80, 45], 75,
      [[1, "Scratch"], [1, "MudSlap"], [18, "Dig"], [40, "Earthquake"]], undefined,
      "O osso virou arma; o grito de guerra ecoa pela planície."),
    sp(106, "Hitmonlee", ["Fighting"], [50, 120, 53, 35, 110, 87], 45,
      [[1, "KarateChop"], [20, "BodySlam"], [36, "AuraSphere"]], undefined,
      "As pernas se esticam livremente; um chute derruba construções."),
    sp(107, "Hitmonchan", ["Fighting"], [50, 105, 79, 35, 110, 76], 45,
      [[1, "KarateChop"], [20, "BodySlam"], [36, "AuraSphere"]], undefined,
      "Boxeador nato: os punhos cortam o ar como lâminas de três dedos."),
    sp(108, "Lickitung", ["Normal"], [90, 55, 75, 60, 75, 30], 45,
      [[1, "Tackle"], [1, "Lick"], [24, "BodySlam"]], undefined,
      "A língua de dois metros paralisa; a saliva derrete qualquer sujeira."),
    sp(109, "Koffing", ["Poison"], [40, 65, 95, 60, 45, 35], 190,
      [[1, "PoisonSting"], [15, "Sludge"]],
      [{ speciesId: 110, trigger: "level", level: 35 }],
      "Flutua inflado de gás; um espinho rompido e tudo explode."),
    sp(110, "Weezing", ["Poison"], [65, 90, 120, 85, 70, 60], 60,
      [[1, "PoisonSting"], [15, "Sludge"], [38, "SludgeBomb"]], undefined,
      "Dois Koffing fundidos; o gás duplo é duas vezes mais tóxico."),
    sp(111, "Rhyhorn", ["Ground", "Rock"], [80, 85, 95, 30, 30, 25], 130,
      [[1, "RockThrow"], [1, "MudSlap"], [30, "RockSlide"]],
      [{ speciesId: 112, trigger: "level", level: 42 }],
      "Cerca de blindagem: investe e não desvia de nada, nem lembra por quê."),
    sp(112, "Rhydon", ["Ground", "Rock"], [105, 130, 120, 45, 45, 40], 60,
      [[1, "RockThrow"], [1, "MudSlap"], [30, "RockSlide"], [46, "Earthquake"]], undefined,
      "A carapaça suporta erupções; o chifre derruba arranha-céus."),
    sp(113, "Chansey", ["Normal"], [250, 5, 5, 35, 105, 50], 30,
      [[1, "Tackle"], [24, "Confusion"], [38, "Psychic"]], undefined,
      "Botovos do dia; quem come um ovo ganha bondade infinita, dizem."),
    sp(114, "Tangela", ["Grass"], [65, 55, 115, 100, 40, 60], 45,
      [[1, "VineWhip"], [10, "RazorLeaf"], [32, "SolarBeam"]], undefined,
      "Os cipós crescem de volta na hora; o corpo real nunca foi visto."),
    sp(115, "Kangaskhan", ["Normal"], [105, 95, 80, 40, 80, 90], 45,
      [[1, "Tackle"], [7, "QuickAttack"], [20, "Bite"], [34, "BodySlam"]], undefined,
      "A cria vive na bolsa até os três anos; a mãe é feroz por natureza."),
    sp(116, "Horsea", ["Water"], [30, 40, 70, 70, 25, 60], 225,
      [[1, "Bubble"], [16, "WaterPulse"]],
      [{ speciesId: 117, trigger: "level", level: 32 }],
      "Cospe tinta pra fugir; enrola a cauda em corais para não boiar."),
    sp(117, "Seadra", ["Water"], [55, 65, 95, 95, 45, 85], 75,
      [[1, "Bubble"], [16, "WaterPulse"], [34, "Surf"], [46, "HydroPump"]], undefined,
      "As guelras expelam jatos de água com agulhas venenosas."),
    sp(118, "Goldeen", ["Water"], [45, 67, 60, 35, 50, 63], 225,
      [[1, "Tackle"], [1, "Bubble"], [18, "WaterPulse"]],
      [{ speciesId: 119, trigger: "level", level: 33 }],
      "O bailarino da água: nada elegante, e o chifre fura gelo duro."),
    sp(119, "Seaking", ["Water"], [80, 92, 65, 65, 80, 68], 60,
      [[1, "Tackle"], [1, "Bubble"], [18, "WaterPulse"], [38, "Surf"]], undefined,
      "Na época de acasalamento, a cauda vermelha incendeia os rios."),

    // ── Especiais e lendas de Kanto ────────────────────────────────────────
    sp(122, "Mr. Mime", ["Psychic", "Fairy"], [40, 45, 65, 100, 120, 90], 45,
      [[1, "Confusion"], [1, "FairyWind"], [26, "Psybeam"], [40, "Moonblast"]], undefined,
      "Pantomima paredes invisíveis — e elas ficam reais de verdade."),
    sp(123, "Scyther", ["Bug", "Flying"], [70, 110, 80, 55, 80, 105], 45,
      [[1, "QuickAttack"], [1, "FuryCutter"], [16, "WingAttack"], [30, "XScissor"], [40, "AirSlash"]], undefined,
      "As foices cortam troncos; movimenta-se tão rápido que parece sumir."),
    sp(124, "Jynx", ["Ice", "Psychic"], [65, 50, 35, 115, 95, 95], 45,
      [[1, "IcyWind"], [1, "Confusion"], [24, "Psybeam"], [40, "Psychic"], [44, "IceBeam"]], undefined,
      "A dança hipnótica em língua estranha arrasta quem assiste."),
    sp(125, "Electabuzz", ["Electric"], [65, 83, 57, 95, 85, 105], 45,
      [[1, "ThunderShock"], [1, "Bite"], [22, "Spark"], [40, "Thunderbolt"]], undefined,
      "Quanto maior a tempestade, mais animado fica para lutar."),
    sp(126, "Magmar", ["Fire"], [65, 95, 57, 100, 85, 93], 45,
      [[1, "Ember"], [1, "Bite"], [22, "FireFang"], [42, "Flamethrower"]], undefined,
      "Vive em crateras; o corpo queima a dois mil graus constantes."),
    sp(127, "Pinsir", ["Bug"], [65, 125, 100, 55, 70, 85], 45,
      [[1, "Scratch"], [1, "FuryCutter"], [18, "BugBite"], [34, "XScissor"], [46, "BodySlam"]], undefined,
      "As pinças esmagam com força de montanha; detesta o frio."),
    sp(128, "Tauros", ["Normal"], [75, 100, 95, 40, 70, 110], 45,
      [[1, "Tackle"], [7, "QuickAttack"], [22, "Bite"], [38, "BodySlam"]], undefined,
      "Chifradas em grupo; as três caudas chicoteiam o próprio ímpeto."),
    sp(129, "Magikarp", ["Water"], [20, 10, 55, 15, 20, 80], 255,
      [[1, "Tackle"]],
      [{ speciesId: 130, trigger: "level", level: 20 }],
      "Patético e inútil — até o dia em que não é mais."),
    sp(132, "Ditto", ["Normal"], [48, 48, 48, 48, 48, 48], 35,
      [[1, "Tackle"], [24, "BodySlam"]], undefined,
      "Transforma-se em qualquer coisa; a cara feliz nunca muda."),
    sp(134, "Vaporeon", ["Water"], [130, 65, 60, 110, 95, 65], 45,
      [[1, "Bubble"], [1, "IcyWind"], [16, "WaterPulse"], [32, "Surf"], [44, "HydroPump"]], undefined, // não ligado: pedras/escolha futuras
      "Corpo aquático: derrete na água e controla a umidade ao redor."),
    sp(135, "Jolteon", ["Electric"], [65, 65, 60, 110, 95, 130], 45,
      [[1, "ThunderShock"], [1, "QuickAttack"], [16, "Spark"], [32, "Thunderbolt"], [46, "Thunder"]], undefined, // não ligado
      "A juba vira agulhas elétricas; descarrega ao menor susto."),
    sp(136, "Flareon", ["Fire"], [65, 130, 60, 95, 110, 65], 45,
      [[1, "Ember"], [1, "QuickAttack"], [16, "Bite"], [34, "FireFang"], [48, "Flamethrower"]], undefined, // não ligado
      "A bolsa de fogo interna aquece o próprio corpo a novecentos graus."),
    sp(137, "Porygon", ["Normal"], [65, 60, 70, 85, 75, 40], 45,
      [[1, "Tackle"], [20, "Spark"], [36, "Thunderbolt"]], undefined,
      "Feito de código: existe só para estudar o movimento dimensional."),
    sp(138, "Omanyte", ["Rock", "Water"], [35, 40, 100, 90, 55, 35], 45,
      [[1, "RockThrow"], [1, "Bubble"], [20, "WaterPulse"]],
      [{ speciesId: 139, trigger: "level", level: 30 }], // pedra (cânon: nível)
      "Ressuscitado de um fóssil; espirala para dentro da concha."),
    sp(139, "Omastar", ["Rock", "Water"], [70, 60, 125, 115, 70, 55], 45,
      [[1, "RockThrow"], [1, "Bubble"], [20, "WaterPulse"], [34, "Surf"], [46, "HydroPump"]], undefined,
      "Os tentáculos prendem presas; os espinhos cruncham conchas."),
    sp(140, "Kabuto", ["Rock", "Water"], [30, 80, 90, 55, 45, 55], 45,
      [[1, "Scratch"], [1, "RockThrow"], [20, "Surf"]],
      [{ speciesId: 141, trigger: "level", level: 30 }], // pedra (cânon: nível)
      "De fossa a fossa: a carapaça endureceu há trezentos milhões de anos."),
    sp(141, "Kabutops", ["Rock", "Water"], [60, 115, 105, 65, 70, 80], 45,
      [[1, "Scratch"], [1, "RockThrow"], [20, "Surf"], [34, "RockSlide"], [46, "Earthquake"]], undefined,
      "As foices sugam fluidos das presas depois do corte seco."),
    sp(142, "Aerodactyl", ["Rock", "Flying"], [80, 105, 65, 60, 75, 130], 45,
      [[1, "Gust"], [1, "RockThrow"], [22, "WingAttack"], [36, "RockSlide"], [48, "AirSlash"]], undefined,
      "Ressuscitado do âmbar; o grito rasga o céu da montanha."),
    sp(143, "Snorlax", ["Normal"], [160, 110, 65, 65, 110, 30], 25,
      [[1, "Tackle"], [20, "BodySlam"], [36, "DarkPulse"], [46, "Earthquake"]], undefined,
      "Come oitocentos quilos por dia e dorme o resto; inamovível."),
    sp(144, "Articuno", ["Ice", "Flying"], [90, 85, 100, 95, 125, 85], 3,
      [[1, "IcyWind"], [1, "Gust"], [20, "IceBeam"], [38, "AirSlash"]], undefined,
      "O pássaro de gelo aparece a viajantes perdidos em nevascas."),
    sp(145, "Zapdos", ["Electric", "Flying"], [90, 90, 85, 125, 90, 100], 3,
      [[1, "ThunderShock"], [1, "Gust"], [20, "Thunderbolt"], [38, "AirSlash"], [50, "Thunder"]], undefined,
      "Vive entre raios; as penas cintilam quando a tempestade chega."),
    sp(146, "Moltres", ["Fire", "Flying"], [90, 100, 90, 125, 85, 90], 3,
      [[1, "Ember"], [1, "Gust"], [22, "AirSlash"], [40, "Flamethrower"]], undefined,
      "Mergulha em lava para se curar; as asas incendeiam o ar."),
    sp(147, "Dratini", ["Dragon"], [41, 64, 45, 50, 50, 50], 45,
      [[1, "Tackle"], [1, "DragonBreath"], [24, "DragonPulse"]],
      [{ speciesId: 148, trigger: "level", level: 30 }],
      "Muda de pele repetidamente; já foi tido como lendário e mítico."),
    sp(151, "Mew", ["Psychic"], [100, 100, 100, 100, 100, 100], 3,
      [[1, "Confusion"], [24, "AuraSphere"], [40, "Psychic"]], undefined,
      "Dizem que só aparece para treinadores de coração puro."),

    // ── Gen 2 que fecha linha de Kanto ─────────────────────────────────────
    sp(208, "Steelix", ["Steel", "Ground"], [75, 85, 200, 55, 65, 30], 25,
      [[1, "MetalClaw"], [1, "RockThrow"], [22, "Dig"], [42, "IronTail"], [48, "Earthquake"]], undefined,
      "Onix que viveu mil anos sob pressão; o corpo virou aço diamantino."),
  ];
}
