/**
 * Catálogo Unova (Fase 6.4-E).
 *
 * Espécies de id 494–649 (Unova), todas novas — Unova é fechada, não há evolução
 * de espécie antiga (nenhuma linha cruzada em gen1/johto/hoenn/sinnoh). Dados
 * (tipos, status-base, capture_rate, evoluções) derivados de PokeAPI/pokeapi
 * (data/v2/csv). Learnsets derivados do catálogo de golpes já existente
 * (ALL_MOVES, 133 golpes), com STAB por tipo e progressão de poder; evolução
 * por item usa os IDs de evolution-items.ts (todos já existiam).
 *
 * Proxies adotados (mesma convenção das fases anteriores, declarados aqui):
 *  - troca → nível (sem sistema de troca no jogo):
 *    Boldore (525) → Gigalith (526) nível 40,
 *    Gurdurr (533) → Conkeldurr (534) nível 40,
 *    Karrablast (588) → Escavalier (589) nível 36 (troca mútua com Shelmet no cânone),
 *    Shelmet (616) → Accelgor (617) nível 36 (troca mútua com Karrablast);
 *  - felicidade → nível (sem sistema de felicidade):
 *    Woobat (527) → Swoobat (528) nível 25,
 *    Swadloon (541) → Leavanny (542) nível 32;
 *  - Darmanitan (555) só na forma base; Zen via item 885 ignorado;
 *  - Basculin (550) só na forma base (listrado vermelho no CSV; azul é forma);
 *  - Deerling (585)/Sawsbuck (586) só na forma base (Primavera);
 *  - Tornadus (641)/Thundurus (642)/Landorus (645) só na forma Incarnate;
 *  - Kyurem (646) só na forma base; Keldeo (647) base; Meloetta (648) Aria;
 *    Genesect (649) base;
 *  - Vanillite (582)/Cubchoo (613) evoluem por nível no cânone (Pedra de Gelo
 *    não existe em Gen V); mantido o nível canônico (35 e 37).
 *  - Sem evolução: Victini (494), Audino (531), Throh (538)/Sawk (539),
 *    Basculin (550), Maractus (556), Sigilyph (561), Emolga (587), Alomomola (594),
 *    Cryogonal (615), Stunfisk (618), Druddigon (621), Bouffalant (626),
 *    Heatmor (631), Durant (632) e lendários/míticos 638–649.
 *
 * Itens de evolução que Unova usa já existem no jogo (nenhuma migration):
 *  - Pansage (511) → Simisage (512) Pedra de Folha (leafStone),
 *  - Pansear (513) → Simisear (514) Pedra de Fogo (fireStone),
 *  - Panpour (515) → Simipour (516) Pedra d'Água (waterStone),
 *  - Munna (517) → Musharna (518) Pedra da Lua (moonStone),
 *  - Cottonee (546) → Whimsicott (547) Pedra do Sol (sunStone),
 *  - Petilil (548) → Lilligant (549) Pedra do Sol (sunStone),
 *  - Minccino (572) → Cinccino (573) Pedra Brilhante (shinyStone),
 *  - Eelektrik (603) → Eelektross (604) Pedra de Trovão (thunderStone),
 *  - Lampent (608) → Chandelure (609) Pedra do Entardecer (duskStone).
 *
 * Sprites: Gen V animado (black-white/animated) cobre até o id 649 — é o teto
 * do CDN atual, por isso a Pokédex para aqui (6.4-F é decisão de arte/produto).
 */

import { EVOLUTION_ITEM_IDS } from "./evolution-items";
import type { AllMoves, EvolvesTo, PokemonSpeciesData } from "./pokedex";

type MoveKey = keyof AllMoves;
type Bases = [number, number, number, number, number, number];

const SPRITE_BASE =
  "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated";

function spriteUrl(id: number, variant?: "back" | "shiny"): string {
  return variant ? `${SPRITE_BASE}/${variant}/${id}.gif` : `${SPRITE_BASE}/${id}.gif`;
}

/** Espécies novas de Unova, em ordem de id. Chamado por pokedex.ts com ALL_MOVES. */
export function unovaRest(M: AllMoves): PokemonSpeciesData[] {
  const sp = (
    id: number, name: string, types: [string] | [string, string], bases: Bases,
    catchRate: number, moves: ReadonlyArray<readonly [number, MoveKey]>,
    evolve: ReadonlyArray<EvolvesTo> | undefined, description: string
  ): PokemonSpeciesData => ({
    id, name, types, baseHp: bases[0], baseAtk: bases[1], baseDef: bases[2],
    baseSpAtk: bases[3], baseSpDef: bases[4], baseSpd: bases[5], catchRate,
    learnset: moves.map(([level, key]) => ({ level, move: M[key] })),
    evolvesTo: evolve?.map((e) => ({ ...e })),
    frontSprite: spriteUrl(id), backSprite: spriteUrl(id, "back"),
    shinyFrontSprite: spriteUrl(id, "shiny"), description,
  });

  return [
    sp(494, "Victini", ["Psychic", "Fire"], [100, 100, 100, 100, 100, 100], 3,
      [[1, "Confusion"], [7, "FireSpin"], [14, "FlameWheel"], [22, "Psybeam"], [32, "ZenHeadbutt"], [42, "Psychic"], [52, "FutureSight"], [62, "Overheat"], [70, "FireBlast"], [80, "Flamethrower"]],
      undefined,
      "Pokémon Mítico da Vitória; dizem que quem o possui nunca perde."),
    sp(495, "Snivy", ["Grass"], [45, 45, 55, 45, 55, 63], 45,
      [[1, "Absorb"], [7, "MegaDrain"], [14, "RazorLeaf"], [22, "PetalDance"], [32, "SeedBomb"], [42, "LeafBlade"], [52, "SolarBeam"], [62, "EnergyBall"]],
      [{ speciesId: 496, trigger: "level", level: 17 }],
      "Inicial de Planta de Unova; a cauda fotossintética murcha quando tem sede."),
    sp(496, "Servine", ["Grass"], [60, 60, 75, 60, 75, 83], 45,
      [[1, "Absorb"], [7, "MegaDrain"], [14, "RazorLeaf"], [22, "PetalDance"], [32, "SeedBomb"], [42, "LeafBlade"], [52, "SolarBeam"], [62, "EnergyBall"]],
      [{ speciesId: 497, trigger: "level", level: 36 }],
      "Evolução de Snivy; desliza pela selva com elegância e rapidez."),
    sp(497, "Serperior", ["Grass"], [75, 75, 95, 75, 95, 113], 45,
      [[1, "Absorb"], [7, "MegaDrain"], [14, "RazorLeaf"], [22, "PetalDance"], [32, "SeedBomb"], [42, "LeafBlade"], [52, "SolarBeam"], [62, "EnergyBall"], [70, "HyperBeam"], [80, "SkullBash"]],
      undefined,
      "Forma final de Snivy; impõe respeito com olhar regal e orgulhoso."),
    sp(498, "Tepig", ["Fire"], [65, 63, 45, 45, 45, 45], 45,
      [[1, "Ember"], [7, "FireSpin"], [14, "FlameWheel"], [22, "FireFang"], [32, "FirePunch"], [42, "Flamethrower"], [52, "Overheat"], [62, "FireBlast"]],
      [{ speciesId: 499, trigger: "level", level: 17 }],
      "Inicial de Fogo de Unova; a chama no focinho cresce quando está animado."),
    sp(499, "Pignite", ["Fire", "Fighting"], [90, 93, 55, 70, 55, 55], 45,
      [[1, "Ember"], [7, "LowKick"], [14, "FlameWheel"], [22, "FireFang"], [32, "FirePunch"], [42, "Flamethrower"], [52, "Overheat"], [62, "FireBlast"]],
      [{ speciesId: 500, trigger: "level", level: 36 }],
      "Evolução de Tepig; luta com corpo a corpo quente e determinado."),
    sp(500, "Emboar", ["Fire", "Fighting"], [110, 123, 65, 100, 65, 65], 45,
      [[1, "Ember"], [7, "LowKick"], [14, "FlameWheel"], [22, "FireFang"], [32, "FirePunch"], [42, "Flamethrower"], [52, "Overheat"], [62, "FireBlast"], [70, "DynamicPunch"], [80, "CrossChop"]],
      undefined,
      "Forma final de Tepig; barba de fogo e socos que quebram muralhas."),
    sp(501, "Oshawott", ["Water"], [55, 55, 45, 63, 45, 45], 45,
      [[1, "Bubble"], [7, "WaterGun"], [14, "WaterPulse"], [22, "BubbleBeam"], [32, "Waterfall"], [42, "Surf"], [52, "HydroPump"], [62, "Crabhammer"]],
      [{ speciesId: 502, trigger: "level", level: 17 }],
      "Inicial de Água de Unova; o apêndice em forma de concha vira arma."),
    sp(502, "Dewott", ["Water"], [75, 75, 60, 83, 60, 60], 45,
      [[1, "Bubble"], [7, "WaterGun"], [14, "WaterPulse"], [22, "BubbleBeam"], [32, "Waterfall"], [42, "Surf"], [52, "HydroPump"], [62, "Crabhammer"]],
      [{ speciesId: 503, trigger: "level", level: 36 }],
      "Evolução de Oshawott; treina com disciplina usando a concha dupla."),
    sp(503, "Samurott", ["Water"], [95, 100, 85, 108, 70, 70], 45,
      [[1, "Bubble"], [7, "WaterGun"], [14, "WaterPulse"], [22, "BubbleBeam"], [32, "Waterfall"], [42, "Surf"], [52, "HydroPump"], [62, "Crabhammer"], [70, "HyperBeam"], [80, "SkullBash"]],
      undefined,
      "Forma final de Oshawott; armadura de conchas e lâminas de água."),
    sp(504, "Patrat", ["Normal"], [45, 55, 39, 35, 39, 42], 255,
      [[1, "Scratch"], [7, "PayDay"], [14, "Swift"], [22, "Headbutt"], [32, "ExtremeSpeed"], [42, "SkullBash"], [52, "HyperBeam"], [62, "TakeDown"]],
      [{ speciesId: 505, trigger: "level", level: 20 }],
      "Patrat é um Pokémon de Unova do tipo Normal, conhecido como Scout — comum nas rotas e cidades, adaptável e curioso."),
    sp(505, "Watchog", ["Normal"], [60, 85, 69, 60, 69, 77], 255,
      [[1, "Scratch"], [7, "PayDay"], [14, "Swift"], [22, "Headbutt"], [32, "ExtremeSpeed"], [42, "SkullBash"], [52, "HyperBeam"], [62, "TakeDown"], [70, "HyperFang"], [80, "Slash"]],
      undefined,
      "Watchog é um Pokémon de Unova do tipo Normal, conhecido como Lookout — comum nas rotas e cidades, adaptável e curioso."),
    sp(506, "Lillipup", ["Normal"], [45, 60, 45, 25, 45, 55], 255,
      [[1, "Scratch"], [7, "PayDay"], [14, "Swift"], [22, "Headbutt"], [32, "ExtremeSpeed"], [42, "SkullBash"], [52, "HyperBeam"], [62, "TakeDown"]],
      [{ speciesId: 507, trigger: "level", level: 16 }],
      "Lillipup é um Pokémon de Unova do tipo Normal, conhecido como Puppy — comum nas rotas e cidades, adaptável e curioso."),
    sp(507, "Herdier", ["Normal"], [65, 80, 65, 35, 65, 60], 120,
      [[1, "Scratch"], [7, "PayDay"], [14, "Swift"], [22, "Headbutt"], [32, "ExtremeSpeed"], [42, "SkullBash"], [52, "HyperBeam"], [62, "TakeDown"]],
      [{ speciesId: 508, trigger: "level", level: 32 }],
      "Herdier é um Pokémon de Unova do tipo Normal, conhecido como Loyal Dog — comum nas rotas e cidades, adaptável e curioso."),
    sp(508, "Stoutland", ["Normal"], [85, 110, 90, 45, 90, 80], 45,
      [[1, "Scratch"], [7, "PayDay"], [14, "Swift"], [22, "Headbutt"], [32, "ExtremeSpeed"], [42, "SkullBash"], [52, "HyperBeam"], [62, "TakeDown"], [70, "HyperFang"], [80, "Slash"]],
      undefined,
      "Stoutland é um Pokémon de Unova do tipo Normal, conhecido como Big-Hearted — comum nas rotas e cidades, adaptável e curioso."),
    sp(509, "Purrloin", ["Dark"], [41, 50, 37, 50, 37, 66], 255,
      [[1, "Pursuit"], [7, "PayDay"], [14, "FeintAttack"], [22, "NightSlash"], [32, "Crunch"], [42, "DarkPulse"], [52, "HyperBeam"], [62, "SkullBash"]],
      [{ speciesId: 510, trigger: "level", level: 20 }],
      "Purrloin é um Pokémon de Unova do tipo Sombrio, conhecido como Devious — age à noite, astuto e desconfiado."),
    sp(510, "Liepard", ["Dark"], [64, 88, 50, 88, 50, 106], 90,
      [[1, "Pursuit"], [7, "PayDay"], [14, "FeintAttack"], [22, "NightSlash"], [32, "Crunch"], [42, "DarkPulse"], [52, "HyperBeam"], [62, "SkullBash"], [70, "Crunch"], [80, "ExtremeSpeed"]],
      undefined,
      "Liepard é um Pokémon de Unova do tipo Sombrio, conhecido como Cruel — age à noite, astuto e desconfiado."),
    sp(511, "Pansage", ["Grass"], [50, 53, 48, 53, 48, 64], 190,
      [[1, "Absorb"], [7, "MegaDrain"], [14, "RazorLeaf"], [22, "PetalDance"], [32, "SeedBomb"], [42, "LeafBlade"], [52, "SolarBeam"], [62, "EnergyBall"]],
      [{ speciesId: 512, trigger: "item", itemId: EVOLUTION_ITEM_IDS.leafStone }],
      "Pansage é um Pokémon de Unova do tipo Planta, conhecido como Grass Monkey — vive em florestas e campos, absorvendo luz solar."),
    sp(512, "Simisage", ["Grass"], [75, 98, 63, 98, 63, 101], 75,
      [[1, "Absorb"], [7, "MegaDrain"], [14, "RazorLeaf"], [22, "PetalDance"], [32, "SeedBomb"], [42, "LeafBlade"], [52, "SolarBeam"], [62, "EnergyBall"], [70, "HyperBeam"], [80, "SkullBash"]],
      undefined,
      "Simisage é um Pokémon de Unova do tipo Planta, conhecido como Thorn Monkey — vive em florestas e campos, absorvendo luz solar."),
    sp(513, "Pansear", ["Fire"], [50, 53, 48, 53, 48, 64], 190,
      [[1, "Ember"], [7, "FireSpin"], [14, "FlameWheel"], [22, "FireFang"], [32, "FirePunch"], [42, "Flamethrower"], [52, "Overheat"], [62, "FireBlast"]],
      [{ speciesId: 514, trigger: "item", itemId: EVOLUTION_ITEM_IDS.fireStone }],
      "Pansear é um Pokémon de Unova do tipo Fogo, conhecido como High Temp — prefere áreas vulcânicas e desertos quentes."),
    sp(514, "Simisear", ["Fire"], [75, 98, 63, 98, 63, 101], 75,
      [[1, "Ember"], [7, "FireSpin"], [14, "FlameWheel"], [22, "FireFang"], [32, "FirePunch"], [42, "Flamethrower"], [52, "Overheat"], [62, "FireBlast"], [70, "HyperBeam"], [80, "SkullBash"]],
      undefined,
      "Simisear é um Pokémon de Unova do tipo Fogo, conhecido como Ember — prefere áreas vulcânicas e desertos quentes."),
    sp(515, "Panpour", ["Water"], [50, 53, 48, 53, 48, 64], 190,
      [[1, "Bubble"], [7, "WaterGun"], [14, "WaterPulse"], [22, "BubbleBeam"], [32, "Waterfall"], [42, "Surf"], [52, "HydroPump"], [62, "Crabhammer"]],
      [{ speciesId: 516, trigger: "item", itemId: EVOLUTION_ITEM_IDS.waterStone }],
      "Panpour é um Pokémon de Unova do tipo Água, conhecido como Spray — habita rios, lagos e o litoral de Unova."),
    sp(516, "Simipour", ["Water"], [75, 98, 63, 98, 63, 101], 75,
      [[1, "Bubble"], [7, "WaterGun"], [14, "WaterPulse"], [22, "BubbleBeam"], [32, "Waterfall"], [42, "Surf"], [52, "HydroPump"], [62, "Crabhammer"], [70, "HyperBeam"], [80, "SkullBash"]],
      undefined,
      "Simipour é um Pokémon de Unova do tipo Água, conhecido como Geyser — habita rios, lagos e o litoral de Unova."),
    sp(517, "Munna", ["Psychic"], [76, 25, 45, 67, 55, 24], 190,
      [[1, "Confusion"], [7, "PayDay"], [14, "Swift"], [22, "Psybeam"], [32, "ZenHeadbutt"], [42, "Psychic"], [52, "FutureSight"], [62, "HyperBeam"]],
      [{ speciesId: 518, trigger: "item", itemId: EVOLUTION_ITEM_IDS.moonStone }],
      "Munna é um Pokémon de Unova do tipo Psíquico, conhecido como Dream Eater — usa poderes mentais para se comunicar e lutar."),
    sp(518, "Musharna", ["Psychic"], [116, 55, 85, 107, 95, 29], 75,
      [[1, "Confusion"], [7, "PayDay"], [14, "Swift"], [22, "Psybeam"], [32, "ZenHeadbutt"], [42, "Psychic"], [52, "FutureSight"], [62, "HyperBeam"], [70, "SkullBash"], [80, "TakeDown"]],
      undefined,
      "Musharna é um Pokémon de Unova do tipo Psíquico, conhecido como Drowsing — usa poderes mentais para se comunicar e lutar."),
    sp(519, "Pidove", ["Normal", "Flying"], [50, 55, 50, 36, 30, 43], 255,
      [[1, "Scratch"], [7, "Peck"], [14, "Swift"], [22, "Headbutt"], [32, "ExtremeSpeed"], [42, "SkullBash"], [52, "HyperBeam"], [62, "TakeDown"]],
      [{ speciesId: 520, trigger: "level", level: 21 }],
      "Pidove é um Pokémon de Unova do tipo Normal/Voador, conhecido como Tiny Pigeon — comum nas rotas e cidades, adaptável e curioso."),
    sp(520, "Tranquill", ["Normal", "Flying"], [62, 77, 62, 50, 42, 65], 120,
      [[1, "Scratch"], [7, "Peck"], [14, "Swift"], [22, "Headbutt"], [32, "ExtremeSpeed"], [42, "SkullBash"], [52, "HyperBeam"], [62, "TakeDown"]],
      [{ speciesId: 521, trigger: "level", level: 32 }],
      "Tranquill é um Pokémon de Unova do tipo Normal/Voador, conhecido como Wild Pigeon — comum nas rotas e cidades, adaptável e curioso."),
    sp(521, "Unfezant", ["Normal", "Flying"], [80, 115, 80, 65, 55, 93], 45,
      [[1, "Scratch"], [7, "Peck"], [14, "Swift"], [22, "Headbutt"], [32, "ExtremeSpeed"], [42, "SkullBash"], [52, "HyperBeam"], [62, "TakeDown"], [70, "HyperFang"], [80, "Slash"]],
      undefined,
      "Unfezant é um Pokémon de Unova do tipo Normal/Voador, conhecido como Proud — comum nas rotas e cidades, adaptável e curioso."),
    sp(522, "Blitzle", ["Electric"], [45, 60, 32, 50, 32, 76], 190,
      [[1, "ThunderShock"], [7, "PayDay"], [14, "ShockWave"], [22, "Spark"], [32, "Discharge"], [42, "Thunderbolt"], [52, "Thunder"], [62, "WildCharge"]],
      [{ speciesId: 523, trigger: "level", level: 27 }],
      "Blitzle é um Pokémon de Unova do tipo Elétrico, conhecido como Electrified — acumula energia em tempestades e usinas."),
    sp(523, "Zebstrika", ["Electric"], [75, 100, 63, 80, 63, 116], 75,
      [[1, "ThunderShock"], [7, "PayDay"], [14, "ShockWave"], [22, "Spark"], [32, "Discharge"], [42, "Thunderbolt"], [52, "Thunder"], [62, "WildCharge"], [70, "ThunderPunch"], [80, "HyperBeam"]],
      undefined,
      "Zebstrika é um Pokémon de Unova do tipo Elétrico, conhecido como Thunderbolt — acumula energia em tempestades e usinas."),
    sp(524, "Roggenrola", ["Rock"], [55, 75, 85, 25, 25, 15], 255,
      [[1, "RockPolish"], [7, "RockTomb"], [14, "AncientPower"], [22, "RockThrow"], [32, "RockSlide"], [42, "SkullBash"], [52, "StoneEdge"], [62, "HyperBeam"]],
      [{ speciesId: 525, trigger: "level", level: 25 }],
      "Roggenrola é um Pokémon de Unova do tipo Pedra, conhecido como Mantle — corpo resistente, encontrado em montanhas."),
    sp(525, "Boldore", ["Rock"], [70, 105, 105, 50, 40, 20], 120,
      [[1, "RockPolish"], [7, "RockTomb"], [14, "AncientPower"], [22, "RockThrow"], [32, "RockSlide"], [42, "SkullBash"], [52, "StoneEdge"], [62, "HyperBeam"]],
      [{ speciesId: 526, trigger: "level", level: 40 }],
      "Boldore é um Pokémon de Unova do tipo Pedra, conhecido como Ore — corpo resistente, encontrado em montanhas."),
    sp(526, "Gigalith", ["Rock"], [85, 135, 130, 60, 80, 25], 45,
      [[1, "RockPolish"], [7, "RockTomb"], [14, "AncientPower"], [22, "RockThrow"], [32, "RockSlide"], [42, "SkullBash"], [52, "StoneEdge"], [62, "HyperBeam"], [70, "TakeDown"], [80, "ExtremeSpeed"]],
      undefined,
      "Gigalith é um Pokémon de Unova do tipo Pedra, conhecido como Compressed — corpo resistente, encontrado em montanhas."),
    sp(527, "Woobat", ["Psychic", "Flying"], [65, 45, 43, 55, 43, 72], 190,
      [[1, "Confusion"], [7, "Peck"], [14, "AerialAce"], [22, "Psybeam"], [32, "ZenHeadbutt"], [42, "Psychic"], [52, "FutureSight"], [62, "Bounce"]],
      [{ speciesId: 528, trigger: "level", level: 25 }],
      "Woobat é um Pokémon de Unova do tipo Psíquico/Voador, conhecido como Bat — usa poderes mentais para se comunicar e lutar."),
    sp(528, "Swoobat", ["Psychic", "Flying"], [67, 57, 55, 77, 55, 114], 45,
      [[1, "Confusion"], [7, "Peck"], [14, "AerialAce"], [22, "Psybeam"], [32, "ZenHeadbutt"], [42, "Psychic"], [52, "FutureSight"], [62, "Bounce"], [70, "Fly"], [80, "DrillPeck"]],
      undefined,
      "Swoobat é um Pokémon de Unova do tipo Psíquico/Voador, conhecido como Courting — usa poderes mentais para se comunicar e lutar."),
    sp(529, "Drilbur", ["Ground"], [60, 85, 40, 30, 45, 68], 120,
      [[1, "MudSlap"], [7, "PayDay"], [14, "MudShot"], [22, "BoneClub"], [32, "Dig"], [42, "EarthPower"], [52, "Earthquake"], [62, "Bonemerang"]],
      [{ speciesId: 530, trigger: "level", level: 31 }],
      "Drilbur é um Pokémon de Unova do tipo Terrestre, conhecido como Mole — cava túneis e vive em cavernas e desertos."),
    sp(530, "Excadrill", ["Ground", "Steel"], [110, 135, 60, 50, 65, 88], 60,
      [[1, "MudSlap"], [7, "MetalClaw"], [14, "MudShot"], [22, "BoneClub"], [32, "Dig"], [42, "EarthPower"], [52, "Earthquake"], [62, "Bonemerang"], [70, "IronTail"], [80, "FlashCannon"]],
      undefined,
      "Excadrill é um Pokémon de Unova do tipo Terrestre/Aço, conhecido como Subterrene — cava túneis e vive em cavernas e desertos."),
    sp(531, "Audino", ["Normal"], [103, 60, 86, 60, 86, 50], 255,
      [[1, "Scratch"], [7, "PayDay"], [14, "Swift"], [22, "Headbutt"], [32, "ExtremeSpeed"], [42, "SkullBash"], [52, "HyperBeam"], [62, "TakeDown"], [70, "HyperFang"], [80, "Slash"]],
      undefined,
      "Audino é um Pokémon de Unova do tipo Normal, conhecido como Hearing — comum nas rotas e cidades, adaptável e curioso."),
    sp(532, "Timburr", ["Fighting"], [75, 80, 55, 25, 35, 35], 180,
      [[1, "MachPunch"], [7, "LowKick"], [14, "RollingKick"], [22, "VitalThrow"], [32, "Submission"], [42, "SkyUppercut"], [52, "DynamicPunch"], [62, "CrossChop"]],
      [{ speciesId: 533, trigger: "level", level: 25 }],
      "Timburr é um Pokémon de Unova do tipo Lutador, conhecido como Muscular — treina artes marciais nas montanhas."),
    sp(533, "Gurdurr", ["Fighting"], [85, 105, 85, 40, 50, 40], 90,
      [[1, "MachPunch"], [7, "LowKick"], [14, "RollingKick"], [22, "VitalThrow"], [32, "Submission"], [42, "SkyUppercut"], [52, "DynamicPunch"], [62, "CrossChop"]],
      [{ speciesId: 534, trigger: "level", level: 40 }],
      "Gurdurr é um Pokémon de Unova do tipo Lutador, conhecido como Muscular — treina artes marciais nas montanhas."),
    sp(534, "Conkeldurr", ["Fighting"], [105, 140, 95, 55, 65, 45], 45,
      [[1, "MachPunch"], [7, "LowKick"], [14, "RollingKick"], [22, "VitalThrow"], [32, "Submission"], [42, "SkyUppercut"], [52, "DynamicPunch"], [62, "CrossChop"], [70, "HighJumpKick"], [80, "AuraSphere"]],
      undefined,
      "Conkeldurr é um Pokémon de Unova do tipo Lutador, conhecido como Muscular — treina artes marciais nas montanhas."),
    sp(535, "Tympole", ["Water"], [50, 50, 40, 50, 40, 64], 255,
      [[1, "Bubble"], [7, "WaterGun"], [14, "WaterPulse"], [22, "BubbleBeam"], [32, "Waterfall"], [42, "Surf"], [52, "HydroPump"], [62, "Crabhammer"]],
      [{ speciesId: 536, trigger: "level", level: 25 }],
      "Tympole é um Pokémon de Unova do tipo Água, conhecido como Tadpole — habita rios, lagos e o litoral de Unova."),
    sp(536, "Palpitoad", ["Water", "Ground"], [75, 65, 55, 65, 55, 69], 120,
      [[1, "Bubble"], [7, "MudSlap"], [14, "WaterPulse"], [22, "BubbleBeam"], [32, "Waterfall"], [42, "Surf"], [52, "HydroPump"], [62, "Crabhammer"]],
      [{ speciesId: 537, trigger: "level", level: 36 }],
      "Palpitoad é um Pokémon de Unova do tipo Água/Terrestre, conhecido como Vibration — habita rios, lagos e o litoral de Unova."),
    sp(537, "Seismitoad", ["Water", "Ground"], [105, 95, 75, 85, 75, 74], 45,
      [[1, "Bubble"], [7, "MudSlap"], [14, "WaterPulse"], [22, "BubbleBeam"], [32, "Waterfall"], [42, "Surf"], [52, "HydroPump"], [62, "Crabhammer"], [70, "Earthquake"], [80, "EarthPower"]],
      undefined,
      "Seismitoad é um Pokémon de Unova do tipo Água/Terrestre, conhecido como Vibration — habita rios, lagos e o litoral de Unova."),
    sp(538, "Throh", ["Fighting"], [120, 100, 85, 30, 85, 45], 45,
      [[1, "MachPunch"], [7, "LowKick"], [14, "RollingKick"], [22, "VitalThrow"], [32, "Submission"], [42, "SkyUppercut"], [52, "DynamicPunch"], [62, "CrossChop"], [70, "HighJumpKick"], [80, "AuraSphere"]],
      undefined,
      "Throh é um Pokémon de Unova do tipo Lutador, conhecido como Judo — treina artes marciais nas montanhas."),
    sp(539, "Sawk", ["Fighting"], [75, 125, 75, 30, 75, 85], 45,
      [[1, "MachPunch"], [7, "LowKick"], [14, "RollingKick"], [22, "VitalThrow"], [32, "Submission"], [42, "SkyUppercut"], [52, "DynamicPunch"], [62, "CrossChop"], [70, "HighJumpKick"], [80, "AuraSphere"]],
      undefined,
      "Sawk é um Pokémon de Unova do tipo Lutador, conhecido como Karate — treina artes marciais nas montanhas."),
    sp(540, "Sewaddle", ["Bug", "Grass"], [45, 53, 70, 40, 60, 42], 255,
      [[1, "LeechLife"], [7, "MegaDrain"], [14, "SilverWind"], [22, "BugBite"], [32, "XScissor"], [42, "SignalBeam"], [52, "SolarBeam"], [62, "LeafBlade"]],
      [{ speciesId: 541, trigger: "level", level: 20 }],
      "Sewaddle é um Pokémon de Unova do tipo Inseto/Planta, conhecido como Sewing — pequeno e ágil, vive em matas e jardins."),
    sp(541, "Swadloon", ["Bug", "Grass"], [55, 63, 90, 50, 80, 42], 120,
      [[1, "LeechLife"], [7, "MegaDrain"], [14, "SilverWind"], [22, "BugBite"], [32, "XScissor"], [42, "SignalBeam"], [52, "SolarBeam"], [62, "LeafBlade"]],
      [{ speciesId: 542, trigger: "level", level: 32 }],
      "Swadloon é um Pokémon de Unova do tipo Inseto/Planta, conhecido como Leaf-Wrapped — pequeno e ágil, vive em matas e jardins."),
    sp(542, "Leavanny", ["Bug", "Grass"], [75, 103, 80, 70, 80, 92], 45,
      [[1, "LeechLife"], [7, "MegaDrain"], [14, "SilverWind"], [22, "BugBite"], [32, "XScissor"], [42, "SignalBeam"], [52, "SolarBeam"], [62, "LeafBlade"], [70, "XScissor"], [80, "SeedBomb"]],
      undefined,
      "Leavanny é um Pokémon de Unova do tipo Inseto/Planta, conhecido como Nurturing — pequeno e ágil, vive em matas e jardins."),
    sp(543, "Venipede", ["Bug", "Poison"], [30, 45, 59, 30, 39, 57], 255,
      [[1, "LeechLife"], [7, "Acid"], [14, "SilverWind"], [22, "BugBite"], [32, "XScissor"], [42, "SignalBeam"], [52, "SludgeBomb"], [62, "PoisonJab"]],
      [{ speciesId: 544, trigger: "level", level: 22 }],
      "Venipede é um Pokémon de Unova do tipo Inseto/Venenoso, conhecido como Centipede — pequeno e ágil, vive em matas e jardins."),
    sp(544, "Whirlipede", ["Bug", "Poison"], [40, 55, 99, 40, 79, 47], 120,
      [[1, "LeechLife"], [7, "Acid"], [14, "SilverWind"], [22, "BugBite"], [32, "XScissor"], [42, "SignalBeam"], [52, "SludgeBomb"], [62, "PoisonJab"]],
      [{ speciesId: 545, trigger: "level", level: 30 }],
      "Whirlipede é um Pokémon de Unova do tipo Inseto/Venenoso, conhecido como Curlipede — pequeno e ágil, vive em matas e jardins."),
    sp(545, "Scolipede", ["Bug", "Poison"], [60, 100, 89, 55, 69, 112], 45,
      [[1, "LeechLife"], [7, "Acid"], [14, "SilverWind"], [22, "BugBite"], [32, "XScissor"], [42, "SignalBeam"], [52, "SludgeBomb"], [62, "PoisonJab"], [70, "XScissor"], [80, "SkullBash"]],
      undefined,
      "Scolipede é um Pokémon de Unova do tipo Inseto/Venenoso, conhecido como Megapede — pequeno e ágil, vive em matas e jardins."),
    sp(546, "Cottonee", ["Grass", "Fairy"], [40, 27, 60, 37, 50, 66], 190,
      [[1, "Absorb"], [7, "DrainingKiss"], [14, "MegaDrain"], [22, "PetalDance"], [32, "SeedBomb"], [42, "LeafBlade"], [52, "SolarBeam"], [62, "EnergyBall"]],
      [{ speciesId: 547, trigger: "item", itemId: EVOLUTION_ITEM_IDS.sunStone }],
      "Cottonee é um Pokémon de Unova do tipo Planta/Fada, conhecido como Cotton Puff — vive em florestas e campos, absorvendo luz solar."),
    sp(547, "Whimsicott", ["Grass", "Fairy"], [60, 67, 85, 77, 75, 116], 75,
      [[1, "Absorb"], [7, "DrainingKiss"], [14, "MegaDrain"], [22, "PetalDance"], [32, "SeedBomb"], [42, "LeafBlade"], [52, "SolarBeam"], [62, "EnergyBall"], [70, "Moonblast"], [80, "PlayRough"]],
      undefined,
      "Whimsicott é um Pokémon de Unova do tipo Planta/Fada, conhecido como Windveiled — vive em florestas e campos, absorvendo luz solar."),
    sp(548, "Petilil", ["Grass"], [45, 35, 50, 70, 50, 30], 190,
      [[1, "Absorb"], [7, "MegaDrain"], [14, "RazorLeaf"], [22, "PetalDance"], [32, "SeedBomb"], [42, "LeafBlade"], [52, "SolarBeam"], [62, "EnergyBall"]],
      [{ speciesId: 549, trigger: "item", itemId: EVOLUTION_ITEM_IDS.sunStone }],
      "Petilil é um Pokémon de Unova do tipo Planta, conhecido como Bulb — vive em florestas e campos, absorvendo luz solar."),
    sp(549, "Lilligant", ["Grass"], [70, 60, 75, 110, 75, 90], 75,
      [[1, "Absorb"], [7, "MegaDrain"], [14, "RazorLeaf"], [22, "PetalDance"], [32, "SeedBomb"], [42, "LeafBlade"], [52, "SolarBeam"], [62, "EnergyBall"], [70, "HyperBeam"], [80, "SkullBash"]],
      undefined,
      "Lilligant é um Pokémon de Unova do tipo Planta, conhecido como Flowering — vive em florestas e campos, absorvendo luz solar."),
    sp(550, "Basculin", ["Water"], [70, 92, 65, 80, 55, 98], 25,
      [[1, "Bubble"], [7, "WaterGun"], [14, "WaterPulse"], [22, "BubbleBeam"], [32, "Waterfall"], [42, "Surf"], [52, "HydroPump"], [62, "Crabhammer"], [70, "HyperBeam"], [80, "SkullBash"]],
      undefined,
      "Basculin é um Pokémon de Unova do tipo Água, conhecido como Hostile — habita rios, lagos e o litoral de Unova."),
    sp(551, "Sandile", ["Ground", "Dark"], [50, 72, 35, 35, 35, 65], 180,
      [[1, "MudSlap"], [7, "Pursuit"], [14, "MudShot"], [22, "BoneClub"], [32, "Dig"], [42, "EarthPower"], [52, "Earthquake"], [62, "Bonemerang"]],
      [{ speciesId: 552, trigger: "level", level: 29 }],
      "Sandile é um Pokémon de Unova do tipo Terrestre/Sombrio, conhecido como Desert Croc — cava túneis e vive em cavernas e desertos."),
    sp(552, "Krokorok", ["Ground", "Dark"], [60, 82, 45, 45, 45, 74], 90,
      [[1, "MudSlap"], [7, "Pursuit"], [14, "MudShot"], [22, "BoneClub"], [32, "Dig"], [42, "EarthPower"], [52, "Earthquake"], [62, "Bonemerang"]],
      [{ speciesId: 553, trigger: "level", level: 40 }],
      "Krokorok é um Pokémon de Unova do tipo Terrestre/Sombrio, conhecido como Desert Croc — cava túneis e vive em cavernas e desertos."),
    sp(553, "Krookodile", ["Ground", "Dark"], [95, 117, 80, 65, 70, 92], 45,
      [[1, "MudSlap"], [7, "Pursuit"], [14, "MudShot"], [22, "BoneClub"], [32, "Dig"], [42, "EarthPower"], [52, "Earthquake"], [62, "Bonemerang"], [70, "Crunch"], [80, "DarkPulse"]],
      undefined,
      "Krookodile é um Pokémon de Unova do tipo Terrestre/Sombrio, conhecido como Intimidation — cava túneis e vive em cavernas e desertos."),
    sp(554, "Darumaka", ["Fire"], [70, 90, 45, 15, 45, 50], 120,
      [[1, "Ember"], [7, "FireSpin"], [14, "FlameWheel"], [22, "FireFang"], [32, "FirePunch"], [42, "Flamethrower"], [52, "Overheat"], [62, "FireBlast"]],
      [{ speciesId: 555, trigger: "level", level: 35 }],
      "Darumaka é um Pokémon de Unova do tipo Fogo, conhecido como Zen Charm — prefere áreas vulcânicas e desertos quentes."),
    sp(555, "Darmanitan", ["Fire"], [105, 140, 55, 30, 55, 95], 60,
      [[1, "Ember"], [7, "FireSpin"], [14, "FlameWheel"], [22, "FireFang"], [32, "FirePunch"], [42, "Flamethrower"], [52, "Overheat"], [62, "FireBlast"], [70, "HyperBeam"], [80, "SkullBash"]],
      undefined,
      "Darmanitan é um Pokémon de Unova do tipo Fogo, conhecido como Blazing — prefere áreas vulcânicas e desertos quentes."),
    sp(556, "Maractus", ["Grass"], [75, 86, 67, 106, 67, 60], 255,
      [[1, "Absorb"], [7, "MegaDrain"], [14, "RazorLeaf"], [22, "PetalDance"], [32, "SeedBomb"], [42, "LeafBlade"], [52, "SolarBeam"], [62, "EnergyBall"], [70, "HyperBeam"], [80, "SkullBash"]],
      undefined,
      "Maractus é um Pokémon de Unova do tipo Planta, conhecido como Cactus — vive em florestas e campos, absorvendo luz solar."),
    sp(557, "Dwebble", ["Bug", "Rock"], [50, 65, 85, 35, 35, 55], 190,
      [[1, "LeechLife"], [7, "RockTomb"], [14, "SilverWind"], [22, "BugBite"], [32, "XScissor"], [42, "SignalBeam"], [52, "StoneEdge"], [62, "RockSlide"]],
      [{ speciesId: 558, trigger: "level", level: 34 }],
      "Dwebble é um Pokémon de Unova do tipo Inseto/Pedra, conhecido como Rock Inn — pequeno e ágil, vive em matas e jardins."),
    sp(558, "Crustle", ["Bug", "Rock"], [70, 105, 125, 65, 75, 45], 75,
      [[1, "LeechLife"], [7, "RockTomb"], [14, "SilverWind"], [22, "BugBite"], [32, "XScissor"], [42, "SignalBeam"], [52, "StoneEdge"], [62, "RockSlide"], [70, "XScissor"], [80, "SkullBash"]],
      undefined,
      "Crustle é um Pokémon de Unova do tipo Inseto/Pedra, conhecido como Stone Home — pequeno e ágil, vive em matas e jardins."),
    sp(559, "Scraggy", ["Dark", "Fighting"], [50, 75, 70, 35, 70, 48], 180,
      [[1, "Pursuit"], [7, "LowKick"], [14, "FeintAttack"], [22, "NightSlash"], [32, "Crunch"], [42, "DarkPulse"], [52, "DynamicPunch"], [62, "CrossChop"]],
      [{ speciesId: 560, trigger: "level", level: 39 }],
      "Scraggy é um Pokémon de Unova do tipo Sombrio/Lutador, conhecido como Shedding — age à noite, astuto e desconfiado."),
    sp(560, "Scrafty", ["Dark", "Fighting"], [65, 90, 115, 45, 115, 58], 90,
      [[1, "Pursuit"], [7, "LowKick"], [14, "FeintAttack"], [22, "NightSlash"], [32, "Crunch"], [42, "DarkPulse"], [52, "DynamicPunch"], [62, "CrossChop"], [70, "Crunch"], [80, "SkyUppercut"]],
      undefined,
      "Scrafty é um Pokémon de Unova do tipo Sombrio/Lutador, conhecido como Hoodlum — age à noite, astuto e desconfiado."),
    sp(561, "Sigilyph", ["Psychic", "Flying"], [72, 58, 80, 103, 80, 97], 45,
      [[1, "Confusion"], [7, "Peck"], [14, "AerialAce"], [22, "Psybeam"], [32, "ZenHeadbutt"], [42, "Psychic"], [52, "FutureSight"], [62, "Bounce"], [70, "Fly"], [80, "DrillPeck"]],
      undefined,
      "Sigilyph é um Pokémon de Unova do tipo Psíquico/Voador, conhecido como Avianoid — usa poderes mentais para se comunicar e lutar."),
    sp(562, "Yamask", ["Ghost"], [38, 30, 85, 55, 65, 30], 190,
      [[1, "Lick"], [7, "ShadowSneak"], [14, "Astonish"], [22, "Headbutt"], [32, "ShadowBall"], [42, "SkullBash"], [52, "HyperBeam"], [62, "TakeDown"]],
      [{ speciesId: 563, trigger: "level", level: 34 }],
      "Yamask é um Pokémon de Unova do tipo Fantasma, conhecido como Spirit — aparece em torres e locais abandonados à noite."),
    sp(563, "Cofagrigus", ["Ghost"], [58, 50, 145, 95, 105, 30], 90,
      [[1, "Lick"], [7, "ShadowSneak"], [14, "Astonish"], [22, "Headbutt"], [32, "ShadowBall"], [42, "SkullBash"], [52, "HyperBeam"], [62, "TakeDown"], [70, "ShadowBall"], [80, "HyperFang"]],
      undefined,
      "Cofagrigus é um Pokémon de Unova do tipo Fantasma, conhecido como Coffin — aparece em torres e locais abandonados à noite."),
    sp(564, "Tirtouga", ["Water", "Rock"], [54, 78, 103, 53, 45, 22], 45,
      [[1, "Bubble"], [7, "RockTomb"], [14, "WaterPulse"], [22, "BubbleBeam"], [32, "Waterfall"], [42, "Surf"], [52, "HydroPump"], [62, "Crabhammer"]],
      [{ speciesId: 565, trigger: "level", level: 37 }],
      "Tirtouga é um Pokémon de Unova do tipo Água/Pedra, conhecido como Prototurtle — habita rios, lagos e o litoral de Unova."),
    sp(565, "Carracosta", ["Water", "Rock"], [74, 108, 133, 83, 65, 32], 45,
      [[1, "Bubble"], [7, "RockTomb"], [14, "WaterPulse"], [22, "BubbleBeam"], [32, "Waterfall"], [42, "Surf"], [52, "HydroPump"], [62, "Crabhammer"], [70, "StoneEdge"], [80, "RockSlide"]],
      undefined,
      "Carracosta é um Pokémon de Unova do tipo Água/Pedra, conhecido como Prototurtle — habita rios, lagos e o litoral de Unova."),
    sp(566, "Archen", ["Rock", "Flying"], [55, 112, 45, 74, 45, 70], 45,
      [[1, "RockPolish"], [7, "Peck"], [14, "AncientPower"], [22, "RockTomb"], [32, "RockSlide"], [42, "Bounce"], [52, "StoneEdge"], [62, "Fly"]],
      [{ speciesId: 567, trigger: "level", level: 37 }],
      "Archen é um Pokémon de Unova do tipo Pedra/Voador, conhecido como First Bird — corpo resistente, encontrado em montanhas."),
    sp(567, "Archeops", ["Rock", "Flying"], [75, 140, 65, 112, 65, 110], 45,
      [[1, "RockPolish"], [7, "Peck"], [14, "AncientPower"], [22, "RockTomb"], [32, "RockSlide"], [42, "Bounce"], [52, "StoneEdge"], [62, "Fly"], [70, "DrillPeck"], [80, "AirSlash"]],
      undefined,
      "Archeops é um Pokémon de Unova do tipo Pedra/Voador, conhecido como First Bird — corpo resistente, encontrado em montanhas."),
    sp(568, "Trubbish", ["Poison"], [50, 50, 62, 40, 62, 65], 190,
      [[1, "PoisonSting"], [7, "Acid"], [14, "Swift"], [22, "PoisonFang"], [32, "PoisonJab"], [42, "SludgeBomb"], [52, "HyperBeam"], [62, "SkullBash"]],
      [{ speciesId: 569, trigger: "level", level: 36 }],
      "Trubbish é um Pokémon de Unova do tipo Venenoso, conhecido como Trash Bag — usa toxinas para se defender e caçar."),
    sp(569, "Garbodor", ["Poison"], [80, 95, 82, 60, 82, 75], 60,
      [[1, "PoisonSting"], [7, "Acid"], [14, "Swift"], [22, "PoisonFang"], [32, "PoisonJab"], [42, "SludgeBomb"], [52, "HyperBeam"], [62, "SkullBash"], [70, "SludgeBomb"], [80, "ExtremeSpeed"]],
      undefined,
      "Garbodor é um Pokémon de Unova do tipo Venenoso, conhecido como Trash Heap — usa toxinas para se defender e caçar."),
    sp(570, "Zorua", ["Dark"], [40, 65, 40, 80, 40, 65], 75,
      [[1, "Pursuit"], [7, "PayDay"], [14, "FeintAttack"], [22, "NightSlash"], [32, "Crunch"], [42, "DarkPulse"], [52, "HyperBeam"], [62, "SkullBash"]],
      [{ speciesId: 571, trigger: "level", level: 30 }],
      "Zorua é um Pokémon de Unova do tipo Sombrio, conhecido como Tricky Fox — age à noite, astuto e desconfiado."),
    sp(571, "Zoroark", ["Dark"], [60, 105, 60, 120, 60, 105], 45,
      [[1, "Pursuit"], [7, "PayDay"], [14, "FeintAttack"], [22, "NightSlash"], [32, "Crunch"], [42, "DarkPulse"], [52, "HyperBeam"], [62, "SkullBash"], [70, "Crunch"], [80, "ExtremeSpeed"]],
      undefined,
      "Zoroark é um Pokémon de Unova do tipo Sombrio, conhecido como Illusion Fox — age à noite, astuto e desconfiado."),
    sp(572, "Minccino", ["Normal"], [55, 50, 40, 40, 40, 75], 255,
      [[1, "Scratch"], [7, "PayDay"], [14, "Swift"], [22, "Headbutt"], [32, "ExtremeSpeed"], [42, "SkullBash"], [52, "HyperBeam"], [62, "TakeDown"]],
      [{ speciesId: 573, trigger: "item", itemId: EVOLUTION_ITEM_IDS.shinyStone }],
      "Minccino é um Pokémon de Unova do tipo Normal, conhecido como Chinchilla — comum nas rotas e cidades, adaptável e curioso."),
    sp(573, "Cinccino", ["Normal"], [75, 95, 60, 65, 60, 115], 60,
      [[1, "Scratch"], [7, "PayDay"], [14, "Swift"], [22, "Headbutt"], [32, "ExtremeSpeed"], [42, "SkullBash"], [52, "HyperBeam"], [62, "TakeDown"], [70, "HyperFang"], [80, "Slash"]],
      undefined,
      "Cinccino é um Pokémon de Unova do tipo Normal, conhecido como Scarf — comum nas rotas e cidades, adaptável e curioso."),
    sp(574, "Gothita", ["Psychic"], [45, 30, 50, 55, 65, 45], 200,
      [[1, "Confusion"], [7, "PayDay"], [14, "Swift"], [22, "Psybeam"], [32, "ZenHeadbutt"], [42, "Psychic"], [52, "FutureSight"], [62, "HyperBeam"]],
      [{ speciesId: 575, trigger: "level", level: 32 }],
      "Gothita é um Pokémon de Unova do tipo Psíquico, conhecido como Fixation — usa poderes mentais para se comunicar e lutar."),
    sp(575, "Gothorita", ["Psychic"], [60, 45, 70, 75, 85, 55], 100,
      [[1, "Confusion"], [7, "PayDay"], [14, "Swift"], [22, "Psybeam"], [32, "ZenHeadbutt"], [42, "Psychic"], [52, "FutureSight"], [62, "HyperBeam"]],
      [{ speciesId: 576, trigger: "level", level: 41 }],
      "Gothorita é um Pokémon de Unova do tipo Psíquico, conhecido como Manipulate — usa poderes mentais para se comunicar e lutar."),
    sp(576, "Gothitelle", ["Psychic"], [70, 55, 95, 95, 110, 65], 50,
      [[1, "Confusion"], [7, "PayDay"], [14, "Swift"], [22, "Psybeam"], [32, "ZenHeadbutt"], [42, "Psychic"], [52, "FutureSight"], [62, "HyperBeam"], [70, "SkullBash"], [80, "TakeDown"]],
      undefined,
      "Gothitelle é um Pokémon de Unova do tipo Psíquico, conhecido como Astral Body — usa poderes mentais para se comunicar e lutar."),
    sp(577, "Solosis", ["Psychic"], [45, 30, 40, 105, 50, 20], 200,
      [[1, "Confusion"], [7, "PayDay"], [14, "Swift"], [22, "Psybeam"], [32, "ZenHeadbutt"], [42, "Psychic"], [52, "FutureSight"], [62, "HyperBeam"]],
      [{ speciesId: 578, trigger: "level", level: 32 }],
      "Solosis é um Pokémon de Unova do tipo Psíquico, conhecido como Cell — usa poderes mentais para se comunicar e lutar."),
    sp(578, "Duosion", ["Psychic"], [65, 40, 50, 125, 60, 30], 100,
      [[1, "Confusion"], [7, "PayDay"], [14, "Swift"], [22, "Psybeam"], [32, "ZenHeadbutt"], [42, "Psychic"], [52, "FutureSight"], [62, "HyperBeam"]],
      [{ speciesId: 579, trigger: "level", level: 41 }],
      "Duosion é um Pokémon de Unova do tipo Psíquico, conhecido como Mitosis — usa poderes mentais para se comunicar e lutar."),
    sp(579, "Reuniclus", ["Psychic"], [110, 65, 75, 125, 85, 30], 50,
      [[1, "Confusion"], [7, "PayDay"], [14, "Swift"], [22, "Psybeam"], [32, "ZenHeadbutt"], [42, "Psychic"], [52, "FutureSight"], [62, "HyperBeam"], [70, "SkullBash"], [80, "TakeDown"]],
      undefined,
      "Reuniclus é um Pokémon de Unova do tipo Psíquico, conhecido como Multiplying — usa poderes mentais para se comunicar e lutar."),
    sp(580, "Ducklett", ["Water", "Flying"], [62, 44, 50, 44, 50, 55], 190,
      [[1, "Bubble"], [7, "Peck"], [14, "WaterPulse"], [22, "BubbleBeam"], [32, "Waterfall"], [42, "Surf"], [52, "HydroPump"], [62, "Crabhammer"]],
      [{ speciesId: 581, trigger: "level", level: 35 }],
      "Ducklett é um Pokémon de Unova do tipo Água/Voador, conhecido como Water Bird — habita rios, lagos e o litoral de Unova."),
    sp(581, "Swanna", ["Water", "Flying"], [75, 87, 63, 87, 63, 98], 45,
      [[1, "Bubble"], [7, "Peck"], [14, "WaterPulse"], [22, "BubbleBeam"], [32, "Waterfall"], [42, "Surf"], [52, "HydroPump"], [62, "Crabhammer"], [70, "Bounce"], [80, "Fly"]],
      undefined,
      "Swanna é um Pokémon de Unova do tipo Água/Voador, conhecido como White Bird — habita rios, lagos e o litoral de Unova."),
    sp(582, "Vanillite", ["Ice"], [36, 50, 50, 65, 60, 44], 255,
      [[1, "IceShard"], [7, "PowderSnow"], [14, "IcyWind"], [22, "IceFang"], [32, "IcePunch"], [42, "IceBeam"], [52, "Blizzard"], [62, "HyperBeam"]],
      [{ speciesId: 583, trigger: "level", level: 35 }],
      "Vanillite é um Pokémon de Unova do tipo Gelo, conhecido como Fresh Snow — habita picos nevados e cavernas geladas."),
    sp(583, "Vanillish", ["Ice"], [51, 65, 65, 80, 75, 59], 120,
      [[1, "IceShard"], [7, "PowderSnow"], [14, "IcyWind"], [22, "IceFang"], [32, "IcePunch"], [42, "IceBeam"], [52, "Blizzard"], [62, "HyperBeam"]],
      [{ speciesId: 584, trigger: "level", level: 47 }],
      "Vanillish é um Pokémon de Unova do tipo Gelo, conhecido como Icy Snow — habita picos nevados e cavernas geladas."),
    sp(584, "Vanilluxe", ["Ice"], [71, 95, 85, 110, 95, 79], 45,
      [[1, "IceShard"], [7, "PowderSnow"], [14, "IcyWind"], [22, "IceFang"], [32, "IcePunch"], [42, "IceBeam"], [52, "Blizzard"], [62, "HyperBeam"], [70, "SkullBash"], [80, "TakeDown"]],
      undefined,
      "Vanilluxe é um Pokémon de Unova do tipo Gelo, conhecido como Snowstorm — habita picos nevados e cavernas geladas."),
    sp(585, "Deerling", ["Normal", "Grass"], [60, 60, 50, 40, 50, 75], 190,
      [[1, "Scratch"], [7, "MegaDrain"], [14, "Swift"], [22, "Headbutt"], [32, "ExtremeSpeed"], [42, "SkullBash"], [52, "HyperBeam"], [62, "TakeDown"]],
      [{ speciesId: 586, trigger: "level", level: 34 }],
      "Deerling é um Pokémon de Unova do tipo Normal/Planta, conhecido como Season — comum nas rotas e cidades, adaptável e curioso."),
    sp(586, "Sawsbuck", ["Normal", "Grass"], [80, 100, 70, 60, 70, 95], 75,
      [[1, "Scratch"], [7, "MegaDrain"], [14, "Swift"], [22, "Headbutt"], [32, "ExtremeSpeed"], [42, "SkullBash"], [52, "HyperBeam"], [62, "TakeDown"], [70, "HyperFang"], [80, "Slash"]],
      undefined,
      "Sawsbuck é um Pokémon de Unova do tipo Normal/Planta, conhecido como Season — comum nas rotas e cidades, adaptável e curioso."),
    sp(587, "Emolga", ["Electric", "Flying"], [55, 75, 60, 75, 60, 103], 200,
      [[1, "ThunderShock"], [7, "Peck"], [14, "ShockWave"], [22, "Spark"], [32, "Discharge"], [42, "Thunderbolt"], [52, "Thunder"], [62, "WildCharge"], [70, "ThunderPunch"], [80, "Bounce"]],
      undefined,
      "Emolga é um Pokémon de Unova do tipo Elétrico/Voador, conhecido como Sky Squirrel — acumula energia em tempestades e usinas."),
    sp(588, "Karrablast", ["Bug"], [50, 75, 45, 40, 45, 60], 200,
      [[1, "LeechLife"], [7, "Twineedle"], [14, "SilverWind"], [22, "BugBite"], [32, "XScissor"], [42, "SignalBeam"], [52, "HyperBeam"], [62, "SkullBash"]],
      [{ speciesId: 589, trigger: "level", level: 36 }],
      "Karrablast é um Pokémon de Unova do tipo Inseto, conhecido como Clamping — pequeno e ágil, vive em matas e jardins."),
    sp(589, "Escavalier", ["Bug", "Steel"], [70, 135, 105, 60, 105, 20], 75,
      [[1, "LeechLife"], [7, "MetalClaw"], [14, "SilverWind"], [22, "BugBite"], [32, "XScissor"], [42, "SignalBeam"], [52, "IronTail"], [62, "FlashCannon"], [70, "XScissor"], [80, "SteelWing"]],
      undefined,
      "Escavalier é um Pokémon de Unova do tipo Inseto/Aço, conhecido como Cavalry — pequeno e ágil, vive em matas e jardins."),
    sp(590, "Foongus", ["Grass", "Poison"], [69, 55, 45, 55, 55, 15], 190,
      [[1, "Absorb"], [7, "Acid"], [14, "MegaDrain"], [22, "PetalDance"], [32, "SeedBomb"], [42, "LeafBlade"], [52, "SolarBeam"], [62, "EnergyBall"]],
      [{ speciesId: 591, trigger: "level", level: 39 }],
      "Foongus é um Pokémon de Unova do tipo Planta/Venenoso, conhecido como Mushroom — vive em florestas e campos, absorvendo luz solar."),
    sp(591, "Amoonguss", ["Grass", "Poison"], [114, 85, 70, 85, 80, 30], 75,
      [[1, "Absorb"], [7, "Acid"], [14, "MegaDrain"], [22, "PetalDance"], [32, "SeedBomb"], [42, "LeafBlade"], [52, "SolarBeam"], [62, "EnergyBall"], [70, "SludgeBomb"], [80, "PoisonJab"]],
      undefined,
      "Amoonguss é um Pokémon de Unova do tipo Planta/Venenoso, conhecido como Mushroom — vive em florestas e campos, absorvendo luz solar."),
    sp(592, "Frillish", ["Water", "Ghost"], [55, 40, 50, 65, 85, 40], 190,
      [[1, "Bubble"], [7, "ShadowSneak"], [14, "WaterPulse"], [22, "BubbleBeam"], [32, "Waterfall"], [42, "Surf"], [52, "HydroPump"], [62, "Crabhammer"]],
      [{ speciesId: 593, trigger: "level", level: 40 }],
      "Frillish é um Pokémon de Unova do tipo Água/Fantasma, conhecido como Floating — habita rios, lagos e o litoral de Unova."),
    sp(593, "Jellicent", ["Water", "Ghost"], [100, 60, 70, 85, 105, 60], 60,
      [[1, "Bubble"], [7, "ShadowSneak"], [14, "WaterPulse"], [22, "BubbleBeam"], [32, "Waterfall"], [42, "Surf"], [52, "HydroPump"], [62, "Crabhammer"], [70, "ShadowBall"], [80, "HyperBeam"]],
      undefined,
      "Jellicent é um Pokémon de Unova do tipo Água/Fantasma, conhecido como Floating — habita rios, lagos e o litoral de Unova."),
    sp(594, "Alomomola", ["Water"], [165, 75, 80, 40, 45, 65], 75,
      [[1, "Bubble"], [7, "WaterGun"], [14, "WaterPulse"], [22, "BubbleBeam"], [32, "Waterfall"], [42, "Surf"], [52, "HydroPump"], [62, "Crabhammer"], [70, "HyperBeam"], [80, "SkullBash"]],
      undefined,
      "Alomomola é um Pokémon de Unova do tipo Água, conhecido como Caring — habita rios, lagos e o litoral de Unova."),
    sp(595, "Joltik", ["Bug", "Electric"], [50, 47, 50, 57, 50, 65], 190,
      [[1, "LeechLife"], [7, "ThunderShock"], [14, "SilverWind"], [22, "BugBite"], [32, "XScissor"], [42, "SignalBeam"], [52, "Thunder"], [62, "Thunderbolt"]],
      [{ speciesId: 596, trigger: "level", level: 36 }],
      "Joltik é um Pokémon de Unova do tipo Inseto/Elétrico, conhecido como Attaching — pequeno e ágil, vive em matas e jardins."),
    sp(596, "Galvantula", ["Bug", "Electric"], [70, 77, 60, 97, 60, 108], 75,
      [[1, "LeechLife"], [7, "ThunderShock"], [14, "SilverWind"], [22, "BugBite"], [32, "XScissor"], [42, "SignalBeam"], [52, "Thunder"], [62, "Thunderbolt"], [70, "XScissor"], [80, "Discharge"]],
      undefined,
      "Galvantula é um Pokémon de Unova do tipo Inseto/Elétrico, conhecido como EleSpider — pequeno e ágil, vive em matas e jardins."),
    sp(597, "Ferroseed", ["Grass", "Steel"], [44, 50, 91, 24, 86, 10], 255,
      [[1, "Absorb"], [7, "MetalClaw"], [14, "MegaDrain"], [22, "PetalDance"], [32, "SeedBomb"], [42, "LeafBlade"], [52, "SolarBeam"], [62, "EnergyBall"]],
      [{ speciesId: 598, trigger: "level", level: 40 }],
      "Ferroseed é um Pokémon de Unova do tipo Planta/Aço, conhecido como Thorn Seed — vive em florestas e campos, absorvendo luz solar."),
    sp(598, "Ferrothorn", ["Grass", "Steel"], [74, 94, 131, 54, 116, 20], 90,
      [[1, "Absorb"], [7, "MetalClaw"], [14, "MegaDrain"], [22, "PetalDance"], [32, "SeedBomb"], [42, "LeafBlade"], [52, "SolarBeam"], [62, "EnergyBall"], [70, "IronTail"], [80, "FlashCannon"]],
      undefined,
      "Ferrothorn é um Pokémon de Unova do tipo Planta/Aço, conhecido como Thorn Pod — vive em florestas e campos, absorvendo luz solar."),
    sp(599, "Klink", ["Steel"], [40, 55, 70, 45, 60, 30], 130,
      [[1, "MetalClaw"], [7, "PayDay"], [14, "MagnetBomb"], [22, "SteelWing"], [32, "FlashCannon"], [42, "IronHead"], [52, "IronTail"], [62, "HyperBeam"]],
      [{ speciesId: 600, trigger: "level", level: 38 }],
      "Klink é um Pokémon de Unova do tipo Aço, conhecido como Gear — corpo metálico e defesa inabalável."),
    sp(600, "Klang", ["Steel"], [60, 80, 95, 70, 85, 50], 60,
      [[1, "MetalClaw"], [7, "PayDay"], [14, "MagnetBomb"], [22, "SteelWing"], [32, "FlashCannon"], [42, "IronHead"], [52, "IronTail"], [62, "HyperBeam"]],
      [{ speciesId: 601, trigger: "level", level: 49 }],
      "Klang é um Pokémon de Unova do tipo Aço, conhecido como Gear — corpo metálico e defesa inabalável."),
    sp(601, "Klinklang", ["Steel"], [60, 100, 115, 70, 85, 90], 30,
      [[1, "MetalClaw"], [7, "PayDay"], [14, "MagnetBomb"], [22, "SteelWing"], [32, "FlashCannon"], [42, "IronHead"], [52, "IronTail"], [62, "HyperBeam"], [70, "SkullBash"], [80, "TakeDown"]],
      undefined,
      "Klinklang é um Pokémon de Unova do tipo Aço, conhecido como Gear — corpo metálico e defesa inabalável."),
    sp(602, "Tynamo", ["Electric"], [35, 55, 40, 45, 40, 60], 190,
      [[1, "ThunderShock"], [7, "PayDay"], [14, "ShockWave"], [22, "Spark"], [32, "Discharge"], [42, "Thunderbolt"], [52, "Thunder"], [62, "WildCharge"]],
      [{ speciesId: 603, trigger: "level", level: 39 }],
      "Tynamo é um Pokémon de Unova do tipo Elétrico, conhecido como EleFish — acumula energia em tempestades e usinas."),
    sp(603, "Eelektrik", ["Electric"], [65, 85, 70, 75, 70, 40], 60,
      [[1, "ThunderShock"], [7, "PayDay"], [14, "ShockWave"], [22, "Spark"], [32, "Discharge"], [42, "Thunderbolt"], [52, "Thunder"], [62, "WildCharge"]],
      [{ speciesId: 604, trigger: "item", itemId: EVOLUTION_ITEM_IDS.thunderStone }],
      "Eelektrik é um Pokémon de Unova do tipo Elétrico, conhecido como EleFish — acumula energia em tempestades e usinas."),
    sp(604, "Eelektross", ["Electric"], [85, 115, 80, 105, 80, 50], 30,
      [[1, "ThunderShock"], [7, "PayDay"], [14, "ShockWave"], [22, "Spark"], [32, "Discharge"], [42, "Thunderbolt"], [52, "Thunder"], [62, "WildCharge"], [70, "ThunderPunch"], [80, "HyperBeam"]],
      undefined,
      "Eelektross é um Pokémon de Unova do tipo Elétrico, conhecido como EleFish — acumula energia em tempestades e usinas."),
    sp(605, "Elgyem", ["Psychic"], [55, 55, 55, 85, 55, 30], 255,
      [[1, "Confusion"], [7, "PayDay"], [14, "Swift"], [22, "Psybeam"], [32, "ZenHeadbutt"], [42, "Psychic"], [52, "FutureSight"], [62, "HyperBeam"]],
      [{ speciesId: 606, trigger: "level", level: 42 }],
      "Elgyem é um Pokémon de Unova do tipo Psíquico, conhecido como Cerebral — usa poderes mentais para se comunicar e lutar."),
    sp(606, "Beheeyem", ["Psychic"], [75, 75, 75, 125, 95, 40], 90,
      [[1, "Confusion"], [7, "PayDay"], [14, "Swift"], [22, "Psybeam"], [32, "ZenHeadbutt"], [42, "Psychic"], [52, "FutureSight"], [62, "HyperBeam"], [70, "SkullBash"], [80, "TakeDown"]],
      undefined,
      "Beheeyem é um Pokémon de Unova do tipo Psíquico, conhecido como Cerebral — usa poderes mentais para se comunicar e lutar."),
    sp(607, "Litwick", ["Ghost", "Fire"], [50, 30, 55, 65, 55, 20], 190,
      [[1, "Lick"], [7, "FireSpin"], [14, "ShadowSneak"], [22, "FireFang"], [32, "ShadowBall"], [42, "Flamethrower"], [52, "Overheat"], [62, "FireBlast"]],
      [{ speciesId: 608, trigger: "level", level: 41 }],
      "Litwick é um Pokémon de Unova do tipo Fantasma/Fogo, conhecido como Candle — aparece em torres e locais abandonados à noite."),
    sp(608, "Lampent", ["Ghost", "Fire"], [60, 40, 60, 95, 60, 55], 90,
      [[1, "Lick"], [7, "FireSpin"], [14, "ShadowSneak"], [22, "FireFang"], [32, "ShadowBall"], [42, "Flamethrower"], [52, "Overheat"], [62, "FireBlast"]],
      [{ speciesId: 609, trigger: "item", itemId: EVOLUTION_ITEM_IDS.duskStone }],
      "Lampent é um Pokémon de Unova do tipo Fantasma/Fogo, conhecido como Lamp — aparece em torres e locais abandonados à noite."),
    sp(609, "Chandelure", ["Ghost", "Fire"], [60, 55, 90, 145, 90, 80], 45,
      [[1, "Lick"], [7, "FireSpin"], [14, "ShadowSneak"], [22, "FireFang"], [32, "ShadowBall"], [42, "Flamethrower"], [52, "Overheat"], [62, "FireBlast"], [70, "ShadowBall"], [80, "HyperBeam"]],
      undefined,
      "Chandelure é um Pokémon de Unova do tipo Fantasma/Fogo, conhecido como Luring — aparece em torres e locais abandonados à noite."),
    sp(610, "Axew", ["Dragon"], [46, 87, 60, 30, 40, 57], 75,
      [[1, "Twister"], [7, "PayDay"], [14, "DragonBreath"], [22, "Headbutt"], [32, "DragonClaw"], [42, "Outrage"], [52, "DragonPulse"], [62, "HyperBeam"]],
      [{ speciesId: 611, trigger: "level", level: 38 }],
      "Axew é um Pokémon de Unova do tipo Dragão, conhecido como Tusk — raro e imponente, com poder ancestral."),
    sp(611, "Fraxure", ["Dragon"], [66, 117, 70, 40, 50, 67], 60,
      [[1, "Twister"], [7, "PayDay"], [14, "DragonBreath"], [22, "Headbutt"], [32, "DragonClaw"], [42, "Outrage"], [52, "DragonPulse"], [62, "HyperBeam"]],
      [{ speciesId: 612, trigger: "level", level: 48 }],
      "Fraxure é um Pokémon de Unova do tipo Dragão, conhecido como Axe Jaw — raro e imponente, com poder ancestral."),
    sp(612, "Haxorus", ["Dragon"], [76, 147, 90, 60, 70, 97], 45,
      [[1, "Twister"], [7, "PayDay"], [14, "DragonBreath"], [22, "Headbutt"], [32, "DragonClaw"], [42, "Outrage"], [52, "DragonPulse"], [62, "HyperBeam"], [70, "SkullBash"], [80, "TakeDown"]],
      undefined,
      "Haxorus é um Pokémon de Unova do tipo Dragão, conhecido como Axe Jaw — raro e imponente, com poder ancestral."),
    sp(613, "Cubchoo", ["Ice"], [55, 70, 40, 60, 40, 40], 120,
      [[1, "IceShard"], [7, "PowderSnow"], [14, "IcyWind"], [22, "IceFang"], [32, "IcePunch"], [42, "IceBeam"], [52, "Blizzard"], [62, "HyperBeam"]],
      [{ speciesId: 614, trigger: "level", level: 37 }],
      "Cubchoo é um Pokémon de Unova do tipo Gelo, conhecido como Chill — habita picos nevados e cavernas geladas."),
    sp(614, "Beartic", ["Ice"], [95, 130, 80, 70, 80, 50], 60,
      [[1, "IceShard"], [7, "PowderSnow"], [14, "IcyWind"], [22, "IceFang"], [32, "IcePunch"], [42, "IceBeam"], [52, "Blizzard"], [62, "HyperBeam"], [70, "SkullBash"], [80, "TakeDown"]],
      undefined,
      "Beartic é um Pokémon de Unova do tipo Gelo, conhecido como Freezing — habita picos nevados e cavernas geladas."),
    sp(615, "Cryogonal", ["Ice"], [80, 50, 50, 95, 135, 105], 25,
      [[1, "IceShard"], [7, "PowderSnow"], [14, "IcyWind"], [22, "IceFang"], [32, "IcePunch"], [42, "IceBeam"], [52, "Blizzard"], [62, "HyperBeam"], [70, "SkullBash"], [80, "TakeDown"]],
      undefined,
      "Cryogonal é um Pokémon de Unova do tipo Gelo, conhecido como Crystallizing — habita picos nevados e cavernas geladas."),
    sp(616, "Shelmet", ["Bug"], [50, 40, 85, 40, 65, 25], 200,
      [[1, "LeechLife"], [7, "Twineedle"], [14, "SilverWind"], [22, "BugBite"], [32, "XScissor"], [42, "SignalBeam"], [52, "HyperBeam"], [62, "SkullBash"]],
      [{ speciesId: 617, trigger: "level", level: 36 }],
      "Shelmet é um Pokémon de Unova do tipo Inseto, conhecido como Snail — pequeno e ágil, vive em matas e jardins."),
    sp(617, "Accelgor", ["Bug"], [80, 70, 40, 100, 60, 145], 75,
      [[1, "LeechLife"], [7, "Twineedle"], [14, "SilverWind"], [22, "BugBite"], [32, "XScissor"], [42, "SignalBeam"], [52, "HyperBeam"], [62, "SkullBash"], [70, "XScissor"], [80, "ExtremeSpeed"]],
      undefined,
      "Accelgor é um Pokémon de Unova do tipo Inseto, conhecido como Shell Out — pequeno e ágil, vive em matas e jardins."),
    sp(618, "Stunfisk", ["Ground", "Electric"], [109, 66, 84, 81, 99, 32], 75,
      [[1, "MudSlap"], [7, "ThunderShock"], [14, "MudShot"], [22, "BoneClub"], [32, "Dig"], [42, "EarthPower"], [52, "Earthquake"], [62, "Bonemerang"], [70, "Thunder"], [80, "Thunderbolt"]],
      undefined,
      "Stunfisk é um Pokémon de Unova do tipo Terrestre/Elétrico, conhecido como Trap — cava túneis e vive em cavernas e desertos."),
    sp(619, "Mienfoo", ["Fighting"], [45, 85, 50, 55, 50, 65], 180,
      [[1, "MachPunch"], [7, "LowKick"], [14, "RollingKick"], [22, "VitalThrow"], [32, "Submission"], [42, "SkyUppercut"], [52, "DynamicPunch"], [62, "CrossChop"]],
      [{ speciesId: 620, trigger: "level", level: 50 }],
      "Mienfoo é um Pokémon de Unova do tipo Lutador, conhecido como Martial Arts — treina artes marciais nas montanhas."),
    sp(620, "Mienshao", ["Fighting"], [65, 125, 60, 95, 60, 105], 45,
      [[1, "MachPunch"], [7, "LowKick"], [14, "RollingKick"], [22, "VitalThrow"], [32, "Submission"], [42, "SkyUppercut"], [52, "DynamicPunch"], [62, "CrossChop"], [70, "HighJumpKick"], [80, "AuraSphere"]],
      undefined,
      "Mienshao é um Pokémon de Unova do tipo Lutador, conhecido como Martial Arts — treina artes marciais nas montanhas."),
    sp(621, "Druddigon", ["Dragon"], [77, 120, 90, 60, 90, 48], 45,
      [[1, "Twister"], [7, "PayDay"], [14, "DragonBreath"], [22, "Headbutt"], [32, "DragonClaw"], [42, "Outrage"], [52, "DragonPulse"], [62, "HyperBeam"], [70, "SkullBash"], [80, "TakeDown"]],
      undefined,
      "Druddigon é um Pokémon de Unova do tipo Dragão, conhecido como Cave — raro e imponente, com poder ancestral."),
    sp(622, "Golett", ["Ground", "Ghost"], [59, 74, 50, 35, 50, 35], 190,
      [[1, "MudSlap"], [7, "ShadowSneak"], [14, "MudShot"], [22, "BoneClub"], [32, "Dig"], [42, "EarthPower"], [52, "Earthquake"], [62, "Bonemerang"]],
      [{ speciesId: 623, trigger: "level", level: 43 }],
      "Golett é um Pokémon de Unova do tipo Terrestre/Fantasma, conhecido como Automaton — cava túneis e vive em cavernas e desertos."),
    sp(623, "Golurk", ["Ground", "Ghost"], [89, 124, 80, 55, 80, 55], 90,
      [[1, "MudSlap"], [7, "ShadowSneak"], [14, "MudShot"], [22, "BoneClub"], [32, "Dig"], [42, "EarthPower"], [52, "Earthquake"], [62, "Bonemerang"], [70, "ShadowBall"], [80, "HyperBeam"]],
      undefined,
      "Golurk é um Pokémon de Unova do tipo Terrestre/Fantasma, conhecido como Automaton — cava túneis e vive em cavernas e desertos."),
    sp(624, "Pawniard", ["Dark", "Steel"], [45, 85, 70, 40, 40, 60], 120,
      [[1, "Pursuit"], [7, "MetalClaw"], [14, "FeintAttack"], [22, "NightSlash"], [32, "Crunch"], [42, "DarkPulse"], [52, "IronTail"], [62, "FlashCannon"]],
      [{ speciesId: 625, trigger: "level", level: 52 }],
      "Pawniard é um Pokémon de Unova do tipo Sombrio/Aço, conhecido como Sharp Blade — age à noite, astuto e desconfiado."),
    sp(625, "Bisharp", ["Dark", "Steel"], [65, 125, 100, 60, 70, 70], 45,
      [[1, "Pursuit"], [7, "MetalClaw"], [14, "FeintAttack"], [22, "NightSlash"], [32, "Crunch"], [42, "DarkPulse"], [52, "IronTail"], [62, "FlashCannon"], [70, "Crunch"], [80, "SteelWing"]],
      undefined,
      "Bisharp é um Pokémon de Unova do tipo Sombrio/Aço, conhecido como Sword Blade — age à noite, astuto e desconfiado."),
    sp(626, "Bouffalant", ["Normal"], [95, 110, 95, 40, 95, 55], 45,
      [[1, "Scratch"], [7, "PayDay"], [14, "Swift"], [22, "Headbutt"], [32, "ExtremeSpeed"], [42, "SkullBash"], [52, "HyperBeam"], [62, "TakeDown"], [70, "HyperFang"], [80, "Slash"]],
      undefined,
      "Bouffalant é um Pokémon de Unova do tipo Normal, conhecido como Bash Buffalo — comum nas rotas e cidades, adaptável e curioso."),
    sp(627, "Rufflet", ["Normal", "Flying"], [70, 83, 50, 37, 50, 60], 190,
      [[1, "Scratch"], [7, "Peck"], [14, "Swift"], [22, "Headbutt"], [32, "ExtremeSpeed"], [42, "SkullBash"], [52, "HyperBeam"], [62, "TakeDown"]],
      [{ speciesId: 628, trigger: "level", level: 54 }],
      "Rufflet é um Pokémon de Unova do tipo Normal/Voador, conhecido como Eaglet — comum nas rotas e cidades, adaptável e curioso."),
    sp(628, "Braviary", ["Normal", "Flying"], [100, 123, 75, 57, 75, 80], 60,
      [[1, "Scratch"], [7, "Peck"], [14, "Swift"], [22, "Headbutt"], [32, "ExtremeSpeed"], [42, "SkullBash"], [52, "HyperBeam"], [62, "TakeDown"], [70, "HyperFang"], [80, "Slash"]],
      undefined,
      "Braviary é um Pokémon de Unova do tipo Normal/Voador, conhecido como Valiant — comum nas rotas e cidades, adaptável e curioso."),
    sp(629, "Vullaby", ["Dark", "Flying"], [70, 55, 75, 45, 65, 60], 190,
      [[1, "Pursuit"], [7, "Peck"], [14, "FeintAttack"], [22, "NightSlash"], [32, "Crunch"], [42, "DarkPulse"], [52, "Bounce"], [62, "Fly"]],
      [{ speciesId: 630, trigger: "level", level: 54 }],
      "Vullaby é um Pokémon de Unova do tipo Sombrio/Voador, conhecido como Diapered — age à noite, astuto e desconfiado."),
    sp(630, "Mandibuzz", ["Dark", "Flying"], [110, 65, 105, 55, 95, 80], 60,
      [[1, "Pursuit"], [7, "Peck"], [14, "FeintAttack"], [22, "NightSlash"], [32, "Crunch"], [42, "DarkPulse"], [52, "Bounce"], [62, "Fly"], [70, "Crunch"], [80, "AirSlash"]],
      undefined,
      "Mandibuzz é um Pokémon de Unova do tipo Sombrio/Voador, conhecido como Bone Vulture — age à noite, astuto e desconfiado."),
    sp(631, "Heatmor", ["Fire"], [85, 97, 66, 105, 66, 65], 90,
      [[1, "Ember"], [7, "FireSpin"], [14, "FlameWheel"], [22, "FireFang"], [32, "FirePunch"], [42, "Flamethrower"], [52, "Overheat"], [62, "FireBlast"], [70, "HyperBeam"], [80, "SkullBash"]],
      undefined,
      "Heatmor é um Pokémon de Unova do tipo Fogo, conhecido como Anteater — prefere áreas vulcânicas e desertos quentes."),
    sp(632, "Durant", ["Bug", "Steel"], [58, 109, 112, 48, 48, 109], 90,
      [[1, "LeechLife"], [7, "MetalClaw"], [14, "SilverWind"], [22, "BugBite"], [32, "XScissor"], [42, "SignalBeam"], [52, "IronTail"], [62, "FlashCannon"], [70, "XScissor"], [80, "SteelWing"]],
      undefined,
      "Durant é um Pokémon de Unova do tipo Inseto/Aço, conhecido como Iron Ant — pequeno e ágil, vive em matas e jardins."),
    sp(633, "Deino", ["Dark", "Dragon"], [52, 65, 50, 45, 50, 38], 45,
      [[1, "Pursuit"], [7, "Twister"], [14, "FeintAttack"], [22, "NightSlash"], [32, "Crunch"], [42, "DarkPulse"], [52, "Outrage"], [62, "DragonPulse"]],
      [{ speciesId: 634, trigger: "level", level: 50 }],
      "Deino é um Pokémon de Unova do tipo Sombrio/Dragão, conhecido como Irate — age à noite, astuto e desconfiado."),
    sp(634, "Zweilous", ["Dark", "Dragon"], [72, 85, 70, 65, 70, 58], 45,
      [[1, "Pursuit"], [7, "Twister"], [14, "FeintAttack"], [22, "NightSlash"], [32, "Crunch"], [42, "DarkPulse"], [52, "Outrage"], [62, "DragonPulse"]],
      [{ speciesId: 635, trigger: "level", level: 64 }],
      "Zweilous é um Pokémon de Unova do tipo Sombrio/Dragão, conhecido como Hostile — age à noite, astuto e desconfiado."),
    sp(635, "Hydreigon", ["Dark", "Dragon"], [92, 105, 90, 125, 90, 98], 45,
      [[1, "Pursuit"], [7, "Twister"], [14, "FeintAttack"], [22, "NightSlash"], [32, "Crunch"], [42, "DarkPulse"], [52, "Outrage"], [62, "DragonPulse"], [70, "Crunch"], [80, "HyperBeam"]],
      undefined,
      "Hydreigon é um Pokémon de Unova do tipo Sombrio/Dragão, conhecido como Brutal — age à noite, astuto e desconfiado."),
    sp(636, "Larvesta", ["Bug", "Fire"], [55, 85, 55, 50, 55, 60], 45,
      [[1, "LeechLife"], [7, "FireSpin"], [14, "SilverWind"], [22, "BugBite"], [32, "XScissor"], [42, "SignalBeam"], [52, "Overheat"], [62, "FireBlast"]],
      [{ speciesId: 637, trigger: "level", level: 59 }],
      "Larvesta é um Pokémon de Unova do tipo Inseto/Fogo, conhecido como Torch — pequeno e ágil, vive em matas e jardins."),
    sp(637, "Volcarona", ["Bug", "Fire"], [85, 60, 65, 135, 105, 100], 15,
      [[1, "LeechLife"], [7, "FireSpin"], [14, "SilverWind"], [22, "BugBite"], [32, "XScissor"], [42, "SignalBeam"], [52, "Overheat"], [62, "FireBlast"], [70, "XScissor"], [80, "FirePunch"]],
      undefined,
      "Volcarona é um Pokémon de Unova do tipo Inseto/Fogo, conhecido como Sun — pequeno e ágil, vive em matas e jardins."),
    sp(638, "Cobalion", ["Steel", "Fighting"], [91, 90, 129, 90, 72, 108], 3,
      [[1, "MetalClaw"], [7, "LowKick"], [14, "MagnetBomb"], [22, "SteelWing"], [32, "FlashCannon"], [42, "IronHead"], [52, "IronTail"], [62, "DynamicPunch"], [70, "CrossChop"], [80, "HighJumpKick"]],
      undefined,
      "Lendário de Unova do tipo Aço/Lutador; líder dos Espadas da Justiça."),
    sp(639, "Terrakion", ["Rock", "Fighting"], [91, 129, 90, 72, 90, 108], 3,
      [[1, "RockPolish"], [7, "LowKick"], [14, "AncientPower"], [22, "RockTomb"], [32, "RockSlide"], [42, "SkyUppercut"], [52, "StoneEdge"], [62, "DynamicPunch"], [70, "CrossChop"], [80, "HighJumpKick"]],
      undefined,
      "Lendário de Unova do tipo Pedra/Lutador; força que racha montanhas."),
    sp(640, "Virizion", ["Grass", "Fighting"], [91, 90, 72, 90, 129, 108], 3,
      [[1, "Absorb"], [7, "LowKick"], [14, "MegaDrain"], [22, "PetalDance"], [32, "SeedBomb"], [42, "LeafBlade"], [52, "SolarBeam"], [62, "EnergyBall"], [70, "DynamicPunch"], [80, "CrossChop"]],
      undefined,
      "Lendário de Unova do tipo Planta/Lutador; protege campos com chifres."),
    sp(641, "Tornadus", ["Flying"], [79, 115, 70, 125, 80, 111], 3,
      [[1, "Gust"], [7, "Peck"], [14, "AerialAce"], [22, "WingAttack"], [32, "Fly"], [42, "Bounce"], [52, "DrillPeck"], [62, "AirSlash"], [70, "HyperBeam"], [80, "SkullBash"]],
      undefined,
      "Lendário de Unova do tipo Voador; tempestades seguem seu voo."),
    sp(642, "Thundurus", ["Electric", "Flying"], [79, 115, 70, 125, 80, 111], 3,
      [[1, "ThunderShock"], [7, "Peck"], [14, "ShockWave"], [22, "Spark"], [32, "Discharge"], [42, "Thunderbolt"], [52, "Thunder"], [62, "WildCharge"], [70, "ThunderPunch"], [80, "Bounce"]],
      undefined,
      "Lendário de Unova do tipo Elétrico/Voador; trovões rasgam o céu."),
    sp(643, "Reshiram", ["Dragon", "Fire"], [100, 120, 100, 150, 120, 90], 3,
      [[1, "Twister"], [7, "FireSpin"], [14, "DragonBreath"], [22, "FireFang"], [32, "DragonClaw"], [42, "Outrage"], [52, "DragonPulse"], [62, "Overheat"], [70, "FireBlast"], [80, "Flamethrower"]],
      undefined,
      "Lendário de Unova do tipo Dragão/Fogo; corpo que incinera o ar."),
    sp(644, "Zekrom", ["Dragon", "Electric"], [100, 150, 120, 120, 100, 90], 3,
      [[1, "Twister"], [7, "ThunderShock"], [14, "DragonBreath"], [22, "Spark"], [32, "DragonClaw"], [42, "Outrage"], [52, "DragonPulse"], [62, "Thunder"], [70, "Thunderbolt"], [80, "WildCharge"]],
      undefined,
      "Lendário de Unova do tipo Dragão/Elétrico; cauda geradora de energia."),
    sp(645, "Landorus", ["Ground", "Flying"], [89, 125, 90, 115, 80, 101], 3,
      [[1, "MudSlap"], [7, "Peck"], [14, "MudShot"], [22, "BoneClub"], [32, "Dig"], [42, "EarthPower"], [52, "Earthquake"], [62, "Bonemerang"], [70, "Bounce"], [80, "Fly"]],
      undefined,
      "Lendário de Unova do tipo Terrestre/Voador; traz fertilidade aos campos."),
    sp(646, "Kyurem", ["Dragon", "Ice"], [125, 130, 90, 130, 90, 95], 3,
      [[1, "Twister"], [7, "PowderSnow"], [14, "DragonBreath"], [22, "IceFang"], [32, "DragonClaw"], [42, "Outrage"], [52, "DragonPulse"], [62, "Blizzard"], [70, "IceBeam"], [80, "IcePunch"]],
      undefined,
      "Lendário de Unova do tipo Dragão/Gelo; corpo incompleto que busca poder."),
    sp(647, "Keldeo", ["Water", "Fighting"], [91, 72, 90, 129, 90, 108], 3,
      [[1, "Bubble"], [7, "LowKick"], [14, "WaterPulse"], [22, "BubbleBeam"], [32, "Waterfall"], [42, "Surf"], [52, "HydroPump"], [62, "Crabhammer"], [70, "DynamicPunch"], [80, "CrossChop"]],
      undefined,
      "Mítico de Unova do tipo Água/Lutador; potro que corre sobre as águas."),
    sp(648, "Meloetta", ["Normal", "Psychic"], [100, 77, 77, 128, 128, 90], 3,
      [[1, "Scratch"], [7, "Confusion"], [14, "Swift"], [22, "Headbutt"], [32, "ExtremeSpeed"], [42, "SkullBash"], [52, "HyperBeam"], [62, "TakeDown"], [70, "HyperFang"], [80, "Slash"]],
      undefined,
      "Mítico de Unova do tipo Normal/Psíquico; canta e muda de forma ao dançar."),
    sp(649, "Genesect", ["Bug", "Steel"], [71, 120, 95, 120, 95, 99], 3,
      [[1, "LeechLife"], [7, "MetalClaw"], [14, "SilverWind"], [22, "BugBite"], [32, "XScissor"], [42, "SignalBeam"], [52, "IronTail"], [62, "FlashCannon"], [70, "XScissor"], [80, "SteelWing"]],
      undefined,
      "Mítico de Unova do tipo Inseto/Aço; caçador antigo modificado em laboratório."),
  ];
}
