/**
 * Catálogo Johto (Fase 6.4-B).
 *
 * Espécies de id 152–251 (Johto), exceto 197/208 que já existem
 * no catálogo. Dados (tipos, status-base, catchRate, evoluções) derivados
 * de PokeAPI/pokeapi (data/v2/csv). Learnsets derivados do catálogo
 * de golpes já existente (`ALL_MOVES`), com STAB por tipo e progressão de
 * poder; evolução por item usa os IDs de `evolution-items.ts`.
 */
import { EVOLUTION_ITEM_IDS } from "./evolution-items";
import type { AllMoves, EvolvesTo, PokemonSpeciesData } from "./pokedex";

type MoveKey = keyof AllMoves;
type Bases = [number, number, number, number, number, number];

const SPRITE_BASE =
  "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated";

function spriteUrl(id: number, variant?: "back" | "shiny"): string {
  return variant ? `${SPRITE_BASE}/${variant}/${id}.gif` : `${SPRITE_BASE}/${id}.gif`;
}

/** Espécies novas de Johto, em ordem de id. Chamado por `pokedex.ts` com `ALL_MOVES`. */
export function johtoRest(M: AllMoves): PokemonSpeciesData[] {
  const sp = (
    id: number, name: string, types: [string] | [string, string], bases: Bases,
    catchRate: number, moves: ReadonlyArray<readonly [number, MoveKey]>,
    evolve: ReadonlyArray<EvolvesTo> | undefined, description: string
  ): PokemonSpeciesData => ({
    id, name, types, baseHp: bases[0], baseAtk: bases[1], baseDef: bases[2],
    baseSpAtk: bases[3], baseSpDef: bases[4], baseSpd: bases[5], catchRate,
    learnset: moves.map(([level, key]) => ({ level, move: M[key] })),
    evolvesTo: evolve?.map((e) => ({ ...e })),
    frontSprite: spriteUrl(id), backSprite: spriteUrl(id, "back"),
    shinyFrontSprite: spriteUrl(id, "shiny"), description,
  });

  return [
    sp(152, "Chikorita", ["Grass"], [45, 49, 65, 49, 65, 45], 45,
      [[1, "Absorb"], [7, "QuickAttack"], [14, "VineWhip"], [22, "RazorLeaf"], [32, "MegaDrain"], [42, "PetalDance"], [52, "SeedBomb"], [62, "EnergyBall"], [70, "LeafBlade"], [80, "SolarBeam"]],
      [{ speciesId: 153, trigger: "level", level: 16 }],
      "Um Pokémon de Johto do tipo Grass, conhecido por sua presença marcante na região."),
    sp(153, "Bayleef", ["Grass"], [60, 62, 80, 63, 80, 60], 45,
      [[1, "Absorb"], [7, "QuickAttack"], [14, "VineWhip"], [22, "RazorLeaf"], [32, "MegaDrain"], [42, "PetalDance"], [52, "SeedBomb"], [62, "EnergyBall"], [70, "LeafBlade"], [80, "SolarBeam"]],
      [{ speciesId: 154, trigger: "level", level: 32 }],
      "Um Pokémon de Johto do tipo Grass, conhecido por sua presença marcante na região."),
    sp(154, "Meganium", ["Grass"], [80, 82, 100, 83, 100, 80], 45,
      [[1, "Absorb"], [7, "QuickAttack"], [14, "VineWhip"], [22, "RazorLeaf"], [32, "MegaDrain"], [42, "PetalDance"], [52, "SeedBomb"], [62, "EnergyBall"], [70, "LeafBlade"], [80, "SolarBeam"]],
      undefined,
      "Um Pokémon de Johto do tipo Grass, conhecido por sua presença marcante na região."),
    sp(155, "Cyndaquil", ["Fire"], [39, 52, 43, 60, 50, 65], 45,
      [[1, "Ember"], [7, "QuickAttack"], [14, "FireSpin"], [22, "FlameWheel"], [32, "FireFang"], [42, "FirePunch"], [52, "Flamethrower"], [62, "FireBlast"], [70, "Overheat"]],
      [{ speciesId: 156, trigger: "level", level: 14 }],
      "Um Pokémon de Johto do tipo Fire, conhecido por sua presença marcante na região."),
    sp(156, "Quilava", ["Fire"], [58, 64, 58, 80, 65, 80], 45,
      [[1, "Ember"], [7, "QuickAttack"], [14, "FireSpin"], [22, "FlameWheel"], [32, "FireFang"], [42, "FirePunch"], [52, "Flamethrower"], [62, "FireBlast"], [70, "Overheat"]],
      [{ speciesId: 157, trigger: "level", level: 36 }],
      "Um Pokémon de Johto do tipo Fire, conhecido por sua presença marcante na região."),
    sp(157, "Typhlosion", ["Fire"], [78, 84, 78, 109, 85, 100], 45,
      [[1, "Ember"], [7, "QuickAttack"], [14, "FireSpin"], [22, "FlameWheel"], [32, "FireFang"], [42, "FirePunch"], [52, "Flamethrower"], [62, "FireBlast"], [70, "Overheat"]],
      undefined,
      "Um Pokémon de Johto do tipo Fire, conhecido por sua presença marcante na região."),
    sp(158, "Totodile", ["Water"], [50, 65, 64, 44, 48, 43], 45,
      [[1, "Bubble"], [7, "QuickAttack"], [14, "WaterGun"], [22, "WaterPulse"], [32, "BubbleBeam"], [42, "Waterfall"], [52, "Surf"], [62, "Crabhammer"], [70, "HydroPump"]],
      [{ speciesId: 159, trigger: "level", level: 18 }],
      "Um Pokémon de Johto do tipo Water, conhecido por sua presença marcante na região."),
    sp(159, "Croconaw", ["Water"], [65, 80, 80, 59, 63, 58], 45,
      [[1, "Bubble"], [7, "QuickAttack"], [14, "WaterGun"], [22, "WaterPulse"], [32, "BubbleBeam"], [42, "Waterfall"], [52, "Surf"], [62, "Crabhammer"], [70, "HydroPump"]],
      [{ speciesId: 160, trigger: "level", level: 30 }],
      "Um Pokémon de Johto do tipo Water, conhecido por sua presença marcante na região."),
    sp(160, "Feraligatr", ["Water"], [85, 105, 100, 79, 83, 78], 45,
      [[1, "Bubble"], [7, "QuickAttack"], [14, "WaterGun"], [22, "WaterPulse"], [32, "BubbleBeam"], [42, "Waterfall"], [52, "Surf"], [62, "Crabhammer"], [70, "HydroPump"]],
      undefined,
      "Um Pokémon de Johto do tipo Water, conhecido por sua presença marcante na região."),
    sp(161, "Sentret", ["Normal"], [35, 46, 34, 35, 45, 20], 255,
      [[1, "Scratch"], [7, "QuickAttack"], [14, "PayDay"], [22, "Swift"], [32, "BodySlam"], [42, "Slash"], [52, "TakeDown"], [62, "HyperBeam"]],
      [{ speciesId: 162, trigger: "level", level: 15 }],
      "Um Pokémon de Johto do tipo Normal, conhecido por sua presença marcante na região."),
    sp(162, "Furret", ["Normal"], [85, 76, 64, 45, 55, 90], 90,
      [[1, "Scratch"], [7, "QuickAttack"], [14, "PayDay"], [22, "Swift"], [32, "BodySlam"], [42, "Slash"], [52, "TakeDown"], [62, "HyperBeam"]],
      undefined,
      "Um Pokémon de Johto do tipo Normal, conhecido por sua presença marcante na região."),
    sp(163, "Hoothoot", ["Normal", "Flying"], [60, 30, 30, 36, 56, 50], 255,
      [[1, "Scratch"], [7, "Gust"], [14, "QuickAttack"], [22, "Peck"], [32, "PayDay"], [42, "Swift"], [52, "WingAttack"], [62, "AerialAce"], [70, "BodySlam"], [80, "Slash"]],
      [{ speciesId: 164, trigger: "level", level: 20 }],
      "Um Pokémon de Johto do tipo Normal/Flying, conhecido por sua presença marcante na região."),
    sp(164, "Noctowl", ["Normal", "Flying"], [100, 50, 50, 86, 96, 70], 90,
      [[1, "Scratch"], [7, "Gust"], [14, "QuickAttack"], [22, "Peck"], [32, "PayDay"], [42, "Swift"], [52, "WingAttack"], [62, "AerialAce"], [70, "BodySlam"], [80, "Slash"]],
      undefined,
      "Um Pokémon de Johto do tipo Normal/Flying, conhecido por sua presença marcante na região."),
    sp(165, "Ledyba", ["Bug", "Flying"], [40, 20, 30, 40, 80, 55], 255,
      [[1, "LeechLife"], [7, "Gust"], [14, "Peck"], [22, "FuryCutter"], [32, "Twineedle"], [42, "BugBite"], [52, "SilverWind"], [62, "WingAttack"], [70, "AerialAce"], [80, "SignalBeam"]],
      [{ speciesId: 166, trigger: "level", level: 18 }],
      "Um Pokémon de Johto do tipo Bug/Flying, conhecido por sua presença marcante na região."),
    sp(166, "Ledian", ["Bug", "Flying"], [55, 35, 50, 55, 110, 85], 90,
      [[1, "LeechLife"], [7, "Gust"], [14, "Peck"], [22, "FuryCutter"], [32, "Twineedle"], [42, "BugBite"], [52, "SilverWind"], [62, "WingAttack"], [70, "AerialAce"], [80, "SignalBeam"]],
      undefined,
      "Um Pokémon de Johto do tipo Bug/Flying, conhecido por sua presença marcante na região."),
    sp(167, "Spinarak", ["Bug", "Poison"], [40, 60, 40, 40, 40, 30], 255,
      [[1, "LeechLife"], [7, "PoisonSting"], [14, "FuryCutter"], [22, "Acid"], [32, "Twineedle"], [42, "BugBite"], [52, "SilverWind"], [62, "PoisonFang"], [70, "Sludge"], [80, "SignalBeam"]],
      [{ speciesId: 168, trigger: "level", level: 22 }],
      "Um Pokémon de Johto do tipo Bug/Poison, conhecido por sua presença marcante na região."),
    sp(168, "Ariados", ["Bug", "Poison"], [70, 90, 70, 60, 70, 40], 90,
      [[1, "LeechLife"], [7, "PoisonSting"], [14, "FuryCutter"], [22, "Acid"], [32, "Twineedle"], [42, "BugBite"], [52, "SilverWind"], [62, "PoisonFang"], [70, "Sludge"], [80, "SignalBeam"]],
      undefined,
      "Um Pokémon de Johto do tipo Bug/Poison, conhecido por sua presença marcante na região."),
    sp(169, "Crobat", ["Poison", "Flying"], [85, 90, 80, 70, 80, 130], 90,
      [[1, "PoisonSting"], [7, "Gust"], [14, "Peck"], [22, "Acid"], [32, "WingAttack"], [42, "AerialAce"], [52, "PoisonFang"], [62, "Sludge"], [70, "AirSlash"], [80, "PoisonJab"]],
      undefined,
      "Um Pokémon de Johto do tipo Poison/Flying, conhecido por sua presença marcante na região."),
    sp(170, "Chinchou", ["Water", "Electric"], [75, 38, 38, 56, 56, 67], 190,
      [[1, "Bubble"], [7, "ThunderShock"], [14, "WaterGun"], [22, "WaterPulse"], [32, "ShockWave"], [42, "BubbleBeam"], [52, "Spark"], [62, "ThunderPunch"], [70, "Waterfall"], [80, "Discharge"]],
      [{ speciesId: 171, trigger: "level", level: 27 }],
      "Um Pokémon de Johto do tipo Water/Electric, conhecido por sua presença marcante na região."),
    sp(171, "Lanturn", ["Water", "Electric"], [125, 58, 58, 76, 76, 67], 75,
      [[1, "Bubble"], [7, "ThunderShock"], [14, "WaterGun"], [22, "WaterPulse"], [32, "ShockWave"], [42, "BubbleBeam"], [52, "Spark"], [62, "ThunderPunch"], [70, "Waterfall"], [80, "Discharge"]],
      undefined,
      "Um Pokémon de Johto do tipo Water/Electric, conhecido por sua presença marcante na região."),
    sp(172, "Pichu", ["Electric"], [20, 40, 15, 35, 35, 60], 190,
      [[1, "ThunderShock"], [7, "QuickAttack"], [14, "ShockWave"], [22, "Spark"], [32, "ThunderPunch"], [42, "Discharge"], [52, "WildCharge"], [62, "Thunderbolt"], [70, "Thunder"]],
      undefined,
      "Um Pokémon de Johto do tipo Electric, conhecido por sua presença marcante na região."),
    sp(173, "Cleffa", ["Fairy"], [50, 25, 28, 45, 55, 15], 150,
      [[1, "FairyWind"], [7, "QuickAttack"], [14, "DisarmingVoice"], [22, "DrainingKiss"], [32, "DazzlingGleam"], [42, "PlayRough"], [52, "Moonblast"]],
      undefined,
      "Um Pokémon de Johto do tipo Fairy, conhecido por sua presença marcante na região."),
    sp(174, "Igglybuff", ["Normal", "Fairy"], [90, 30, 15, 40, 20, 15], 170,
      [[1, "Scratch"], [7, "FairyWind"], [14, "QuickAttack"], [22, "PayDay"], [32, "DisarmingVoice"], [42, "DrainingKiss"], [52, "Swift"], [62, "BodySlam"], [70, "Slash"], [80, "DazzlingGleam"]],
      undefined,
      "Um Pokémon de Johto do tipo Normal/Fairy, conhecido por sua presença marcante na região."),
    sp(175, "Togepi", ["Fairy"], [35, 20, 65, 40, 65, 20], 190,
      [[1, "FairyWind"], [7, "QuickAttack"], [14, "DisarmingVoice"], [22, "DrainingKiss"], [32, "DazzlingGleam"], [42, "PlayRough"], [52, "Moonblast"]],
      [{ speciesId: 176, trigger: "level", level: 20 }],
      "Um Pokémon de Johto do tipo Fairy, conhecido por sua presença marcante na região."),
    sp(176, "Togetic", ["Fairy", "Flying"], [55, 40, 85, 80, 105, 40], 75,
      [[1, "FairyWind"], [7, "Gust"], [14, "Peck"], [22, "DisarmingVoice"], [32, "DrainingKiss"], [42, "WingAttack"], [52, "AerialAce"], [62, "AirSlash"], [70, "DazzlingGleam"], [80, "DrillPeck"]],
      [{ speciesId: 468, trigger: "item", itemId: EVOLUTION_ITEM_IDS.shinyStone }], // 6.4-D: Togekiss
      "Um Pokémon de Johto do tipo Fairy/Flying, conhecido por sua presença marcante na região."),
    sp(177, "Natu", ["Psychic", "Flying"], [40, 50, 45, 70, 45, 70], 190,
      [[1, "Confusion"], [7, "Gust"], [14, "Peck"], [22, "WingAttack"], [32, "AerialAce"], [42, "Psybeam"], [52, "AirSlash"], [62, "FutureSight"], [70, "ZenHeadbutt"], [80, "DrillPeck"]],
      [{ speciesId: 178, trigger: "level", level: 25 }],
      "Um Pokémon de Johto do tipo Psychic/Flying, conhecido por sua presença marcante na região."),
    sp(178, "Xatu", ["Psychic", "Flying"], [65, 75, 70, 95, 70, 95], 75,
      [[1, "Confusion"], [7, "Gust"], [14, "Peck"], [22, "WingAttack"], [32, "AerialAce"], [42, "Psybeam"], [52, "AirSlash"], [62, "FutureSight"], [70, "ZenHeadbutt"], [80, "DrillPeck"]],
      undefined,
      "Um Pokémon de Johto do tipo Psychic/Flying, conhecido por sua presença marcante na região."),
    sp(179, "Mareep", ["Electric"], [55, 40, 40, 65, 45, 35], 235,
      [[1, "ThunderShock"], [7, "QuickAttack"], [14, "ShockWave"], [22, "Spark"], [32, "ThunderPunch"], [42, "Discharge"], [52, "WildCharge"], [62, "Thunderbolt"], [70, "Thunder"]],
      [{ speciesId: 180, trigger: "level", level: 15 }],
      "Um Pokémon de Johto do tipo Electric, conhecido por sua presença marcante na região."),
    sp(180, "Flaaffy", ["Electric"], [70, 55, 55, 80, 60, 45], 120,
      [[1, "ThunderShock"], [7, "QuickAttack"], [14, "ShockWave"], [22, "Spark"], [32, "ThunderPunch"], [42, "Discharge"], [52, "WildCharge"], [62, "Thunderbolt"], [70, "Thunder"]],
      [{ speciesId: 181, trigger: "level", level: 30 }],
      "Um Pokémon de Johto do tipo Electric, conhecido por sua presença marcante na região."),
    sp(181, "Ampharos", ["Electric"], [90, 75, 85, 115, 90, 55], 45,
      [[1, "ThunderShock"], [7, "QuickAttack"], [14, "ShockWave"], [22, "Spark"], [32, "ThunderPunch"], [42, "Discharge"], [52, "WildCharge"], [62, "Thunderbolt"], [70, "Thunder"]],
      undefined,
      "Um Pokémon de Johto do tipo Electric, conhecido por sua presença marcante na região."),
    sp(182, "Bellossom", ["Grass"], [75, 80, 95, 90, 100, 50], 45,
      [[1, "Absorb"], [7, "QuickAttack"], [14, "VineWhip"], [22, "RazorLeaf"], [32, "MegaDrain"], [42, "PetalDance"], [52, "SeedBomb"], [62, "EnergyBall"], [70, "LeafBlade"], [80, "SolarBeam"]],
      undefined,
      "Um Pokémon de Johto do tipo Grass, conhecido por sua presença marcante na região."),
    sp(183, "Marill", ["Water", "Fairy"], [70, 20, 50, 20, 50, 40], 190,
      [[1, "Bubble"], [7, "FairyWind"], [14, "WaterGun"], [22, "DisarmingVoice"], [32, "DrainingKiss"], [42, "WaterPulse"], [52, "BubbleBeam"], [62, "Waterfall"], [70, "DazzlingGleam"], [80, "Surf"]],
      [{ speciesId: 184, trigger: "level", level: 18 }],
      "Um Pokémon de Johto do tipo Water/Fairy, conhecido por sua presença marcante na região."),
    sp(184, "Azumarill", ["Water", "Fairy"], [100, 50, 80, 60, 80, 50], 75,
      [[1, "Bubble"], [7, "FairyWind"], [14, "WaterGun"], [22, "DisarmingVoice"], [32, "DrainingKiss"], [42, "WaterPulse"], [52, "BubbleBeam"], [62, "Waterfall"], [70, "DazzlingGleam"], [80, "Surf"]],
      undefined,
      "Um Pokémon de Johto do tipo Water/Fairy, conhecido por sua presença marcante na região."),
    sp(185, "Sudowoodo", ["Rock"], [70, 100, 115, 30, 65, 30], 65,
      [[1, "RockThrow"], [7, "QuickAttack"], [14, "RockTomb"], [22, "AncientPower"], [32, "RockSlide"], [42, "StoneEdge"]],
      undefined,
      "Um Pokémon de Johto do tipo Rock, conhecido por sua presença marcante na região."),
    sp(186, "Politoed", ["Water"], [90, 75, 75, 90, 100, 70], 45,
      [[1, "Bubble"], [7, "QuickAttack"], [14, "WaterGun"], [22, "WaterPulse"], [32, "BubbleBeam"], [42, "Waterfall"], [52, "Surf"], [62, "Crabhammer"], [70, "HydroPump"]],
      undefined,
      "Um Pokémon de Johto do tipo Water, conhecido por sua presença marcante na região."),
    sp(187, "Hoppip", ["Grass", "Flying"], [35, 35, 40, 35, 55, 50], 255,
      [[1, "Absorb"], [7, "Gust"], [14, "VineWhip"], [22, "RazorLeaf"], [32, "Peck"], [42, "MegaDrain"], [52, "WingAttack"], [62, "AerialAce"], [70, "PetalDance"], [80, "AirSlash"]],
      [{ speciesId: 188, trigger: "level", level: 18 }],
      "Um Pokémon de Johto do tipo Grass/Flying, conhecido por sua presença marcante na região."),
    sp(188, "Skiploom", ["Grass", "Flying"], [55, 45, 50, 45, 65, 80], 120,
      [[1, "Absorb"], [7, "Gust"], [14, "VineWhip"], [22, "RazorLeaf"], [32, "Peck"], [42, "MegaDrain"], [52, "WingAttack"], [62, "AerialAce"], [70, "PetalDance"], [80, "AirSlash"]],
      [{ speciesId: 189, trigger: "level", level: 27 }],
      "Um Pokémon de Johto do tipo Grass/Flying, conhecido por sua presença marcante na região."),
    sp(189, "Jumpluff", ["Grass", "Flying"], [75, 55, 70, 55, 95, 110], 45,
      [[1, "Absorb"], [7, "Gust"], [14, "VineWhip"], [22, "RazorLeaf"], [32, "Peck"], [42, "MegaDrain"], [52, "WingAttack"], [62, "AerialAce"], [70, "PetalDance"], [80, "AirSlash"]],
      undefined,
      "Um Pokémon de Johto do tipo Grass/Flying, conhecido por sua presença marcante na região."),
    sp(190, "Aipom", ["Normal"], [55, 70, 55, 40, 55, 85], 45,
      [[1, "Scratch"], [7, "QuickAttack"], [14, "PayDay"], [22, "Swift"], [32, "BodySlam"], [42, "Slash"], [52, "TakeDown"], [62, "HyperBeam"]],
      [{ speciesId: 424, trigger: "level", level: 32 }], // 6.4-D: Ambipom (conhecer Golpe Duplo → nível canônico)
      "Um Pokémon de Johto do tipo Normal, conhecido por sua presença marcante na região."),
    sp(191, "Sunkern", ["Grass"], [30, 30, 30, 30, 30, 30], 235,
      [[1, "Absorb"], [7, "QuickAttack"], [14, "VineWhip"], [22, "RazorLeaf"], [32, "MegaDrain"], [42, "PetalDance"], [52, "SeedBomb"], [62, "EnergyBall"], [70, "LeafBlade"], [80, "SolarBeam"]],
      [{ speciesId: 192, trigger: "item", itemId: EVOLUTION_ITEM_IDS.sunStone }],
      "Um Pokémon de Johto do tipo Grass, conhecido por sua presença marcante na região."),
    sp(192, "Sunflora", ["Grass"], [75, 75, 55, 105, 85, 30], 120,
      [[1, "Absorb"], [7, "QuickAttack"], [14, "VineWhip"], [22, "RazorLeaf"], [32, "MegaDrain"], [42, "PetalDance"], [52, "SeedBomb"], [62, "EnergyBall"], [70, "LeafBlade"], [80, "SolarBeam"]],
      undefined,
      "Um Pokémon de Johto do tipo Grass, conhecido por sua presença marcante na região."),
    sp(193, "Yanma", ["Bug", "Flying"], [65, 65, 45, 75, 45, 95], 75,
      [[1, "LeechLife"], [7, "Gust"], [14, "Peck"], [22, "FuryCutter"], [32, "Twineedle"], [42, "BugBite"], [52, "SilverWind"], [62, "WingAttack"], [70, "AerialAce"], [80, "SignalBeam"]],
      [{ speciesId: 469, trigger: "level", level: 33 }], // 6.4-D: Yanmega (conhecer Poder Antigo → nível canônico)
      "Um Pokémon de Johto do tipo Bug/Flying, conhecido por sua presença marcante na região."),
    sp(194, "Wooper", ["Water", "Ground"], [55, 45, 45, 25, 25, 15], 255,
      [[1, "Bubble"], [7, "MudSlap"], [14, "WaterGun"], [22, "MudShot"], [32, "WaterPulse"], [42, "BubbleBeam"], [52, "BoneClub"], [62, "Waterfall"], [70, "Dig"], [80, "Bonemerang"]],
      [{ speciesId: 195, trigger: "level", level: 20 }],
      "Um Pokémon de Johto do tipo Water/Ground, conhecido por sua presença marcante na região."),
    sp(195, "Quagsire", ["Water", "Ground"], [95, 85, 85, 65, 65, 35], 90,
      [[1, "Bubble"], [7, "MudSlap"], [14, "WaterGun"], [22, "MudShot"], [32, "WaterPulse"], [42, "BubbleBeam"], [52, "BoneClub"], [62, "Waterfall"], [70, "Dig"], [80, "Bonemerang"]],
      undefined,
      "Um Pokémon de Johto do tipo Water/Ground, conhecido por sua presença marcante na região."),
    sp(196, "Espeon", ["Psychic"], [65, 65, 60, 130, 95, 110], 45,
      [[1, "Confusion"], [7, "QuickAttack"], [14, "Psybeam"], [22, "FutureSight"], [32, "ZenHeadbutt"], [42, "Psychic"]],
      undefined,
      "Um Pokémon de Johto do tipo Psychic, conhecido por sua presença marcante na região."),
    sp(198, "Murkrow", ["Dark", "Flying"], [60, 85, 42, 85, 42, 91], 30,
      [[1, "Pursuit"], [7, "Gust"], [14, "Peck"], [22, "FeintAttack"], [32, "Bite"], [42, "WingAttack"], [52, "AerialAce"], [62, "NightSlash"], [70, "AirSlash"], [80, "Crunch"]],
      [{ speciesId: 430, trigger: "item", itemId: EVOLUTION_ITEM_IDS.duskStone }], // 6.4-D: Honchkrow
      "Um Pokémon de Johto do tipo Dark/Flying, conhecido por sua presença marcante na região."),
    sp(199, "Slowking", ["Water", "Psychic"], [95, 75, 80, 100, 110, 30], 70,
      [[1, "Bubble"], [7, "Confusion"], [14, "WaterGun"], [22, "WaterPulse"], [32, "BubbleBeam"], [42, "Psybeam"], [52, "Waterfall"], [62, "FutureSight"], [70, "ZenHeadbutt"], [80, "Surf"]],
      undefined,
      "Um Pokémon de Johto do tipo Water/Psychic, conhecido por sua presença marcante na região."),
    sp(200, "Misdreavus", ["Ghost"], [60, 60, 60, 85, 85, 85], 45,
      [[1, "Astonish"], [7, "QuickAttack"], [14, "Lick"], [22, "ShadowSneak"], [32, "ShadowBall"]],
      [{ speciesId: 429, trigger: "item", itemId: EVOLUTION_ITEM_IDS.duskStone }], // 6.4-D: Mismagius
      "Um Pokémon de Johto do tipo Ghost, conhecido por sua presença marcante na região."),
    sp(201, "Unown", ["Psychic"], [48, 72, 48, 72, 48, 48], 225,
      [[1, "Confusion"], [7, "QuickAttack"], [14, "Psybeam"], [22, "FutureSight"], [32, "ZenHeadbutt"], [42, "Psychic"]],
      undefined,
      "Um Pokémon de Johto do tipo Psychic, conhecido por sua presença marcante na região."),
    sp(202, "Wobbuffet", ["Psychic"], [190, 33, 58, 33, 58, 33], 45,
      [[1, "Confusion"], [7, "QuickAttack"], [14, "Psybeam"], [22, "FutureSight"], [32, "ZenHeadbutt"], [42, "Psychic"]],
      undefined,
      "Um Pokémon de Johto do tipo Psychic, conhecido por sua presença marcante na região."),
    sp(203, "Girafarig", ["Normal", "Psychic"], [70, 80, 65, 90, 65, 85], 60,
      [[1, "Scratch"], [7, "Confusion"], [14, "QuickAttack"], [22, "PayDay"], [32, "Swift"], [42, "Psybeam"], [52, "BodySlam"], [62, "Slash"], [70, "FutureSight"], [80, "ZenHeadbutt"]],
      undefined,
      "Um Pokémon de Johto do tipo Normal/Psychic, conhecido por sua presença marcante na região."),
    sp(204, "Pineco", ["Bug"], [50, 65, 90, 35, 35, 15], 190,
      [[1, "LeechLife"], [7, "QuickAttack"], [14, "FuryCutter"], [22, "Twineedle"], [32, "BugBite"], [42, "SilverWind"], [52, "SignalBeam"], [62, "XScissor"]],
      [{ speciesId: 205, trigger: "level", level: 31 }],
      "Um Pokémon de Johto do tipo Bug, conhecido por sua presença marcante na região."),
    sp(205, "Forretress", ["Bug", "Steel"], [75, 90, 140, 60, 60, 40], 75,
      [[1, "LeechLife"], [7, "MetalClaw"], [14, "FuryCutter"], [22, "Twineedle"], [32, "BugBite"], [42, "SilverWind"], [52, "MagnetBomb"], [62, "SteelWing"], [70, "SignalBeam"], [80, "XScissor"]],
      undefined,
      "Um Pokémon de Johto do tipo Bug/Steel, conhecido por sua presença marcante na região."),
    sp(206, "Dunsparce", ["Normal"], [100, 70, 70, 65, 65, 45], 190,
      [[1, "Scratch"], [7, "QuickAttack"], [14, "PayDay"], [22, "Swift"], [32, "BodySlam"], [42, "Slash"], [52, "TakeDown"], [62, "HyperBeam"]],
      undefined,
      "Um Pokémon de Johto do tipo Normal, conhecido por sua presença marcante na região."),
    sp(207, "Gligar", ["Ground", "Flying"], [65, 75, 105, 35, 65, 85], 60,
      [[1, "MudSlap"], [7, "Gust"], [14, "Peck"], [22, "MudShot"], [32, "WingAttack"], [42, "AerialAce"], [52, "BoneClub"], [62, "AirSlash"], [70, "Dig"], [80, "DrillPeck"]],
      [{ speciesId: 472, trigger: "item", itemId: EVOLUTION_ITEM_IDS.razorFang }], // 6.4-D: Gliscor
      "Um Pokémon de Johto do tipo Ground/Flying, conhecido por sua presença marcante na região."),
    sp(209, "Snubbull", ["Fairy"], [60, 80, 50, 40, 40, 30], 190,
      [[1, "FairyWind"], [7, "QuickAttack"], [14, "DisarmingVoice"], [22, "DrainingKiss"], [32, "DazzlingGleam"], [42, "PlayRough"], [52, "Moonblast"]],
      [{ speciesId: 210, trigger: "level", level: 23 }],
      "Um Pokémon de Johto do tipo Fairy, conhecido por sua presença marcante na região."),
    sp(210, "Granbull", ["Fairy"], [90, 120, 75, 60, 60, 45], 75,
      [[1, "FairyWind"], [7, "QuickAttack"], [14, "DisarmingVoice"], [22, "DrainingKiss"], [32, "DazzlingGleam"], [42, "PlayRough"], [52, "Moonblast"]],
      undefined,
      "Um Pokémon de Johto do tipo Fairy, conhecido por sua presença marcante na região."),
    sp(211, "Qwilfish", ["Water", "Poison"], [65, 95, 85, 55, 55, 85], 45,
      [[1, "Bubble"], [7, "PoisonSting"], [14, "WaterGun"], [22, "Acid"], [32, "WaterPulse"], [42, "BubbleBeam"], [52, "PoisonFang"], [62, "Sludge"], [70, "Waterfall"], [80, "PoisonJab"]],
      undefined,
      "Um Pokémon de Johto do tipo Water/Poison, conhecido por sua presença marcante na região."),
    sp(212, "Scizor", ["Bug", "Steel"], [70, 130, 100, 55, 80, 65], 25,
      [[1, "LeechLife"], [7, "MetalClaw"], [14, "FuryCutter"], [22, "Twineedle"], [32, "BugBite"], [42, "SilverWind"], [52, "MagnetBomb"], [62, "SteelWing"], [70, "SignalBeam"], [80, "XScissor"]],
      undefined,
      "Um Pokémon de Johto do tipo Bug/Steel, conhecido por sua presença marcante na região."),
    sp(213, "Shuckle", ["Bug", "Rock"], [20, 10, 230, 10, 230, 5], 190,
      [[1, "LeechLife"], [7, "RockThrow"], [14, "FuryCutter"], [22, "Twineedle"], [32, "RockTomb"], [42, "BugBite"], [52, "SilverWind"], [62, "AncientPower"], [70, "SignalBeam"], [80, "RockSlide"]],
      undefined,
      "Um Pokémon de Johto do tipo Bug/Rock, conhecido por sua presença marcante na região."),
    sp(214, "Heracross", ["Bug", "Fighting"], [80, 125, 75, 40, 95, 85], 45,
      [[1, "LeechLife"], [7, "MachPunch"], [14, "FuryCutter"], [22, "Twineedle"], [32, "LowKick"], [42, "KarateChop"], [52, "BugBite"], [62, "SignalBeam"], [70, "SilverWind"], [80, "XScissor"]],
      undefined,
      "Um Pokémon de Johto do tipo Bug/Fighting, conhecido por sua presença marcante na região."),
    sp(215, "Sneasel", ["Dark", "Ice"], [55, 95, 55, 35, 75, 115], 60,
      [[1, "Pursuit"], [7, "PowderSnow"], [14, "IceShard"], [22, "IcyWind"], [32, "FeintAttack"], [42, "Bite"], [52, "IceFang"], [62, "AuroraBeam"], [70, "NightSlash"], [80, "IcePunch"]],
      [{ speciesId: 461, trigger: "item", itemId: EVOLUTION_ITEM_IDS.razorClaw }], // 6.4-D: Weavile
      "Um Pokémon de Johto do tipo Dark/Ice, conhecido por sua presença marcante na região."),
    sp(216, "Teddiursa", ["Normal"], [60, 80, 50, 50, 50, 40], 120,
      [[1, "Scratch"], [7, "QuickAttack"], [14, "PayDay"], [22, "Swift"], [32, "BodySlam"], [42, "Slash"], [52, "TakeDown"], [62, "HyperBeam"]],
      [{ speciesId: 217, trigger: "level", level: 30 }],
      "Um Pokémon de Johto do tipo Normal, conhecido por sua presença marcante na região."),
    sp(217, "Ursaring", ["Normal"], [90, 130, 75, 75, 75, 55], 60,
      [[1, "Scratch"], [7, "QuickAttack"], [14, "PayDay"], [22, "Swift"], [32, "BodySlam"], [42, "Slash"], [52, "TakeDown"], [62, "HyperBeam"]],
      undefined,
      "Um Pokémon de Johto do tipo Normal, conhecido por sua presença marcante na região."),
    sp(218, "Slugma", ["Fire"], [40, 40, 40, 70, 40, 20], 190,
      [[1, "Ember"], [7, "QuickAttack"], [14, "FireSpin"], [22, "FlameWheel"], [32, "FireFang"], [42, "FirePunch"], [52, "Flamethrower"], [62, "FireBlast"], [70, "Overheat"]],
      [{ speciesId: 219, trigger: "level", level: 38 }],
      "Um Pokémon de Johto do tipo Fire, conhecido por sua presença marcante na região."),
    sp(219, "Magcargo", ["Fire", "Rock"], [60, 50, 120, 90, 80, 30], 75,
      [[1, "Ember"], [7, "RockThrow"], [14, "FireSpin"], [22, "RockTomb"], [32, "FlameWheel"], [42, "AncientPower"], [52, "FireFang"], [62, "FirePunch"], [70, "RockSlide"], [80, "Flamethrower"]],
      undefined,
      "Um Pokémon de Johto do tipo Fire/Rock, conhecido por sua presença marcante na região."),
    sp(220, "Swinub", ["Ice", "Ground"], [50, 50, 40, 30, 30, 50], 225,
      [[1, "PowderSnow"], [7, "MudSlap"], [14, "IceShard"], [22, "IcyWind"], [32, "MudShot"], [42, "IceFang"], [52, "AuroraBeam"], [62, "BoneClub"], [70, "IcePunch"], [80, "Dig"]],
      [{ speciesId: 221, trigger: "level", level: 33 }],
      "Um Pokémon de Johto do tipo Ice/Ground, conhecido por sua presença marcante na região."),
    sp(221, "Piloswine", ["Ice", "Ground"], [100, 100, 80, 60, 60, 50], 75,
      [[1, "PowderSnow"], [7, "MudSlap"], [14, "IceShard"], [22, "IcyWind"], [32, "MudShot"], [42, "IceFang"], [52, "AuroraBeam"], [62, "BoneClub"], [70, "IcePunch"], [80, "Dig"]],
      [{ speciesId: 473, trigger: "level", level: 45 }], // 6.4-D: Mamoswine (conhecer Poder Antigo; acima do 33 de Swinub→Piloswine para a cadeia só subir)
      "Um Pokémon de Johto do tipo Ice/Ground, conhecido por sua presença marcante na região."),
    sp(222, "Corsola", ["Water", "Rock"], [65, 55, 95, 65, 95, 35], 60,
      [[1, "Bubble"], [7, "RockThrow"], [14, "WaterGun"], [22, "RockTomb"], [32, "WaterPulse"], [42, "AncientPower"], [52, "BubbleBeam"], [62, "RockSlide"], [70, "Waterfall"], [80, "Surf"]],
      undefined,
      "Um Pokémon de Johto do tipo Water/Rock, conhecido por sua presença marcante na região."),
    sp(223, "Remoraid", ["Water"], [35, 65, 35, 65, 35, 65], 190,
      [[1, "Bubble"], [7, "QuickAttack"], [14, "WaterGun"], [22, "WaterPulse"], [32, "BubbleBeam"], [42, "Waterfall"], [52, "Surf"], [62, "Crabhammer"], [70, "HydroPump"]],
      [{ speciesId: 224, trigger: "level", level: 25 }],
      "Um Pokémon de Johto do tipo Water, conhecido por sua presença marcante na região."),
    sp(224, "Octillery", ["Water"], [75, 105, 75, 105, 75, 45], 75,
      [[1, "Bubble"], [7, "QuickAttack"], [14, "WaterGun"], [22, "WaterPulse"], [32, "BubbleBeam"], [42, "Waterfall"], [52, "Surf"], [62, "Crabhammer"], [70, "HydroPump"]],
      undefined,
      "Um Pokémon de Johto do tipo Water, conhecido por sua presença marcante na região."),
    sp(225, "Delibird", ["Ice", "Flying"], [45, 55, 45, 65, 45, 75], 45,
      [[1, "PowderSnow"], [7, "Gust"], [14, "IceShard"], [22, "Peck"], [32, "IcyWind"], [42, "WingAttack"], [52, "AerialAce"], [62, "IceFang"], [70, "AuroraBeam"], [80, "IcePunch"]],
      undefined,
      "Um Pokémon de Johto do tipo Ice/Flying, conhecido por sua presença marcante na região."),
    sp(226, "Mantine", ["Water", "Flying"], [85, 40, 70, 80, 140, 70], 25,
      [[1, "Bubble"], [7, "Gust"], [14, "Peck"], [22, "WaterGun"], [32, "WaterPulse"], [42, "WingAttack"], [52, "AerialAce"], [62, "BubbleBeam"], [70, "AirSlash"], [80, "Waterfall"]],
      undefined,
      "Um Pokémon de Johto do tipo Water/Flying, conhecido por sua presença marcante na região."),
    sp(227, "Skarmory", ["Steel", "Flying"], [65, 80, 140, 40, 70, 70], 25,
      [[1, "MetalClaw"], [7, "Gust"], [14, "Peck"], [22, "MagnetBomb"], [32, "WingAttack"], [42, "AerialAce"], [52, "SteelWing"], [62, "AirSlash"], [70, "IronHead"], [80, "FlashCannon"]],
      undefined,
      "Um Pokémon de Johto do tipo Steel/Flying, conhecido por sua presença marcante na região."),
    sp(228, "Houndour", ["Dark", "Fire"], [45, 60, 30, 80, 50, 65], 120,
      [[1, "Pursuit"], [7, "Ember"], [14, "FireSpin"], [22, "FeintAttack"], [32, "Bite"], [42, "FlameWheel"], [52, "FireFang"], [62, "NightSlash"], [70, "FirePunch"], [80, "Crunch"]],
      [{ speciesId: 229, trigger: "level", level: 24 }],
      "Um Pokémon de Johto do tipo Dark/Fire, conhecido por sua presença marcante na região."),
    sp(229, "Houndoom", ["Dark", "Fire"], [75, 90, 50, 110, 80, 95], 45,
      [[1, "Pursuit"], [7, "Ember"], [14, "FireSpin"], [22, "FeintAttack"], [32, "Bite"], [42, "FlameWheel"], [52, "FireFang"], [62, "NightSlash"], [70, "FirePunch"], [80, "Crunch"]],
      undefined,
      "Um Pokémon de Johto do tipo Dark/Fire, conhecido por sua presença marcante na região."),
    sp(230, "Kingdra", ["Water", "Dragon"], [75, 95, 95, 95, 95, 85], 45,
      [[1, "Bubble"], [7, "Twister"], [14, "WaterGun"], [22, "WaterPulse"], [32, "DragonBreath"], [42, "BubbleBeam"], [52, "Waterfall"], [62, "DragonClaw"], [70, "DragonPulse"], [80, "Surf"]],
      undefined,
      "Um Pokémon de Johto do tipo Water/Dragon, conhecido por sua presença marcante na região."),
    sp(231, "Phanpy", ["Ground"], [90, 60, 60, 40, 40, 40], 120,
      [[1, "MudSlap"], [7, "QuickAttack"], [14, "MudShot"], [22, "BoneClub"], [32, "Dig"], [42, "Bonemerang"], [52, "EarthPower"], [62, "Earthquake"]],
      [{ speciesId: 232, trigger: "level", level: 25 }],
      "Um Pokémon de Johto do tipo Ground, conhecido por sua presença marcante na região."),
    sp(232, "Donphan", ["Ground"], [90, 120, 120, 60, 60, 50], 60,
      [[1, "MudSlap"], [7, "QuickAttack"], [14, "MudShot"], [22, "BoneClub"], [32, "Dig"], [42, "Bonemerang"], [52, "EarthPower"], [62, "Earthquake"]],
      undefined,
      "Um Pokémon de Johto do tipo Ground, conhecido por sua presença marcante na região."),
    sp(233, "Porygon2", ["Normal"], [85, 80, 90, 105, 95, 60], 45,
      [[1, "Scratch"], [7, "QuickAttack"], [14, "PayDay"], [22, "Swift"], [32, "BodySlam"], [42, "Slash"], [52, "TakeDown"], [62, "HyperBeam"]],
      [{ speciesId: 474, trigger: "item", itemId: EVOLUTION_ITEM_IDS.dubiousDisc }], // 6.4-D: Porygon-Z
      "Um Pokémon de Johto do tipo Normal, conhecido por sua presença marcante na região."),
    sp(234, "Stantler", ["Normal"], [73, 95, 62, 85, 65, 85], 45,
      [[1, "Scratch"], [7, "QuickAttack"], [14, "PayDay"], [22, "Swift"], [32, "BodySlam"], [42, "Slash"], [52, "TakeDown"], [62, "HyperBeam"]],
      undefined,
      "Um Pokémon de Johto do tipo Normal, conhecido por sua presença marcante na região."),
    sp(235, "Smeargle", ["Normal"], [55, 20, 35, 20, 45, 75], 45,
      [[1, "Scratch"], [7, "QuickAttack"], [14, "PayDay"], [22, "Swift"], [32, "BodySlam"], [42, "Slash"], [52, "TakeDown"], [62, "HyperBeam"]],
      undefined,
      "Um Pokémon de Johto do tipo Normal, conhecido por sua presença marcante na região."),
    sp(236, "Tyrogue", ["Fighting"], [35, 35, 35, 35, 35, 35], 75,
      [[1, "MachPunch"], [7, "QuickAttack"], [14, "LowKick"], [22, "KarateChop"], [32, "RollingKick"], [42, "VitalThrow"], [52, "BrickBreak"], [62, "Submission"], [70, "SkyUppercut"], [80, "HighJumpKick"]],
      [{ speciesId: 237, trigger: "level", level: 20 }],
      "Um Pokémon de Johto do tipo Fighting, conhecido por sua presença marcante na região."),
    sp(237, "Hitmontop", ["Fighting"], [50, 95, 95, 35, 110, 70], 45,
      [[1, "MachPunch"], [7, "QuickAttack"], [14, "LowKick"], [22, "KarateChop"], [32, "RollingKick"], [42, "VitalThrow"], [52, "BrickBreak"], [62, "Submission"], [70, "SkyUppercut"], [80, "HighJumpKick"]],
      undefined,
      "Um Pokémon de Johto do tipo Fighting, conhecido por sua presença marcante na região."),
    sp(238, "Smoochum", ["Ice", "Psychic"], [45, 30, 15, 85, 65, 65], 45,
      [[1, "PowderSnow"], [7, "Confusion"], [14, "IceShard"], [22, "IcyWind"], [32, "IceFang"], [42, "AuroraBeam"], [52, "Psybeam"], [62, "IcePunch"], [70, "FutureSight"], [80, "ZenHeadbutt"]],
      undefined,
      "Um Pokémon de Johto do tipo Ice/Psychic, conhecido por sua presença marcante na região."),
    sp(239, "Elekid", ["Electric"], [45, 63, 37, 65, 55, 95], 45,
      [[1, "ThunderShock"], [7, "QuickAttack"], [14, "ShockWave"], [22, "Spark"], [32, "ThunderPunch"], [42, "Discharge"], [52, "WildCharge"], [62, "Thunderbolt"], [70, "Thunder"]],
      undefined,
      "Um Pokémon de Johto do tipo Electric, conhecido por sua presença marcante na região."),
    sp(240, "Magby", ["Fire"], [45, 75, 37, 70, 55, 83], 45,
      [[1, "Ember"], [7, "QuickAttack"], [14, "FireSpin"], [22, "FlameWheel"], [32, "FireFang"], [42, "FirePunch"], [52, "Flamethrower"], [62, "FireBlast"], [70, "Overheat"]],
      undefined,
      "Um Pokémon de Johto do tipo Fire, conhecido por sua presença marcante na região."),
    sp(241, "Miltank", ["Normal"], [95, 80, 105, 40, 70, 100], 45,
      [[1, "Scratch"], [7, "QuickAttack"], [14, "PayDay"], [22, "Swift"], [32, "BodySlam"], [42, "Slash"], [52, "TakeDown"], [62, "HyperBeam"]],
      undefined,
      "Um Pokémon de Johto do tipo Normal, conhecido por sua presença marcante na região."),
    sp(242, "Blissey", ["Normal"], [255, 10, 10, 75, 135, 55], 30,
      [[1, "Scratch"], [7, "QuickAttack"], [14, "PayDay"], [22, "Swift"], [32, "BodySlam"], [42, "Slash"], [52, "TakeDown"], [62, "HyperBeam"]],
      undefined,
      "Um Pokémon de Johto do tipo Normal, conhecido por sua presença marcante na região."),
    sp(243, "Raikou", ["Electric"], [90, 85, 75, 115, 100, 115], 3,
      [[1, "ThunderShock"], [7, "QuickAttack"], [14, "ShockWave"], [22, "Spark"], [32, "ThunderPunch"], [42, "Discharge"], [52, "WildCharge"], [62, "Thunderbolt"], [70, "Thunder"]],
      undefined,
      "Um Pokémon de Johto do tipo Electric, conhecido por sua presença marcante na região."),
    sp(244, "Entei", ["Fire"], [115, 115, 85, 90, 75, 100], 3,
      [[1, "Ember"], [7, "QuickAttack"], [14, "FireSpin"], [22, "FlameWheel"], [32, "FireFang"], [42, "FirePunch"], [52, "Flamethrower"], [62, "FireBlast"], [70, "Overheat"]],
      undefined,
      "Um Pokémon de Johto do tipo Fire, conhecido por sua presença marcante na região."),
    sp(245, "Suicune", ["Water"], [100, 75, 115, 90, 115, 85], 3,
      [[1, "Bubble"], [7, "QuickAttack"], [14, "WaterGun"], [22, "WaterPulse"], [32, "BubbleBeam"], [42, "Waterfall"], [52, "Surf"], [62, "Crabhammer"], [70, "HydroPump"]],
      undefined,
      "Um Pokémon de Johto do tipo Water, conhecido por sua presença marcante na região."),
    sp(246, "Larvitar", ["Rock", "Ground"], [50, 64, 50, 45, 50, 41], 45,
      [[1, "RockThrow"], [7, "MudSlap"], [14, "RockTomb"], [22, "MudShot"], [32, "AncientPower"], [42, "BoneClub"], [52, "RockSlide"], [62, "Dig"], [70, "Bonemerang"], [80, "EarthPower"]],
      [{ speciesId: 247, trigger: "level", level: 30 }],
      "Um Pokémon de Johto do tipo Rock/Ground, conhecido por sua presença marcante na região."),
    sp(247, "Pupitar", ["Rock", "Ground"], [70, 84, 70, 65, 70, 51], 45,
      [[1, "RockThrow"], [7, "MudSlap"], [14, "RockTomb"], [22, "MudShot"], [32, "AncientPower"], [42, "BoneClub"], [52, "RockSlide"], [62, "Dig"], [70, "Bonemerang"], [80, "EarthPower"]],
      [{ speciesId: 248, trigger: "level", level: 55 }],
      "Um Pokémon de Johto do tipo Rock/Ground, conhecido por sua presença marcante na região."),
    sp(248, "Tyranitar", ["Rock", "Dark"], [100, 134, 110, 95, 100, 61], 45,
      [[1, "RockThrow"], [7, "Pursuit"], [14, "RockTomb"], [22, "AncientPower"], [32, "FeintAttack"], [42, "Bite"], [52, "NightSlash"], [62, "RockSlide"], [70, "Crunch"], [80, "StoneEdge"]],
      undefined,
      "Um Pokémon de Johto do tipo Rock/Dark, conhecido por sua presença marcante na região."),
    sp(249, "Lugia", ["Psychic", "Flying"], [106, 90, 130, 90, 154, 110], 3,
      [[1, "Confusion"], [7, "Gust"], [14, "Peck"], [22, "WingAttack"], [32, "AerialAce"], [42, "Psybeam"], [52, "AirSlash"], [62, "FutureSight"], [70, "ZenHeadbutt"], [80, "DrillPeck"]],
      undefined,
      "Um Pokémon de Johto do tipo Psychic/Flying, conhecido por sua presença marcante na região."),
    sp(250, "Ho-Oh", ["Fire", "Flying"], [106, 130, 90, 110, 154, 90], 3,
      [[1, "Ember"], [7, "Gust"], [14, "FireSpin"], [22, "Peck"], [32, "FlameWheel"], [42, "WingAttack"], [52, "AerialAce"], [62, "FireFang"], [70, "FirePunch"], [80, "AirSlash"]],
      undefined,
      "Um Pokémon de Johto do tipo Fire/Flying, conhecido por sua presença marcante na região."),
    sp(251, "Celebi", ["Psychic", "Grass"], [100, 100, 100, 100, 100, 100], 45,
      [[1, "Confusion"], [7, "Absorb"], [14, "VineWhip"], [22, "RazorLeaf"], [32, "MegaDrain"], [42, "Psybeam"], [52, "PetalDance"], [62, "FutureSight"], [70, "ZenHeadbutt"], [80, "SeedBomb"]],
      undefined,
      "Um Pokémon de Johto do tipo Psychic/Grass, conhecido por sua presença marcante na região."),
  ];
}
