/**
 * Catálogo Hoenn (Fase 6.4-C).
 *
 * Espécies de id 252–386 (Hoenn), exceto 282 (Gardevoir) e 384 (Rayquaza),
 * que já viviam no catálogo base. Dados (tipos, status-base, catchRate,
 * evoluções) derivados de PokeAPI/pokeapi (data/v2/csv). Learnsets derivados
 * do catálogo de golpes já existente (`ALL_MOVES`), com STAB por tipo e
 * progressão de poder; evolução por item usa os IDs de `evolution-items.ts`.
 *
 * Regras herdadas da 6.4-B: linhas evolutivas completas, gatilho dirigido por
 * dados (`trigger:"level"|"item"`), e proxies de pedra onde a série original
 * usa felicidade/beleza/troca (o jogo ainda não tem esses estados).
 * Shedinja (292) existe como espécie, mas sem gatilho: o cânone exige slot
 * vazio no time + Pokébola, mecânica que não existe aqui.
 */
import { EVOLUTION_ITEM_IDS } from "./evolution-items";
import type { AllMoves, EvolvesTo, PokemonSpeciesData } from "./pokedex";

type MoveKey = keyof AllMoves;
type Bases = [number, number, number, number, number, number];

const SPRITE_BASE =
  "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated";

function spriteUrl(id: number, variant?: "back" | "shiny"): string {
  return variant ? `${SPRITE_BASE}/${variant}/${id}.gif` : `${SPRITE_BASE}/${id}.gif`;
}

/** Espécies novas de Hoenn, em ordem de id. Chamado por `pokedex.ts` com `ALL_MOVES`. */
export function hoennRest(M: AllMoves): PokemonSpeciesData[] {
  const sp = (
    id: number, name: string, types: [string] | [string, string], bases: Bases,
    catchRate: number, moves: ReadonlyArray<readonly [number, MoveKey]>,
    evolve: ReadonlyArray<EvolvesTo> | undefined, description: string
  ): PokemonSpeciesData => ({
    id, name, types, baseHp: bases[0], baseAtk: bases[1], baseDef: bases[2],
    baseSpAtk: bases[3], baseSpDef: bases[4], baseSpd: bases[5], catchRate,
    learnset: moves.map(([level, key]) => ({ level, move: M[key] })),
    evolvesTo: evolve?.map((e) => ({ ...e })),
    frontSprite: spriteUrl(id), backSprite: spriteUrl(id, "back"),
    shinyFrontSprite: spriteUrl(id, "shiny"), description,
  });

  return [
    sp(252, "Treecko", ["Grass"], [40, 45, 35, 65, 55, 70], 45,
      [[1, "Absorb"], [7, "VineWhip"], [14, "RazorLeaf"], [22, "MegaDrain"], [32, "PetalDance"], [42, "SeedBomb"], [52, "EnergyBall"], [62, "LeafBlade"], [70, "SolarBeam"]],
      [{ speciesId: 253, trigger: "level", level: 16 }],
      "Um Pokémon de Hoenn do tipo Grass, avistado pela primeira vez nas rotas da região."),
    sp(253, "Grovyle", ["Grass"], [50, 65, 45, 85, 65, 95], 45,
      [[1, "Absorb"], [7, "VineWhip"], [14, "RazorLeaf"], [22, "MegaDrain"], [32, "PetalDance"], [42, "SeedBomb"], [52, "EnergyBall"], [62, "LeafBlade"], [70, "SolarBeam"]],
      [{ speciesId: 254, trigger: "level", level: 36 }],
      "Um Pokémon de Hoenn do tipo Grass, avistado pela primeira vez nas rotas da região."),
    sp(254, "Sceptile", ["Grass"], [70, 85, 65, 105, 85, 120], 45,
      [[1, "Absorb"], [7, "VineWhip"], [14, "RazorLeaf"], [22, "MegaDrain"], [32, "PetalDance"], [42, "SeedBomb"], [52, "EnergyBall"], [62, "LeafBlade"], [70, "SolarBeam"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Grass, avistado pela primeira vez nas rotas da região."),
    sp(255, "Torchic", ["Fire"], [45, 60, 40, 70, 50, 45], 45,
      [[1, "Ember"], [7, "FireSpin"], [14, "FlameWheel"], [22, "FireFang"], [32, "FirePunch"], [42, "Flamethrower"], [52, "FireBlast"], [62, "Overheat"]],
      [{ speciesId: 256, trigger: "level", level: 16 }],
      "Um Pokémon de Hoenn do tipo Fire, avistado pela primeira vez nas rotas da região."),
    sp(256, "Combusken", ["Fire", "Fighting"], [60, 85, 60, 85, 60, 55], 45,
      [[1, "Ember"], [7, "FireSpin"], [14, "MachPunch"], [22, "KarateChop"], [32, "LowKick"], [42, "FlameWheel"], [52, "CrossChop"], [62, "DynamicPunch"], [70, "FireBlast"], [80, "Overheat"]],
      [{ speciesId: 257, trigger: "level", level: 36 }],
      "Um Pokémon de Hoenn do tipo Fire, avistado pela primeira vez nas rotas da região."),
    sp(257, "Blaziken", ["Fire", "Fighting"], [80, 120, 70, 110, 70, 80], 45,
      [[1, "Ember"], [7, "FireSpin"], [14, "MachPunch"], [22, "KarateChop"], [32, "LowKick"], [42, "FlameWheel"], [52, "CrossChop"], [62, "DynamicPunch"], [70, "FireBlast"], [80, "Overheat"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Fire, avistado pela primeira vez nas rotas da região."),
    sp(258, "Mudkip", ["Water"], [50, 70, 50, 50, 50, 40], 45,
      [[1, "Bubble"], [7, "WaterGun"], [14, "WaterPulse"], [22, "BubbleBeam"], [32, "Waterfall"], [42, "Surf"], [52, "Crabhammer"], [62, "HydroPump"]],
      [{ speciesId: 259, trigger: "level", level: 16 }],
      "Um Pokémon de Hoenn do tipo Water, avistado pela primeira vez nas rotas da região."),
    sp(259, "Marshtomp", ["Water", "Ground"], [70, 85, 70, 60, 70, 50], 45,
      [[1, "Bubble"], [7, "MudSlap"], [14, "WaterGun"], [22, "MudShot"], [32, "WaterPulse"], [42, "BoneClub"], [52, "EarthPower"], [62, "Crabhammer"], [70, "Earthquake"], [80, "HydroPump"]],
      [{ speciesId: 260, trigger: "level", level: 36 }],
      "Um Pokémon de Hoenn do tipo Water, avistado pela primeira vez nas rotas da região."),
    sp(260, "Swampert", ["Water", "Ground"], [100, 110, 90, 85, 90, 60], 45,
      [[1, "Bubble"], [7, "MudSlap"], [14, "WaterGun"], [22, "MudShot"], [32, "WaterPulse"], [42, "BoneClub"], [52, "EarthPower"], [62, "Crabhammer"], [70, "Earthquake"], [80, "HydroPump"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Water, avistado pela primeira vez nas rotas da região."),
    sp(261, "Poochyena", ["Dark"], [35, 55, 35, 30, 30, 35], 255,
      [[1, "Pursuit"], [7, "Tackle"], [14, "FeintAttack"], [22, "Bite"], [32, "NightSlash"], [42, "Crunch"], [52, "DarkPulse"]],
      [{ speciesId: 262, trigger: "level", level: 18 }],
      "Um Pokémon de Hoenn do tipo Dark, avistado pela primeira vez nas rotas da região."),
    sp(262, "Mightyena", ["Dark"], [70, 90, 70, 60, 60, 70], 127,
      [[1, "Pursuit"], [7, "Tackle"], [14, "FeintAttack"], [22, "Bite"], [32, "NightSlash"], [42, "Crunch"], [52, "DarkPulse"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Dark, avistado pela primeira vez nas rotas da região."),
    sp(263, "Zigzagoon", ["Normal"], [38, 30, 41, 30, 41, 60], 255,
      [[1, "Scratch"], [7, "Tackle"], [14, "QuickAttack"], [22, "PayDay"], [32, "ViceGrip"], [42, "Swift"], [52, "ExtremeSpeed"], [62, "SkullBash"], [70, "TakeDown"], [80, "HyperBeam"]],
      [{ speciesId: 264, trigger: "level", level: 20 }],
      "Um Pokémon de Hoenn do tipo Normal, avistado pela primeira vez nas rotas da região."),
    sp(264, "Linoone", ["Normal"], [78, 70, 61, 50, 61, 100], 90,
      [[1, "Scratch"], [7, "Tackle"], [14, "QuickAttack"], [22, "PayDay"], [32, "ViceGrip"], [42, "Swift"], [52, "ExtremeSpeed"], [62, "SkullBash"], [70, "TakeDown"], [80, "HyperBeam"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Normal, avistado pela primeira vez nas rotas da região."),
    sp(265, "Wurmple", ["Bug"], [45, 45, 35, 20, 30, 20], 255,
      [[1, "LeechLife"], [7, "FuryCutter"], [14, "Twineedle"], [22, "BugBite"], [32, "SilverWind"], [42, "SignalBeam"], [52, "XScissor"]],
      [{ speciesId: 266, trigger: "level", level: 7 }, { speciesId: 268, trigger: "level", level: 7 }],
      "Um Pokémon de Hoenn do tipo Bug, avistado pela primeira vez nas rotas da região."),
    sp(266, "Silcoon", ["Bug"], [50, 35, 55, 25, 25, 15], 120,
      [[1, "LeechLife"], [7, "FuryCutter"], [14, "Twineedle"], [22, "BugBite"], [32, "SilverWind"], [42, "SignalBeam"], [52, "XScissor"]],
      [{ speciesId: 267, trigger: "level", level: 10 }],
      "Um Pokémon de Hoenn do tipo Bug, avistado pela primeira vez nas rotas da região."),
    sp(267, "Beautifly", ["Bug", "Flying"], [60, 70, 50, 100, 50, 65], 45,
      [[1, "LeechLife"], [7, "Gust"], [14, "Peck"], [22, "FuryCutter"], [32, "Twineedle"], [42, "AerialAce"], [52, "DrillPeck"], [62, "Fly"], [70, "XScissor"], [80, "Bounce"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Bug, avistado pela primeira vez nas rotas da região."),
    sp(268, "Cascoon", ["Bug"], [50, 35, 55, 25, 25, 15], 120,
      [[1, "LeechLife"], [7, "FuryCutter"], [14, "Twineedle"], [22, "BugBite"], [32, "SilverWind"], [42, "SignalBeam"], [52, "XScissor"]],
      [{ speciesId: 269, trigger: "level", level: 10 }],
      "Um Pokémon de Hoenn do tipo Bug, avistado pela primeira vez nas rotas da região."),
    sp(269, "Dustox", ["Bug", "Poison"], [60, 50, 70, 50, 90, 65], 45,
      [[1, "LeechLife"], [7, "PoisonSting"], [14, "Acid"], [22, "FuryCutter"], [32, "Twineedle"], [42, "BugBite"], [52, "SignalBeam"], [62, "PoisonJab"], [70, "XScissor"], [80, "SludgeBomb"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Bug, avistado pela primeira vez nas rotas da região."),
    sp(270, "Lotad", ["Water", "Grass"], [40, 30, 30, 40, 50, 30], 255,
      [[1, "Absorb"], [7, "Bubble"], [14, "VineWhip"], [22, "RazorLeaf"], [32, "MegaDrain"], [42, "WaterGun"], [52, "LeafBlade"], [62, "Crabhammer"], [70, "SolarBeam"], [80, "HydroPump"]],
      [{ speciesId: 271, trigger: "level", level: 14 }],
      "Um Pokémon de Hoenn do tipo Water, avistado pela primeira vez nas rotas da região."),
    sp(271, "Lombre", ["Water", "Grass"], [60, 50, 50, 60, 70, 50], 120,
      [[1, "Absorb"], [7, "Bubble"], [14, "VineWhip"], [22, "RazorLeaf"], [32, "MegaDrain"], [42, "WaterGun"], [52, "LeafBlade"], [62, "Crabhammer"], [70, "SolarBeam"], [80, "HydroPump"]],
      [{ speciesId: 272, trigger: "item", itemId: EVOLUTION_ITEM_IDS.waterStone }],
      "Um Pokémon de Hoenn do tipo Water, avistado pela primeira vez nas rotas da região."),
    sp(272, "Ludicolo", ["Water", "Grass"], [80, 70, 70, 90, 100, 70], 45,
      [[1, "Absorb"], [7, "Bubble"], [14, "VineWhip"], [22, "RazorLeaf"], [32, "MegaDrain"], [42, "WaterGun"], [52, "LeafBlade"], [62, "Crabhammer"], [70, "SolarBeam"], [80, "HydroPump"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Water, avistado pela primeira vez nas rotas da região."),
    sp(273, "Seedot", ["Grass"], [40, 40, 50, 30, 30, 30], 255,
      [[1, "Absorb"], [7, "VineWhip"], [14, "RazorLeaf"], [22, "MegaDrain"], [32, "PetalDance"], [42, "SeedBomb"], [52, "EnergyBall"], [62, "LeafBlade"], [70, "SolarBeam"]],
      [{ speciesId: 274, trigger: "level", level: 14 }],
      "Um Pokémon de Hoenn do tipo Grass, avistado pela primeira vez nas rotas da região."),
    sp(274, "Nuzleaf", ["Grass", "Dark"], [70, 70, 40, 60, 40, 60], 120,
      [[1, "Absorb"], [7, "VineWhip"], [14, "RazorLeaf"], [22, "MegaDrain"], [32, "Pursuit"], [42, "Bite"], [52, "Crunch"], [62, "EnergyBall"], [70, "LeafBlade"], [80, "SolarBeam"]],
      [{ speciesId: 275, trigger: "item", itemId: EVOLUTION_ITEM_IDS.leafStone }],
      "Um Pokémon de Hoenn do tipo Grass, avistado pela primeira vez nas rotas da região."),
    sp(275, "Shiftry", ["Grass", "Dark"], [90, 100, 60, 90, 60, 80], 45,
      [[1, "Absorb"], [7, "VineWhip"], [14, "RazorLeaf"], [22, "MegaDrain"], [32, "Pursuit"], [42, "Bite"], [52, "Crunch"], [62, "EnergyBall"], [70, "LeafBlade"], [80, "SolarBeam"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Grass, avistado pela primeira vez nas rotas da região."),
    sp(276, "Taillow", ["Normal", "Flying"], [40, 55, 30, 30, 30, 85], 200,
      [[1, "Scratch"], [7, "Gust"], [14, "Tackle"], [22, "Peck"], [32, "QuickAttack"], [42, "PayDay"], [52, "Bounce"], [62, "SkullBash"], [70, "TakeDown"], [80, "HyperBeam"]],
      [{ speciesId: 277, trigger: "level", level: 22 }],
      "Um Pokémon de Hoenn do tipo Normal, avistado pela primeira vez nas rotas da região."),
    sp(277, "Swellow", ["Normal", "Flying"], [60, 85, 60, 75, 50, 125], 45,
      [[1, "Scratch"], [7, "Gust"], [14, "Tackle"], [22, "Peck"], [32, "QuickAttack"], [42, "PayDay"], [52, "Bounce"], [62, "SkullBash"], [70, "TakeDown"], [80, "HyperBeam"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Normal, avistado pela primeira vez nas rotas da região."),
    sp(278, "Wingull", ["Water", "Flying"], [40, 30, 30, 55, 30, 85], 190,
      [[1, "Bubble"], [7, "Gust"], [14, "Peck"], [22, "WaterGun"], [32, "AerialAce"], [42, "WaterPulse"], [52, "Bounce"], [62, "Surf"], [70, "Crabhammer"], [80, "HydroPump"]],
      [{ speciesId: 279, trigger: "level", level: 25 }],
      "Um Pokémon de Hoenn do tipo Water, avistado pela primeira vez nas rotas da região."),
    sp(279, "Pelipper", ["Water", "Flying"], [60, 50, 100, 95, 70, 65], 45,
      [[1, "Bubble"], [7, "Gust"], [14, "Peck"], [22, "WaterGun"], [32, "AerialAce"], [42, "WaterPulse"], [52, "Bounce"], [62, "Surf"], [70, "Crabhammer"], [80, "HydroPump"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Water, avistado pela primeira vez nas rotas da região."),
    sp(280, "Ralts", ["Psychic", "Fairy"], [28, 25, 25, 45, 35, 40], 235,
      [[1, "FairyWind"], [7, "DisarmingVoice"], [14, "Confusion"], [22, "DrainingKiss"], [32, "Psybeam"], [42, "FutureSight"], [52, "DazzlingGleam"], [62, "PlayRough"], [70, "Psychic"], [80, "Moonblast"]],
      [{ speciesId: 281, trigger: "level", level: 20 }],
      "Um Pokémon de Hoenn do tipo Psychic, avistado pela primeira vez nas rotas da região."),
    sp(281, "Kirlia", ["Psychic", "Fairy"], [38, 35, 35, 65, 55, 50], 120,
      [[1, "FairyWind"], [7, "DisarmingVoice"], [14, "Confusion"], [22, "DrainingKiss"], [32, "Psybeam"], [42, "FutureSight"], [52, "DazzlingGleam"], [62, "PlayRough"], [70, "Psychic"], [80, "Moonblast"]],
      [{ speciesId: 282, trigger: "level", level: 30 }, { speciesId: 475, trigger: "item", itemId: EVOLUTION_ITEM_IDS.dawnStone }], // 6.4-D: Gallade (sem gênero no jogo: a Pedra do Amanhecer decide)
      "Um Pokémon de Hoenn do tipo Psychic, avistado pela primeira vez nas rotas da região."),
    sp(283, "Surskit", ["Bug", "Water"], [40, 30, 32, 50, 52, 65], 200,
      [[1, "LeechLife"], [7, "Bubble"], [14, "FuryCutter"], [22, "WaterGun"], [32, "Twineedle"], [42, "BugBite"], [52, "XScissor"], [62, "Surf"], [70, "Crabhammer"], [80, "HydroPump"]],
      [{ speciesId: 284, trigger: "level", level: 22 }],
      "Um Pokémon de Hoenn do tipo Bug, avistado pela primeira vez nas rotas da região."),
    sp(284, "Masquerain", ["Bug", "Flying"], [70, 60, 62, 100, 82, 80], 75,
      [[1, "LeechLife"], [7, "Gust"], [14, "Peck"], [22, "FuryCutter"], [32, "Twineedle"], [42, "AerialAce"], [52, "DrillPeck"], [62, "Fly"], [70, "XScissor"], [80, "Bounce"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Bug, avistado pela primeira vez nas rotas da região."),
    sp(285, "Shroomish", ["Grass"], [60, 40, 60, 40, 60, 35], 255,
      [[1, "Absorb"], [7, "VineWhip"], [14, "RazorLeaf"], [22, "MegaDrain"], [32, "PetalDance"], [42, "SeedBomb"], [52, "EnergyBall"], [62, "LeafBlade"], [70, "SolarBeam"]],
      [{ speciesId: 286, trigger: "level", level: 23 }],
      "Um Pokémon de Hoenn do tipo Grass, avistado pela primeira vez nas rotas da região."),
    sp(286, "Breloom", ["Grass", "Fighting"], [60, 130, 80, 60, 60, 70], 90,
      [[1, "Absorb"], [7, "VineWhip"], [14, "RazorLeaf"], [22, "MachPunch"], [32, "MegaDrain"], [42, "KarateChop"], [52, "CrossChop"], [62, "DynamicPunch"], [70, "HighJumpKick"], [80, "SolarBeam"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Grass, avistado pela primeira vez nas rotas da região."),
    sp(287, "Slakoth", ["Normal"], [60, 60, 60, 35, 35, 30], 255,
      [[1, "Scratch"], [7, "Tackle"], [14, "QuickAttack"], [22, "PayDay"], [32, "ViceGrip"], [42, "Swift"], [52, "ExtremeSpeed"], [62, "SkullBash"], [70, "TakeDown"], [80, "HyperBeam"]],
      [{ speciesId: 288, trigger: "level", level: 18 }],
      "Um Pokémon de Hoenn do tipo Normal, avistado pela primeira vez nas rotas da região."),
    sp(288, "Vigoroth", ["Normal"], [80, 80, 80, 55, 55, 90], 120,
      [[1, "Scratch"], [7, "Tackle"], [14, "QuickAttack"], [22, "PayDay"], [32, "ViceGrip"], [42, "Swift"], [52, "ExtremeSpeed"], [62, "SkullBash"], [70, "TakeDown"], [80, "HyperBeam"]],
      [{ speciesId: 289, trigger: "level", level: 36 }],
      "Um Pokémon de Hoenn do tipo Normal, avistado pela primeira vez nas rotas da região."),
    sp(289, "Slaking", ["Normal"], [150, 160, 100, 95, 65, 100], 45,
      [[1, "Scratch"], [7, "Tackle"], [14, "QuickAttack"], [22, "PayDay"], [32, "ViceGrip"], [42, "Swift"], [52, "ExtremeSpeed"], [62, "SkullBash"], [70, "TakeDown"], [80, "HyperBeam"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Normal, avistado pela primeira vez nas rotas da região."),
    sp(290, "Nincada", ["Bug", "Ground"], [31, 45, 90, 30, 30, 40], 255,
      [[1, "LeechLife"], [7, "MudSlap"], [14, "FuryCutter"], [22, "Twineedle"], [32, "MudShot"], [42, "BugBite"], [52, "XScissor"], [62, "Bonemerang"], [70, "EarthPower"], [80, "Earthquake"]],
      [{ speciesId: 291, trigger: "level", level: 20 }],
      "Um Pokémon de Hoenn do tipo Bug, avistado pela primeira vez nas rotas da região."),
    sp(291, "Ninjask", ["Bug", "Flying"], [61, 90, 45, 50, 50, 160], 120,
      [[1, "LeechLife"], [7, "Gust"], [14, "Peck"], [22, "FuryCutter"], [32, "Twineedle"], [42, "AerialAce"], [52, "DrillPeck"], [62, "Fly"], [70, "XScissor"], [80, "Bounce"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Bug, avistado pela primeira vez nas rotas da região."),
    sp(292, "Shedinja", ["Bug", "Ghost"], [1, 90, 45, 30, 30, 40], 45,
      [[1, "LeechLife"], [7, "Astonish"], [14, "Lick"], [22, "FuryCutter"], [32, "ShadowSneak"], [42, "Twineedle"], [52, "BugBite"], [62, "SignalBeam"], [70, "ShadowBall"], [80, "XScissor"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Bug, avistado pela primeira vez nas rotas da região."),
    sp(293, "Whismur", ["Normal"], [64, 51, 23, 51, 23, 28], 190,
      [[1, "Scratch"], [7, "Tackle"], [14, "QuickAttack"], [22, "PayDay"], [32, "ViceGrip"], [42, "Swift"], [52, "ExtremeSpeed"], [62, "SkullBash"], [70, "TakeDown"], [80, "HyperBeam"]],
      [{ speciesId: 294, trigger: "level", level: 20 }],
      "Um Pokémon de Hoenn do tipo Normal, avistado pela primeira vez nas rotas da região."),
    sp(294, "Loudred", ["Normal"], [84, 71, 43, 71, 43, 48], 120,
      [[1, "Scratch"], [7, "Tackle"], [14, "QuickAttack"], [22, "PayDay"], [32, "ViceGrip"], [42, "Swift"], [52, "ExtremeSpeed"], [62, "SkullBash"], [70, "TakeDown"], [80, "HyperBeam"]],
      [{ speciesId: 295, trigger: "level", level: 40 }],
      "Um Pokémon de Hoenn do tipo Normal, avistado pela primeira vez nas rotas da região."),
    sp(295, "Exploud", ["Normal"], [104, 91, 63, 91, 73, 68], 45,
      [[1, "Scratch"], [7, "Tackle"], [14, "QuickAttack"], [22, "PayDay"], [32, "ViceGrip"], [42, "Swift"], [52, "ExtremeSpeed"], [62, "SkullBash"], [70, "TakeDown"], [80, "HyperBeam"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Normal, avistado pela primeira vez nas rotas da região."),
    sp(296, "Makuhita", ["Fighting"], [72, 60, 30, 20, 30, 25], 180,
      [[1, "MachPunch"], [7, "KarateChop"], [14, "LowKick"], [22, "RollingKick"], [32, "VitalThrow"], [42, "BrickBreak"], [52, "SkyUppercut"], [62, "CrossChop"], [70, "DynamicPunch"], [80, "HighJumpKick"]],
      [{ speciesId: 297, trigger: "level", level: 24 }],
      "Um Pokémon de Hoenn do tipo Fighting, avistado pela primeira vez nas rotas da região."),
    sp(297, "Hariyama", ["Fighting"], [144, 120, 60, 40, 60, 50], 200,
      [[1, "MachPunch"], [7, "KarateChop"], [14, "LowKick"], [22, "RollingKick"], [32, "VitalThrow"], [42, "BrickBreak"], [52, "SkyUppercut"], [62, "CrossChop"], [70, "DynamicPunch"], [80, "HighJumpKick"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Fighting, avistado pela primeira vez nas rotas da região."),
    sp(298, "Azurill", ["Normal", "Fairy"], [50, 20, 40, 20, 40, 20], 150,
      [[1, "Scratch"], [7, "FairyWind"], [14, "Tackle"], [22, "QuickAttack"], [32, "DisarmingVoice"], [42, "PayDay"], [52, "SkullBash"], [62, "PlayRough"], [70, "Moonblast"], [80, "HyperBeam"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Normal, avistado pela primeira vez nas rotas da região."),
    sp(299, "Nosepass", ["Rock"], [30, 45, 135, 45, 90, 30], 255,
      [[1, "RockPolish"], [7, "RockTomb"], [14, "RockThrow"], [22, "AncientPower"], [32, "RockSlide"], [42, "StoneEdge"]],
      [{ speciesId: 476, trigger: "item", itemId: EVOLUTION_ITEM_IDS.thunderStone }], // 6.4-D: Probopass (campo magnético → Pedra de Trovão, como em SwSh)
      "Um Pokémon de Hoenn do tipo Rock, avistado pela primeira vez nas rotas da região."),
    sp(300, "Skitty", ["Normal"], [50, 45, 45, 35, 35, 50], 255,
      [[1, "Scratch"], [7, "Tackle"], [14, "QuickAttack"], [22, "PayDay"], [32, "ViceGrip"], [42, "Swift"], [52, "ExtremeSpeed"], [62, "SkullBash"], [70, "TakeDown"], [80, "HyperBeam"]],
      [{ speciesId: 301, trigger: "item", itemId: EVOLUTION_ITEM_IDS.moonStone }],
      "Um Pokémon de Hoenn do tipo Normal, avistado pela primeira vez nas rotas da região."),
    sp(301, "Delcatty", ["Normal"], [70, 65, 65, 55, 55, 90], 60,
      [[1, "Scratch"], [7, "Tackle"], [14, "QuickAttack"], [22, "PayDay"], [32, "ViceGrip"], [42, "Swift"], [52, "ExtremeSpeed"], [62, "SkullBash"], [70, "TakeDown"], [80, "HyperBeam"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Normal, avistado pela primeira vez nas rotas da região."),
    sp(302, "Sableye", ["Dark", "Ghost"], [50, 75, 75, 65, 65, 50], 45,
      [[1, "Astonish"], [7, "Lick"], [14, "Pursuit"], [22, "ShadowSneak"], [32, "Bite"], [42, "FeintAttack"], [52, "NightSlash"], [62, "Crunch"], [70, "DarkPulse"], [80, "ShadowBall"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Dark, avistado pela primeira vez nas rotas da região."),
    sp(303, "Mawile", ["Steel", "Fairy"], [50, 85, 85, 55, 55, 50], 45,
      [[1, "FairyWind"], [7, "MetalClaw"], [14, "DisarmingVoice"], [22, "DrainingKiss"], [32, "MagnetBomb"], [42, "SteelWing"], [52, "DazzlingGleam"], [62, "PlayRough"], [70, "Moonblast"], [80, "IronTail"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Steel, avistado pela primeira vez nas rotas da região."),
    sp(304, "Aron", ["Steel", "Rock"], [50, 70, 100, 40, 40, 30], 180,
      [[1, "MetalClaw"], [7, "RockPolish"], [14, "RockThrow"], [22, "RockTomb"], [32, "AncientPower"], [42, "MagnetBomb"], [52, "FlashCannon"], [62, "IronHead"], [70, "IronTail"], [80, "StoneEdge"]],
      [{ speciesId: 305, trigger: "level", level: 32 }],
      "Um Pokémon de Hoenn do tipo Steel, avistado pela primeira vez nas rotas da região."),
    sp(305, "Lairon", ["Steel", "Rock"], [60, 90, 140, 50, 50, 40], 90,
      [[1, "MetalClaw"], [7, "RockPolish"], [14, "RockThrow"], [22, "RockTomb"], [32, "AncientPower"], [42, "MagnetBomb"], [52, "FlashCannon"], [62, "IronHead"], [70, "IronTail"], [80, "StoneEdge"]],
      [{ speciesId: 306, trigger: "level", level: 42 }],
      "Um Pokémon de Hoenn do tipo Steel, avistado pela primeira vez nas rotas da região."),
    sp(306, "Aggron", ["Steel", "Rock"], [70, 110, 180, 60, 60, 50], 45,
      [[1, "MetalClaw"], [7, "RockPolish"], [14, "RockThrow"], [22, "RockTomb"], [32, "AncientPower"], [42, "MagnetBomb"], [52, "FlashCannon"], [62, "IronHead"], [70, "IronTail"], [80, "StoneEdge"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Steel, avistado pela primeira vez nas rotas da região."),
    sp(307, "Meditite", ["Fighting", "Psychic"], [30, 40, 55, 40, 55, 60], 180,
      [[1, "MachPunch"], [7, "Confusion"], [14, "KarateChop"], [22, "LowKick"], [32, "RollingKick"], [42, "Psybeam"], [52, "Psychic"], [62, "CrossChop"], [70, "DynamicPunch"], [80, "HighJumpKick"]],
      [{ speciesId: 308, trigger: "level", level: 37 }],
      "Um Pokémon de Hoenn do tipo Fighting, avistado pela primeira vez nas rotas da região."),
    sp(308, "Medicham", ["Fighting", "Psychic"], [60, 60, 75, 60, 75, 80], 90,
      [[1, "MachPunch"], [7, "Confusion"], [14, "KarateChop"], [22, "LowKick"], [32, "RollingKick"], [42, "Psybeam"], [52, "Psychic"], [62, "CrossChop"], [70, "DynamicPunch"], [80, "HighJumpKick"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Fighting, avistado pela primeira vez nas rotas da região."),
    sp(309, "Electrike", ["Electric"], [40, 45, 40, 65, 40, 65], 120,
      [[1, "ThunderShock"], [7, "Tackle"], [14, "ShockWave"], [22, "Spark"], [32, "ThunderPunch"], [42, "Discharge"], [52, "WildCharge"], [62, "Thunderbolt"], [70, "Thunder"]],
      [{ speciesId: 310, trigger: "level", level: 26 }],
      "Um Pokémon de Hoenn do tipo Electric, avistado pela primeira vez nas rotas da região."),
    sp(310, "Manectric", ["Electric"], [70, 75, 60, 105, 60, 105], 45,
      [[1, "ThunderShock"], [7, "Tackle"], [14, "ShockWave"], [22, "Spark"], [32, "ThunderPunch"], [42, "Discharge"], [52, "WildCharge"], [62, "Thunderbolt"], [70, "Thunder"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Electric, avistado pela primeira vez nas rotas da região."),
    sp(311, "Plusle", ["Electric"], [60, 50, 40, 85, 75, 95], 200,
      [[1, "ThunderShock"], [7, "Tackle"], [14, "ShockWave"], [22, "Spark"], [32, "ThunderPunch"], [42, "Discharge"], [52, "WildCharge"], [62, "Thunderbolt"], [70, "Thunder"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Electric, avistado pela primeira vez nas rotas da região."),
    sp(312, "Minun", ["Electric"], [60, 40, 50, 75, 85, 95], 200,
      [[1, "ThunderShock"], [7, "Tackle"], [14, "ShockWave"], [22, "Spark"], [32, "ThunderPunch"], [42, "Discharge"], [52, "WildCharge"], [62, "Thunderbolt"], [70, "Thunder"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Electric, avistado pela primeira vez nas rotas da região."),
    sp(313, "Volbeat", ["Bug"], [65, 73, 75, 47, 85, 85], 150,
      [[1, "LeechLife"], [7, "FuryCutter"], [14, "Twineedle"], [22, "BugBite"], [32, "SilverWind"], [42, "SignalBeam"], [52, "XScissor"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Bug, avistado pela primeira vez nas rotas da região."),
    sp(314, "Illumise", ["Bug"], [65, 47, 75, 73, 85, 85], 150,
      [[1, "LeechLife"], [7, "FuryCutter"], [14, "Twineedle"], [22, "BugBite"], [32, "SilverWind"], [42, "SignalBeam"], [52, "XScissor"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Bug, avistado pela primeira vez nas rotas da região."),
    sp(315, "Roselia", ["Grass", "Poison"], [50, 60, 45, 100, 80, 65], 150,
      [[1, "Absorb"], [7, "PoisonSting"], [14, "VineWhip"], [22, "RazorLeaf"], [32, "Acid"], [42, "MegaDrain"], [52, "EnergyBall"], [62, "LeafBlade"], [70, "SludgeBomb"], [80, "SolarBeam"]],
      [{ speciesId: 407, trigger: "item", itemId: EVOLUTION_ITEM_IDS.shinyStone }], // 6.4-D: Roserade
      "Um Pokémon de Hoenn do tipo Grass, avistado pela primeira vez nas rotas da região."),
    sp(316, "Gulpin", ["Poison"], [70, 43, 53, 43, 53, 40], 225,
      [[1, "PoisonSting"], [7, "Acid"], [14, "PoisonFang"], [22, "Sludge"], [32, "PoisonJab"], [42, "SludgeBomb"]],
      [{ speciesId: 317, trigger: "level", level: 26 }],
      "Um Pokémon de Hoenn do tipo Poison, avistado pela primeira vez nas rotas da região."),
    sp(317, "Swalot", ["Poison"], [100, 73, 83, 73, 83, 55], 75,
      [[1, "PoisonSting"], [7, "Acid"], [14, "PoisonFang"], [22, "Sludge"], [32, "PoisonJab"], [42, "SludgeBomb"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Poison, avistado pela primeira vez nas rotas da região."),
    sp(318, "Carvanha", ["Water", "Dark"], [45, 90, 20, 65, 20, 65], 225,
      [[1, "Bubble"], [7, "Pursuit"], [14, "WaterGun"], [22, "Bite"], [32, "FeintAttack"], [42, "WaterPulse"], [52, "Crunch"], [62, "Surf"], [70, "Crabhammer"], [80, "HydroPump"]],
      [{ speciesId: 319, trigger: "level", level: 30 }],
      "Um Pokémon de Hoenn do tipo Water, avistado pela primeira vez nas rotas da região."),
    sp(319, "Sharpedo", ["Water", "Dark"], [70, 120, 40, 95, 40, 95], 60,
      [[1, "Bubble"], [7, "Pursuit"], [14, "WaterGun"], [22, "Bite"], [32, "FeintAttack"], [42, "WaterPulse"], [52, "Crunch"], [62, "Surf"], [70, "Crabhammer"], [80, "HydroPump"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Water, avistado pela primeira vez nas rotas da região."),
    sp(320, "Wailmer", ["Water"], [130, 70, 35, 70, 35, 60], 125,
      [[1, "Bubble"], [7, "WaterGun"], [14, "WaterPulse"], [22, "BubbleBeam"], [32, "Waterfall"], [42, "Surf"], [52, "Crabhammer"], [62, "HydroPump"]],
      [{ speciesId: 321, trigger: "level", level: 40 }],
      "Um Pokémon de Hoenn do tipo Water, avistado pela primeira vez nas rotas da região."),
    sp(321, "Wailord", ["Water"], [170, 90, 45, 90, 45, 60], 60,
      [[1, "Bubble"], [7, "WaterGun"], [14, "WaterPulse"], [22, "BubbleBeam"], [32, "Waterfall"], [42, "Surf"], [52, "Crabhammer"], [62, "HydroPump"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Water, avistado pela primeira vez nas rotas da região."),
    sp(322, "Numel", ["Fire", "Ground"], [60, 60, 40, 65, 45, 35], 255,
      [[1, "Ember"], [7, "FireSpin"], [14, "MudSlap"], [22, "MudShot"], [32, "FlameWheel"], [42, "BoneClub"], [52, "EarthPower"], [62, "Earthquake"], [70, "FireBlast"], [80, "Overheat"]],
      [{ speciesId: 323, trigger: "level", level: 33 }],
      "Um Pokémon de Hoenn do tipo Fire, avistado pela primeira vez nas rotas da região."),
    sp(323, "Camerupt", ["Fire", "Ground"], [70, 100, 70, 105, 75, 40], 150,
      [[1, "Ember"], [7, "FireSpin"], [14, "MudSlap"], [22, "MudShot"], [32, "FlameWheel"], [42, "BoneClub"], [52, "EarthPower"], [62, "Earthquake"], [70, "FireBlast"], [80, "Overheat"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Fire, avistado pela primeira vez nas rotas da região."),
    sp(324, "Torkoal", ["Fire"], [70, 85, 140, 85, 70, 20], 90,
      [[1, "Ember"], [7, "FireSpin"], [14, "FlameWheel"], [22, "FireFang"], [32, "FirePunch"], [42, "Flamethrower"], [52, "FireBlast"], [62, "Overheat"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Fire, avistado pela primeira vez nas rotas da região."),
    sp(325, "Spoink", ["Psychic"], [60, 25, 35, 70, 80, 60], 255,
      [[1, "Confusion"], [7, "Tackle"], [14, "Psybeam"], [22, "FutureSight"], [32, "ZenHeadbutt"], [42, "Psychic"]],
      [{ speciesId: 326, trigger: "level", level: 32 }],
      "Um Pokémon de Hoenn do tipo Psychic, avistado pela primeira vez nas rotas da região."),
    sp(326, "Grumpig", ["Psychic"], [80, 45, 65, 90, 110, 80], 60,
      [[1, "Confusion"], [7, "Tackle"], [14, "Psybeam"], [22, "FutureSight"], [32, "ZenHeadbutt"], [42, "Psychic"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Psychic, avistado pela primeira vez nas rotas da região."),
    sp(327, "Spinda", ["Normal"], [60, 60, 60, 60, 60, 60], 255,
      [[1, "Scratch"], [7, "Tackle"], [14, "QuickAttack"], [22, "PayDay"], [32, "ViceGrip"], [42, "Swift"], [52, "ExtremeSpeed"], [62, "SkullBash"], [70, "TakeDown"], [80, "HyperBeam"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Normal, avistado pela primeira vez nas rotas da região."),
    sp(328, "Trapinch", ["Ground"], [45, 100, 45, 45, 45, 10], 255,
      [[1, "MudSlap"], [7, "Tackle"], [14, "MudShot"], [22, "BoneClub"], [32, "Dig"], [42, "Bonemerang"], [52, "EarthPower"], [62, "Earthquake"]],
      [{ speciesId: 329, trigger: "level", level: 35 }],
      "Um Pokémon de Hoenn do tipo Ground, avistado pela primeira vez nas rotas da região."),
    sp(329, "Vibrava", ["Ground", "Dragon"], [50, 70, 50, 50, 50, 70], 120,
      [[1, "MudSlap"], [7, "Twister"], [14, "MudShot"], [22, "DragonBreath"], [32, "BoneClub"], [42, "Dig"], [52, "Bonemerang"], [62, "EarthPower"], [70, "Outrage"], [80, "Earthquake"]],
      [{ speciesId: 330, trigger: "level", level: 45 }],
      "Um Pokémon de Hoenn do tipo Ground, avistado pela primeira vez nas rotas da região."),
    sp(330, "Flygon", ["Ground", "Dragon"], [80, 100, 80, 80, 80, 100], 45,
      [[1, "MudSlap"], [7, "Twister"], [14, "MudShot"], [22, "DragonBreath"], [32, "BoneClub"], [42, "Dig"], [52, "Bonemerang"], [62, "EarthPower"], [70, "Outrage"], [80, "Earthquake"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Ground, avistado pela primeira vez nas rotas da região."),
    sp(331, "Cacnea", ["Grass"], [50, 85, 40, 85, 40, 35], 190,
      [[1, "Absorb"], [7, "VineWhip"], [14, "RazorLeaf"], [22, "MegaDrain"], [32, "PetalDance"], [42, "SeedBomb"], [52, "EnergyBall"], [62, "LeafBlade"], [70, "SolarBeam"]],
      [{ speciesId: 332, trigger: "level", level: 32 }],
      "Um Pokémon de Hoenn do tipo Grass, avistado pela primeira vez nas rotas da região."),
    sp(332, "Cacturne", ["Grass", "Dark"], [70, 115, 60, 115, 60, 55], 60,
      [[1, "Absorb"], [7, "VineWhip"], [14, "RazorLeaf"], [22, "MegaDrain"], [32, "Pursuit"], [42, "Bite"], [52, "Crunch"], [62, "EnergyBall"], [70, "LeafBlade"], [80, "SolarBeam"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Grass, avistado pela primeira vez nas rotas da região."),
    sp(333, "Swablu", ["Normal", "Flying"], [45, 40, 60, 40, 75, 50], 255,
      [[1, "Scratch"], [7, "Gust"], [14, "Tackle"], [22, "Peck"], [32, "QuickAttack"], [42, "PayDay"], [52, "Bounce"], [62, "SkullBash"], [70, "TakeDown"], [80, "HyperBeam"]],
      [{ speciesId: 334, trigger: "level", level: 35 }],
      "Um Pokémon de Hoenn do tipo Normal, avistado pela primeira vez nas rotas da região."),
    sp(334, "Altaria", ["Dragon", "Flying"], [75, 70, 90, 70, 105, 80], 45,
      [[1, "Gust"], [7, "Peck"], [14, "Twister"], [22, "AerialAce"], [32, "DragonBreath"], [42, "WingAttack"], [52, "DragonClaw"], [62, "Bounce"], [70, "DragonPulse"], [80, "Outrage"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Dragon, avistado pela primeira vez nas rotas da região."),
    sp(335, "Zangoose", ["Normal"], [73, 115, 60, 60, 60, 90], 90,
      [[1, "Scratch"], [7, "Tackle"], [14, "QuickAttack"], [22, "PayDay"], [32, "ViceGrip"], [42, "Swift"], [52, "ExtremeSpeed"], [62, "SkullBash"], [70, "TakeDown"], [80, "HyperBeam"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Normal, avistado pela primeira vez nas rotas da região."),
    sp(336, "Seviper", ["Poison"], [73, 100, 60, 100, 60, 65], 90,
      [[1, "PoisonSting"], [7, "Acid"], [14, "PoisonFang"], [22, "Sludge"], [32, "PoisonJab"], [42, "SludgeBomb"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Poison, avistado pela primeira vez nas rotas da região."),
    sp(337, "Lunatone", ["Rock", "Psychic"], [90, 55, 65, 95, 85, 70], 45,
      [[1, "RockPolish"], [7, "Confusion"], [14, "RockThrow"], [22, "RockTomb"], [32, "AncientPower"], [42, "Psybeam"], [52, "FutureSight"], [62, "ZenHeadbutt"], [70, "Psychic"], [80, "StoneEdge"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Rock, avistado pela primeira vez nas rotas da região."),
    sp(338, "Solrock", ["Rock", "Psychic"], [90, 95, 85, 55, 65, 70], 45,
      [[1, "RockPolish"], [7, "Confusion"], [14, "RockThrow"], [22, "RockTomb"], [32, "AncientPower"], [42, "Psybeam"], [52, "FutureSight"], [62, "ZenHeadbutt"], [70, "Psychic"], [80, "StoneEdge"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Rock, avistado pela primeira vez nas rotas da região."),
    sp(339, "Barboach", ["Water", "Ground"], [50, 48, 43, 46, 41, 60], 190,
      [[1, "Bubble"], [7, "MudSlap"], [14, "WaterGun"], [22, "MudShot"], [32, "WaterPulse"], [42, "BoneClub"], [52, "EarthPower"], [62, "Crabhammer"], [70, "Earthquake"], [80, "HydroPump"]],
      [{ speciesId: 340, trigger: "level", level: 30 }],
      "Um Pokémon de Hoenn do tipo Water, avistado pela primeira vez nas rotas da região."),
    sp(340, "Whiscash", ["Water", "Ground"], [110, 78, 73, 76, 71, 60], 75,
      [[1, "Bubble"], [7, "MudSlap"], [14, "WaterGun"], [22, "MudShot"], [32, "WaterPulse"], [42, "BoneClub"], [52, "EarthPower"], [62, "Crabhammer"], [70, "Earthquake"], [80, "HydroPump"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Water, avistado pela primeira vez nas rotas da região."),
    sp(341, "Corphish", ["Water"], [43, 80, 65, 50, 35, 35], 205,
      [[1, "Bubble"], [7, "WaterGun"], [14, "WaterPulse"], [22, "BubbleBeam"], [32, "Waterfall"], [42, "Surf"], [52, "Crabhammer"], [62, "HydroPump"]],
      [{ speciesId: 342, trigger: "level", level: 30 }],
      "Um Pokémon de Hoenn do tipo Water, avistado pela primeira vez nas rotas da região."),
    sp(342, "Crawdaunt", ["Water", "Dark"], [63, 120, 85, 90, 55, 55], 155,
      [[1, "Bubble"], [7, "Pursuit"], [14, "WaterGun"], [22, "Bite"], [32, "FeintAttack"], [42, "WaterPulse"], [52, "Crunch"], [62, "Surf"], [70, "Crabhammer"], [80, "HydroPump"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Water, avistado pela primeira vez nas rotas da região."),
    sp(343, "Baltoy", ["Ground", "Psychic"], [40, 40, 55, 40, 70, 55], 255,
      [[1, "MudSlap"], [7, "Confusion"], [14, "MudShot"], [22, "BoneClub"], [32, "Psybeam"], [42, "Dig"], [52, "Bonemerang"], [62, "EarthPower"], [70, "Psychic"], [80, "Earthquake"]],
      [{ speciesId: 344, trigger: "level", level: 36 }],
      "Um Pokémon de Hoenn do tipo Ground, avistado pela primeira vez nas rotas da região."),
    sp(344, "Claydol", ["Ground", "Psychic"], [60, 70, 105, 70, 120, 75], 90,
      [[1, "MudSlap"], [7, "Confusion"], [14, "MudShot"], [22, "BoneClub"], [32, "Psybeam"], [42, "Dig"], [52, "Bonemerang"], [62, "EarthPower"], [70, "Psychic"], [80, "Earthquake"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Ground, avistado pela primeira vez nas rotas da região."),
    sp(345, "Lileep", ["Rock", "Grass"], [66, 41, 77, 61, 87, 23], 45,
      [[1, "Absorb"], [7, "VineWhip"], [14, "RazorLeaf"], [22, "MegaDrain"], [32, "RockPolish"], [42, "RockThrow"], [52, "EnergyBall"], [62, "LeafBlade"], [70, "StoneEdge"], [80, "SolarBeam"]],
      [{ speciesId: 346, trigger: "level", level: 40 }],
      "Um Pokémon de Hoenn do tipo Rock, avistado pela primeira vez nas rotas da região."),
    sp(346, "Cradily", ["Rock", "Grass"], [86, 81, 97, 81, 107, 43], 45,
      [[1, "Absorb"], [7, "VineWhip"], [14, "RazorLeaf"], [22, "MegaDrain"], [32, "RockPolish"], [42, "RockThrow"], [52, "EnergyBall"], [62, "LeafBlade"], [70, "StoneEdge"], [80, "SolarBeam"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Rock, avistado pela primeira vez nas rotas da região."),
    sp(347, "Anorith", ["Rock", "Bug"], [45, 95, 50, 40, 50, 75], 45,
      [[1, "LeechLife"], [7, "FuryCutter"], [14, "RockPolish"], [22, "Twineedle"], [32, "RockThrow"], [42, "RockTomb"], [52, "RockSlide"], [62, "SignalBeam"], [70, "XScissor"], [80, "StoneEdge"]],
      [{ speciesId: 348, trigger: "level", level: 40 }],
      "Um Pokémon de Hoenn do tipo Rock, avistado pela primeira vez nas rotas da região."),
    sp(348, "Armaldo", ["Rock", "Bug"], [75, 125, 100, 70, 80, 45], 45,
      [[1, "LeechLife"], [7, "FuryCutter"], [14, "RockPolish"], [22, "Twineedle"], [32, "RockThrow"], [42, "RockTomb"], [52, "RockSlide"], [62, "SignalBeam"], [70, "XScissor"], [80, "StoneEdge"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Rock, avistado pela primeira vez nas rotas da região."),
    sp(349, "Feebas", ["Water"], [20, 15, 20, 10, 55, 80], 255,
      [[1, "Bubble"], [7, "WaterGun"], [14, "WaterPulse"], [22, "BubbleBeam"], [32, "Waterfall"], [42, "Surf"], [52, "Crabhammer"], [62, "HydroPump"]],
      [{ speciesId: 350, trigger: "item", itemId: EVOLUTION_ITEM_IDS.shinyStone }],
      "Um Pokémon de Hoenn do tipo Water, avistado pela primeira vez nas rotas da região."),
    sp(350, "Milotic", ["Water"], [95, 60, 79, 100, 125, 81], 60,
      [[1, "Bubble"], [7, "WaterGun"], [14, "WaterPulse"], [22, "BubbleBeam"], [32, "Waterfall"], [42, "Surf"], [52, "Crabhammer"], [62, "HydroPump"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Water, avistado pela primeira vez nas rotas da região."),
    sp(351, "Castform", ["Normal"], [70, 70, 70, 70, 70, 70], 45,
      [[1, "Scratch"], [7, "Tackle"], [14, "QuickAttack"], [22, "PayDay"], [32, "ViceGrip"], [42, "Swift"], [52, "ExtremeSpeed"], [62, "SkullBash"], [70, "TakeDown"], [80, "HyperBeam"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Normal, avistado pela primeira vez nas rotas da região."),
    sp(352, "Kecleon", ["Normal"], [60, 90, 70, 60, 120, 40], 200,
      [[1, "Scratch"], [7, "Tackle"], [14, "QuickAttack"], [22, "PayDay"], [32, "ViceGrip"], [42, "Swift"], [52, "ExtremeSpeed"], [62, "SkullBash"], [70, "TakeDown"], [80, "HyperBeam"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Normal, avistado pela primeira vez nas rotas da região."),
    sp(353, "Shuppet", ["Ghost"], [44, 75, 35, 63, 33, 45], 225,
      [[1, "Astonish"], [7, "Lick"], [14, "ShadowSneak"], [22, "ShadowBall"]],
      [{ speciesId: 354, trigger: "level", level: 37 }],
      "Um Pokémon de Hoenn do tipo Ghost, avistado pela primeira vez nas rotas da região."),
    sp(354, "Banette", ["Ghost"], [64, 115, 65, 83, 63, 65], 45,
      [[1, "Astonish"], [7, "Lick"], [14, "ShadowSneak"], [22, "ShadowBall"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Ghost, avistado pela primeira vez nas rotas da região."),
    sp(355, "Duskull", ["Ghost"], [20, 40, 90, 30, 90, 25], 190,
      [[1, "Astonish"], [7, "Lick"], [14, "ShadowSneak"], [22, "ShadowBall"]],
      [{ speciesId: 356, trigger: "level", level: 37 }],
      "Um Pokémon de Hoenn do tipo Ghost, avistado pela primeira vez nas rotas da região."),
    sp(356, "Dusclops", ["Ghost"], [40, 70, 130, 60, 130, 25], 90,
      [[1, "Astonish"], [7, "Lick"], [14, "ShadowSneak"], [22, "ShadowBall"]],
      [{ speciesId: 477, trigger: "item", itemId: EVOLUTION_ITEM_IDS.reaperCloth }], // 6.4-D: Dusknoir
      "Um Pokémon de Hoenn do tipo Ghost, avistado pela primeira vez nas rotas da região."),
    sp(357, "Tropius", ["Grass", "Flying"], [99, 68, 83, 72, 87, 51], 200,
      [[1, "Absorb"], [7, "Gust"], [14, "VineWhip"], [22, "Peck"], [32, "RazorLeaf"], [42, "MegaDrain"], [52, "Bounce"], [62, "EnergyBall"], [70, "LeafBlade"], [80, "SolarBeam"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Grass, avistado pela primeira vez nas rotas da região."),
    sp(358, "Chimecho", ["Psychic"], [75, 50, 80, 95, 90, 65], 45,
      [[1, "Confusion"], [7, "Tackle"], [14, "Psybeam"], [22, "FutureSight"], [32, "ZenHeadbutt"], [42, "Psychic"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Psychic, avistado pela primeira vez nas rotas da região."),
    sp(359, "Absol", ["Dark"], [65, 130, 60, 75, 60, 75], 30,
      [[1, "Pursuit"], [7, "Tackle"], [14, "FeintAttack"], [22, "Bite"], [32, "NightSlash"], [42, "Crunch"], [52, "DarkPulse"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Dark, avistado pela primeira vez nas rotas da região."),
    sp(360, "Wynaut", ["Psychic"], [95, 23, 48, 23, 48, 23], 125,
      [[1, "Confusion"], [7, "Tackle"], [14, "Psybeam"], [22, "FutureSight"], [32, "ZenHeadbutt"], [42, "Psychic"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Psychic, avistado pela primeira vez nas rotas da região."),
    sp(361, "Snorunt", ["Ice"], [50, 50, 50, 50, 50, 50], 190,
      [[1, "IceShard"], [7, "PowderSnow"], [14, "IcyWind"], [22, "IceFang"], [32, "AuroraBeam"], [42, "IcePunch"], [52, "IceBeam"], [62, "Blizzard"]],
      [{ speciesId: 362, trigger: "level", level: 42 }, { speciesId: 478, trigger: "item", itemId: EVOLUTION_ITEM_IDS.dawnStone }], // 6.4-D: Froslass (sem gênero no jogo: a Pedra do Amanhecer decide)
      "Um Pokémon de Hoenn do tipo Ice, avistado pela primeira vez nas rotas da região."),
    sp(362, "Glalie", ["Ice"], [80, 80, 80, 80, 80, 80], 75,
      [[1, "IceShard"], [7, "PowderSnow"], [14, "IcyWind"], [22, "IceFang"], [32, "AuroraBeam"], [42, "IcePunch"], [52, "IceBeam"], [62, "Blizzard"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Ice, avistado pela primeira vez nas rotas da região."),
    sp(363, "Spheal", ["Ice", "Water"], [70, 40, 50, 55, 50, 25], 255,
      [[1, "Bubble"], [7, "IceShard"], [14, "PowderSnow"], [22, "WaterGun"], [32, "IcyWind"], [42, "WaterPulse"], [52, "IceBeam"], [62, "Crabhammer"], [70, "Blizzard"], [80, "HydroPump"]],
      [{ speciesId: 364, trigger: "level", level: 32 }],
      "Um Pokémon de Hoenn do tipo Ice, avistado pela primeira vez nas rotas da região."),
    sp(364, "Sealeo", ["Ice", "Water"], [90, 60, 70, 75, 70, 45], 120,
      [[1, "Bubble"], [7, "IceShard"], [14, "PowderSnow"], [22, "WaterGun"], [32, "IcyWind"], [42, "WaterPulse"], [52, "IceBeam"], [62, "Crabhammer"], [70, "Blizzard"], [80, "HydroPump"]],
      [{ speciesId: 365, trigger: "level", level: 44 }],
      "Um Pokémon de Hoenn do tipo Ice, avistado pela primeira vez nas rotas da região."),
    sp(365, "Walrein", ["Ice", "Water"], [110, 80, 90, 95, 90, 65], 45,
      [[1, "Bubble"], [7, "IceShard"], [14, "PowderSnow"], [22, "WaterGun"], [32, "IcyWind"], [42, "WaterPulse"], [52, "IceBeam"], [62, "Crabhammer"], [70, "Blizzard"], [80, "HydroPump"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Ice, avistado pela primeira vez nas rotas da região."),
    sp(366, "Clamperl", ["Water"], [35, 64, 85, 74, 55, 32], 255,
      [[1, "Bubble"], [7, "WaterGun"], [14, "WaterPulse"], [22, "BubbleBeam"], [32, "Waterfall"], [42, "Surf"], [52, "Crabhammer"], [62, "HydroPump"]],
      [{ speciesId: 367, trigger: "item", itemId: EVOLUTION_ITEM_IDS.dragonScale }, { speciesId: 368, trigger: "item", itemId: EVOLUTION_ITEM_IDS.waterStone }],
      "Um Pokémon de Hoenn do tipo Water, avistado pela primeira vez nas rotas da região."),
    sp(367, "Huntail", ["Water"], [55, 104, 105, 94, 75, 52], 60,
      [[1, "Bubble"], [7, "WaterGun"], [14, "WaterPulse"], [22, "BubbleBeam"], [32, "Waterfall"], [42, "Surf"], [52, "Crabhammer"], [62, "HydroPump"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Water, avistado pela primeira vez nas rotas da região."),
    sp(368, "Gorebyss", ["Water"], [55, 84, 105, 114, 75, 52], 60,
      [[1, "Bubble"], [7, "WaterGun"], [14, "WaterPulse"], [22, "BubbleBeam"], [32, "Waterfall"], [42, "Surf"], [52, "Crabhammer"], [62, "HydroPump"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Water, avistado pela primeira vez nas rotas da região."),
    sp(369, "Relicanth", ["Water", "Rock"], [100, 90, 130, 45, 65, 55], 25,
      [[1, "Bubble"], [7, "WaterGun"], [14, "RockPolish"], [22, "RockThrow"], [32, "RockTomb"], [42, "AncientPower"], [52, "Surf"], [62, "Crabhammer"], [70, "StoneEdge"], [80, "HydroPump"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Water, avistado pela primeira vez nas rotas da região."),
    sp(370, "Luvdisc", ["Water"], [43, 30, 55, 40, 65, 97], 225,
      [[1, "Bubble"], [7, "WaterGun"], [14, "WaterPulse"], [22, "BubbleBeam"], [32, "Waterfall"], [42, "Surf"], [52, "Crabhammer"], [62, "HydroPump"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Water, avistado pela primeira vez nas rotas da região."),
    sp(371, "Bagon", ["Dragon"], [45, 75, 60, 40, 30, 50], 45,
      [[1, "Twister"], [7, "Tackle"], [14, "DragonBreath"], [22, "DragonClaw"], [32, "DragonPulse"], [42, "Outrage"]],
      [{ speciesId: 372, trigger: "level", level: 30 }],
      "Um Pokémon de Hoenn do tipo Dragon, avistado pela primeira vez nas rotas da região."),
    sp(372, "Shelgon", ["Dragon"], [65, 95, 100, 60, 50, 50], 45,
      [[1, "Twister"], [7, "Tackle"], [14, "DragonBreath"], [22, "DragonClaw"], [32, "DragonPulse"], [42, "Outrage"]],
      [{ speciesId: 373, trigger: "level", level: 50 }],
      "Um Pokémon de Hoenn do tipo Dragon, avistado pela primeira vez nas rotas da região."),
    sp(373, "Salamence", ["Dragon", "Flying"], [95, 135, 80, 110, 80, 100], 45,
      [[1, "Gust"], [7, "Peck"], [14, "Twister"], [22, "AerialAce"], [32, "DragonBreath"], [42, "WingAttack"], [52, "DragonClaw"], [62, "Bounce"], [70, "DragonPulse"], [80, "Outrage"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Dragon, avistado pela primeira vez nas rotas da região."),
    sp(374, "Beldum", ["Steel", "Psychic"], [40, 55, 80, 35, 60, 30], 3,
      [[1, "MetalClaw"], [7, "Confusion"], [14, "MagnetBomb"], [22, "Psybeam"], [32, "SteelWing"], [42, "IronHead"], [52, "FlashCannon"], [62, "FutureSight"], [70, "Psychic"], [80, "IronTail"]],
      [{ speciesId: 375, trigger: "level", level: 20 }],
      "Um Pokémon de Hoenn do tipo Steel, avistado pela primeira vez nas rotas da região."),
    sp(375, "Metang", ["Steel", "Psychic"], [60, 75, 100, 55, 80, 50], 3,
      [[1, "MetalClaw"], [7, "Confusion"], [14, "MagnetBomb"], [22, "Psybeam"], [32, "SteelWing"], [42, "IronHead"], [52, "FlashCannon"], [62, "FutureSight"], [70, "Psychic"], [80, "IronTail"]],
      [{ speciesId: 376, trigger: "level", level: 45 }],
      "Um Pokémon de Hoenn do tipo Steel, avistado pela primeira vez nas rotas da região."),
    sp(376, "Metagross", ["Steel", "Psychic"], [80, 135, 130, 95, 90, 70], 3,
      [[1, "MetalClaw"], [7, "Confusion"], [14, "MagnetBomb"], [22, "Psybeam"], [32, "SteelWing"], [42, "IronHead"], [52, "FlashCannon"], [62, "FutureSight"], [70, "Psychic"], [80, "IronTail"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Steel, avistado pela primeira vez nas rotas da região."),
    sp(377, "Regirock", ["Rock"], [80, 100, 200, 50, 100, 50], 3,
      [[1, "RockPolish"], [7, "RockTomb"], [14, "RockThrow"], [22, "AncientPower"], [32, "RockSlide"], [42, "StoneEdge"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Rock, avistado pela primeira vez nas rotas da região."),
    sp(378, "Regice", ["Ice"], [80, 50, 100, 100, 200, 50], 3,
      [[1, "IceShard"], [7, "PowderSnow"], [14, "IcyWind"], [22, "IceFang"], [32, "AuroraBeam"], [42, "IcePunch"], [52, "IceBeam"], [62, "Blizzard"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Ice, avistado pela primeira vez nas rotas da região."),
    sp(379, "Registeel", ["Steel"], [80, 75, 150, 75, 150, 50], 3,
      [[1, "MetalClaw"], [7, "Tackle"], [14, "MagnetBomb"], [22, "SteelWing"], [32, "FlashCannon"], [42, "IronHead"], [52, "IronTail"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Steel, avistado pela primeira vez nas rotas da região."),
    sp(380, "Latias", ["Dragon", "Psychic"], [80, 80, 90, 110, 130, 110], 3,
      [[1, "Twister"], [7, "Confusion"], [14, "DragonBreath"], [22, "Psybeam"], [32, "FutureSight"], [42, "ZenHeadbutt"], [52, "DragonClaw"], [62, "DragonPulse"], [70, "Outrage"], [80, "Psychic"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Dragon, avistado pela primeira vez nas rotas da região."),
    sp(381, "Latios", ["Dragon", "Psychic"], [80, 90, 80, 130, 110, 110], 3,
      [[1, "Twister"], [7, "Confusion"], [14, "DragonBreath"], [22, "Psybeam"], [32, "FutureSight"], [42, "ZenHeadbutt"], [52, "DragonClaw"], [62, "DragonPulse"], [70, "Outrage"], [80, "Psychic"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Dragon, avistado pela primeira vez nas rotas da região."),
    sp(382, "Kyogre", ["Water"], [100, 100, 90, 150, 140, 90], 3,
      [[1, "Bubble"], [7, "WaterGun"], [14, "WaterPulse"], [22, "BubbleBeam"], [32, "Waterfall"], [42, "Surf"], [52, "Crabhammer"], [62, "HydroPump"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Water, avistado pela primeira vez nas rotas da região."),
    sp(383, "Groudon", ["Ground"], [100, 150, 140, 100, 90, 90], 3,
      [[1, "MudSlap"], [7, "Tackle"], [14, "MudShot"], [22, "BoneClub"], [32, "Dig"], [42, "Bonemerang"], [52, "EarthPower"], [62, "Earthquake"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Ground, avistado pela primeira vez nas rotas da região."),
    sp(385, "Jirachi", ["Steel", "Psychic"], [100, 100, 100, 100, 100, 100], 3,
      [[1, "MetalClaw"], [7, "Confusion"], [14, "MagnetBomb"], [22, "Psybeam"], [32, "SteelWing"], [42, "IronHead"], [52, "FlashCannon"], [62, "FutureSight"], [70, "Psychic"], [80, "IronTail"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Steel, avistado pela primeira vez nas rotas da região."),
    sp(386, "Deoxys", ["Psychic"], [50, 150, 50, 150, 50, 150], 3,
      [[1, "Confusion"], [7, "Tackle"], [14, "Psybeam"], [22, "FutureSight"], [32, "ZenHeadbutt"], [42, "Psychic"]],
      undefined,
      "Um Pokémon de Hoenn do tipo Psychic, avistado pela primeira vez nas rotas da região."),
  ];
}
